### ISSUE TITLE
Выгрузка резюме в виде файлов (.doc, .rtf, .pdf, .txt)

### ISSUE THREAD

**Issue by maizy** [hhru/api#106]
.doc, .rtf, .pdf, .txt

Если вам интересна данная возможность, подпишитесь на обновление этого тикета, чтобы получать уведомления о её появлении.

**Comment by andrey158** [comment]
Уточните, пожалуйста, имеется ли в виду парсинг/распознавание резюме? 
Такая функциональность оччччень интересна! :)

**Comment by maizy** [comment]
Нет, имеется ввиду выгрузка в виде готового файла резюме ранее созданного на сайте hh.ru (или через api).

То, что на сайте делается так:
![screen shot 2015-07-13 at 14 14 36](https://cloud.githubusercontent.com/assets/789623/8648443/5528473a-2969-11e5-9167-a65665e3e1f5.png)

**Comment by donkikos** [comment]
Очень нужна фича!

**Comment by AnaToliyZ83** [comment]
Когда планируется реализовать, очень не хватает?

**Comment by a-stankevich-parc** [comment]
интересует!

**Comment by maizy** [comment]
+3 от различных клиентов

**Comment by kholodovitch** [comment]
Наивно искал по документации, думал что имеется уже, а я не замечаю. А оно во как...
Но с другой стороны - API как бы предполагается "чистые" данные должно возвращать. А сгенерённое по каким-то стилям - это уже дело "обёрток".

**Comment by maizy** [comment]
+1 от клиента

**Comment by xirurg2016** [comment]
известны ли сроки выхода?

**Comment by maizy** [comment]
> известны ли сроки выхода?

в данный момент ещё нет

**Comment by rogozin** [comment]
Друзья, стоит ли ожидать появление данной фичи в текущем году?

**Comment by shlima** [comment]
+1

**Comment by yyakhontov** [comment]
Добрый день, да, эта функциональность есть в планах на этот год, но, к сожалению, не стоит ожидать ранее конца 3-го квартала.

**Comment by maizy** [comment]
выпустили функциональность скачивания резюме.
см: https://github.com/hhru/api/blob/master/docs/resumes.md#download-links , а также ключ `download` в различных представлениях резюме.

из поддерживаемых на данный момент форматов .pdf, .rtf

**Comment by maizy** [comment]
про скачивание в других форматах завёл: #266
