### ISSUE TITLE
Работа с отобранными кандидатами для работодателей

### ISSUE THREAD

**Issue by maizy** [hhru/api#107]
- получение/добавление/удаление папок с отобранными кандидатами
- добавление/удаление кандидатов из папок
- передача папок между менеджерами компании
- предоставление доступа к папке другим менеджерам компании
- ...

Если вам интересна данная возможность, подпишитесь на обновление этого тикета, чтобы получать уведомления о её появлении.

**Comment by maizy** [comment]
+1 от клиента

**Comment by xirurg2016** [comment]
интересует

**Comment by joeblack3108** [comment]
+1

**Comment by evhtlt** [comment]
+1

**Comment by hexeh** [comment]
+1

**Comment by bvation** [comment]
+1
