### ISSUE TITLE
Возможность отправить вакансию в несколько городов 

### ISSUE THREAD

**Issue by rik43** [hhru/api#114]
через веб интерфейс можно назначить несколько городов для поиска. 

через апи пробовал так 
"area": [
  {"id": 123},
  {"id": 456},
]

возвращает ошибку, с одним городом работает.

**Comment by maizy** [comment]
В API такой возможности нет. На сайте она как способ облегчения работы. В API просто можно сделать N запросов на каждый регион. Лучше при этом добавить параметр `/vacancies?ignore_duplicates=true`.

**Comment by rik43** [comment]
понял, вопрос снят
