### ISSUE TITLE
Письмо в почтовой рассылке содержит текст samara.hh.ru, хотя получатель в Москве

### ISSUE THREAD

**Issue by shurik2533** [hhru/api#118]
Письмо с темой "HeadHunter: работодатели не знают о Вашем резюме" в почтовой рассылке содержит текст samara.hh.ru, хотя получатель в Москве.

![screenshot from 2015-08-13 11 24 12](https://cloud.githubusercontent.com/assets/4835582/9245873/4979fa8c-41b0-11e5-8acf-0b5349f98866.png)

**Comment by maizy** [comment]
Добрый день. Здесь мы принимает замечания и предложения по работе [HeadHunter API](https://dev.hh.ru/).

Перенаправлю ваше обращение в [поддержку по работе сайта](http://hh.ru/feedback).
