### ISSUE TITLE
Получение откликов "Хочу у Вас работать!"

### ISSUE THREAD

**Issue by AnaToliyZ83** [hhru/api#127]
"Хочу у Вас работать!" – платная услуга у соискателей. Если соискатель выбрал услугу, он отображается в особом списке, а также помечается в выдаче поиска резюме.

Описание работы на сайте: http://hh.ru/article/98

Со стороны API логично видеть флаг в [результатах поиска резюме](https://github.com/hhru/api/blob/master/docs/resumes.md#search), а также отдельный список таких резюме.

---

Если вам интересна данная возможность, подпишитесь на обновление этого тикета, чтобы получать уведомления о её появлении.

**Comment by maizy** [comment]
предложение принято. расширил описание тикета.

**Comment by maizy** [comment]
+1 от клиента

**Comment by almatgs** [comment]
Добрый день! Эта функция появилась в API? В документации не нашел

**Comment by iriss22** [comment]
добрый день, не появилась
