### ISSUE TITLE
Не работает поиск вакансий по валюте

### ISSUE THREAD

**Issue by Zlob** [hhru/api#128]
К примеру, запрос https://api.hh.ru/vacancies?currency=USD
возвращает объекты с 
```json
"salary": {
"to": 100000, 
"from": 100000, 
"currency": "RUR"
}

```

**Comment by maizy** [comment]
Этот параметр работает, не так как вы ожидаете. Он имеет смысл только с указанием валюты (`salary`). 

Даже если указать какую-то валюту будут найдены резюме с указанной вилкой зарплаты вне зависимости от валюты (идёт пересчёт по текущим курсам).

Например запрос `/vacancies?currency=USD&salary=100` выдаст в том числе резюме, где желаемая зарплата ~6600 руб.
