### ISSUE TITLE
Error when refreshing token

### ISSUE THREAD

**Issue by Nyholm** [hhru/api#130]
I get a 400 error when I try to refresh the authentication token. Steps to reproduce: 
1) Get an access token and refresh token pair
2) 2 minutes after, try to send the following HTTP request: 

``` http
POST /oauth/token HTTP/1.1
Host: hh.ru
Content-Type: application/x-www-form-urlencoded
User-Agent: Guzzle/5.3.0 curl/7.43.0 PHP/5.6.12
Content-Length: 103

grant_type=refresh_token&refresh_token=[refresh_token]
```

Am I doing something wrong?

**Comment by maizy** [comment]
Refresh token may be used only after access token expired.

**Comment by Nyholm** [comment]
Okey. I thought I could use it before as well. Thank you.
