### ISSUE TITLE
Что можно передавать в description у вакансии?

### ISSUE THREAD

**Issue by Afigan** [hhru/api#131]
https://github.com/hhru/api/blob/master/docs/vacancies.md#creation

в поле "description" какой html можно передавать, что нибудь подобное:
&lt;span style=&quot;font-family: Arial,
	sans-serif;line-height: 18.2px;&quot;&gt;&#1058;&#1077;&#1082;&#1089;&#1090;&lt;/span&gt; 
нормально отобразится?

**Comment by maizy** [comment]
Рекомендуется ограничиваться простыми html тегами: b, i, em, strong, ul, ol, li.
Таблицы будут вырезаться, ровно как и атрибуты style.

При добавлении или редактировании вакансии мы примем любой HTML, но он будет очищен на нашей стороне.

Ваш пример превратиться в:
```html
<span>Текст</span>
```
