### ISSUE TITLE
Ошибка в отказе на отклик

### ISSUE THREAD

**Issue by AnaToliyZ83** [hhru/api#132]
Действие "отказать" на отклик на вакансию направляется PUT запрос negotiations/discarded/609488725?message=%D0%97%D0%B4%D1%80%D0%B0%D0%B2%D1%81%D1%82%D0%B2%D1%83%D0%B9%D1%82%D0%B5%2C%20%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9%20%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2%D0%B8%D1%87%21%0A%0A%D0%91%D0%BE%D0%BB%D1%8C%D1%88%D0%BE%D0%B5%20%D1%81%D0%BF%D0%B0%D1%81%D0%B8%D0%B1%D0%BE%20%D0%B7%D0%B0%20%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B5%D1%81%2C%20%D0%BF%D1%80%D0%BE%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9%20%D0%BA%20%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%BE%D0%B9%20%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B8%20%22%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%20%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D0%B0%20NPD%22.%20%D0%9A%20%D1%81%D0%BE%D0%B6%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E%2C%20%D0%B2%20%D0%BD%D0%B0%D1%81%D1%82%D0%BE%D1%8F%D1%89%D0%B8%D0%B9%20%D0%BC%D0%BE%D0%BC%D0%B5%D0%BD%D1%82%20%D0%BC%D1%8B%20%D0%BD%D0%B5%20%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D1%8B%20%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C%20%D0%92%D0%B0%D0%BC%20%D1%8D%D1%82%D0%BE%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.%20%D0%9C%D1%8B%20%D0%B2%D0%BD%D0%B8%D0%BC%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%20%D0%BE%D0%B7%D0%BD%D0%B0%D0%BA%D0%BE%D0%BC%D0%B8%D0%BB%D0%B8%D1%81%D1%8C%20%D1%81%20%D0%92%D0%B0%D1%88%D0%B8%D0%BC%20%D1%80%D0%B5%D0%B7%D1%8E%D0%BC%D0%B5%2C%20%D0%B8%2C%20%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%2C%20%D0%B2%D0%B5%D1%80%D0%BD%D0%B5%D0%BC%D1%81%D1%8F%20%D0%BA%20%D0%92%D0%B0%D1%88%D0%B5%D0%B9%20%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D1%83%D1%80%D0%B5%2C%20%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0%20%D1%83%20%D0%BD%D0%B0%D1%81%20%D0%B2%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BD%D0%B5%D1%82%20%D1%82%D0%B0%D0%BA%D0%B0%D1%8F%20%D0%BF%D0%BE%D1%82%D1%80%D0%B5%D0%B1%D0%BD%D0%BE%D1%81%D1%82%D1%8C.%0A%0A%D0%A1%20%D1%83%D0%B2%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC%2C%0A%D0%92%D0%BE%D1%80%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0%20%D0%A2%D0%B0%D1%82%D1%8C%D1%8F%D0%BD%D0%B0

получаю ответ с ошибкой
код: 413
тело ответа: <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>

**Comment by maizy** [comment]
Параметры PUT/POST/DELETE запросов рекомендуется отправлять в теле запроса (с типом application/x-www-form-urlencoded), а не в query.

Запросы с длинными query мы отбрасываем.

**Comment by AnaToliyZ83** [comment]
Спасибо. Исправил. Заработало.
