### ISSUE TITLE
Ошибка входа через mail.ru

### ISSUE THREAD

**Issue by agent868** [hhru/api#136]
При попытке входа на hh.ru через mail.ru - ошибка (Bad request)
![hh_mail ru](https://cloud.githubusercontent.com/assets/15254190/10676864/a01493a0-7911-11e5-821e-591c4e30b670.png)

**Comment by maizy** [comment]
FYI мы не забыли о проблеме. разбираемся, о результатах напишу позднее.

**Comment by maizy** [comment]
Мы уже знаем о данной проблеме и сейчас работаем над её решением, проблема проявляется и в работе основных сайтов (hh.ru, hh.ua ...).

Текущий work around – сбросить в браузере cookies доменов hhid.ru и hh.ru.

Я отпишусь в тикет, когда проблема будет закрыта.

**Comment by maizy** [comment]
В данный момент проблема решена.
Если вдруг проблема не перестаёт проявляться, обязательно напишите нам об этом.
