### ISSUE TITLE
Вернуть вакансию из архива

### ISSUE THREAD

**Issue by Afigan** [hhru/api#137]
Здравствуйте!
PUT /employers/{employer_id}/vacancies/archived/{vacancy_id}
этим запросом можно отправить вакансию в архив.
каким запросом можно вакансию сделать вновь опубликованной? т.е. вернуть их архива назад в опубликованные.

**Comment by maizy** [comment]
это невозможно (и на сайте тоже).
если это произошло случайно, попробуйте обратиться к персональному менеджеру (на сайте можно получить его контакты), возможно он сможет помочь.
