### ISSUE TITLE
Кнопка пляшет на hover

### ISSUE THREAD

**Issue by c01nd01r** [hhru/api#138]
Сообщество поддержки (http://feedback.hh.ru/), комментирование ответа в теме.
#form_answer_comment_form > div.d-answer.f-right > div.d-actions > button.button-green.f-right.need-auth

![2015-10-26 12 50 16](https://cloud.githubusercontent.com/assets/3511312/10724805/605e9d40-7bd8-11e5-9a74-bc47ce2440cc.png)
При наведении
![2015-10-26 12 51 04](https://cloud.githubusercontent.com/assets/3511312/10724806/606403a2-7bd8-11e5-9776-2afde521cd86.png)

**Comment by maizy** [comment]
Добрый день. В этом репозитории рассматриваются только обращения по HeadHunter API.
Я перенаправлю ваше замечание разработчикам feedback.hh.ru

**Comment by c01nd01r** [comment]
Пардон, обратной связи для таких случаев я не нашел :bow:

**Comment by maizy** [comment]
Обратная связь по сайтам здесь: http://hh.ru/feedback
