### ISSUE TITLE
201 статус на публикацию вакансии

### ISSUE THREAD

**Issue by oyajiro** [hhru/api#140]
Здравствуйте, во время публикации вакансии получили 201й статус. В документации есть только описание для 204, 403 и 400. Как трактовать 201й? Вакансия опубликовалась или нет?

**Comment by maizy** [comment]
201 - означает, что вакансия опубликована.

В документации была ошибка, [исправили](https://github.com/hhru/api/commit/96b3922375ae455f1dbc8e88750e7f7cb3632357), спасибо за замечание.
