### ISSUE TITLE
Вакансии похожие на другую вакансию

### ISSUE THREAD

**Issue by DrDeath72** [hhru/api#142]
Нужен способ найти указанное кол-во похожих вакансий 
Как вариант параметр vacancy_id для /vacancies с учетом всех остальных параметров

**Comment by maizy** [comment]
Такая возможность планируется. Точнее по срокам сориентировать пока не могу.

**Comment by maizy** [comment]
добавили такую возможность
https://github.com/hhru/api/blob/master/docs/vacancies.md#similar
