### ISSUE TITLE
Описать в документации популярные примеры использования API

### ISSUE THREAD

**Issue by ateregulov** [hhru/api#143]
Для того кто видит API первый раз, более интересно - как он может это API для себя использовать, а не формат тела запроса. Интересные зачем создано API, как оно будет развиваться, какие виды и типы информации доступны, а какие закрыты. Интересны кейсы использования.

**Comment by Altair4713** [comment]
Ну простым пользователям и соискателям этот API не особо нужен, а вот кадровым агентствам, компаниям, которые частенько ищут новых сотрудников и т.д. вполне себе может пригодиться.

**Comment by maizy** [comment]
@Altair4713 говорит верно. Соискателя напрямую API не совсем интересен, скорее API будут использовать разработчики приложений для соискателей. Как, например, использует API официальные приложения HeadHunter для iOs/Android/Winphone.

В общем и целом возможности API можно понять по [списку доступных в нём ресурсов](https://github.com/hhru/api#Ресурсы).

Идея описать популярные use case и паттерны использования API выглядет достаточно интерсной и принимается как идея на будущее.

Немного поменял описание тикета, если вы против, напишите.

**Comment by iriss22** [comment]
добавили FAQ: https://github.com/hhru/api/blob/master/docs/FAQ.md
будем расширять по мере необходимости
