### ISSUE TITLE
Отсутствующий заголовок CORS при запросе hh.ru/oauth/token

### ISSUE THREAD

**Issue by TRechkalov** [hhru/api#144]
Здравствуйте!
Я пытаюсь подключить механизм авторизации с помощью javascript из страницы браузера. Запросы выполняются с помощью jQuery ajax. При работе с тестовым URL https://api.hh.ru/cors все работает хорошо. При использовании https://hh.ru/oauth/token запрос получивший 200 статус считается невалидным, потому что у него отсутствует заголовок access-control-allow-origin. Этот заголовок присутствует для https://api.hh.ru/cors.

Можно ли добавить этот заголовок?

![cors token error](https://cloud.githubusercontent.com/assets/8432444/11516179/9d65af0c-98a3-11e5-8c9d-39fa438aae6a.jpg)
![cors example ok](https://cloud.githubusercontent.com/assets/8432444/11516180/9d6aaec6-98a3-11e5-8ffe-081fcf707a14.jpg)

**Comment by maizy** [comment]
https://hh.ru/oauth/token – это url для аунтификации. Вы не должны запрашивать его через AJAX запросы, вместо это нужно открыть iframe/popup для пользователя, где он проведёт авторизацию самостоятельно (введёт свои логин/пароль, подтвердит доступ приложению и прочее).

Есть пример проведения авторизации практически в браузере (extension для chrome), там можно подчерпнуть, как такое делать без участия сервера: https://github.com/maizy/chrome-extension-hh-oauth

Понадобятся две страницы с js кодом на одном домене: одна основная, где авторизация запрашивается, вторая дополнительная, которая обработает данные, пришедшие в redirect_uri после окончания авторизации и вернёт управление первой.

Подробнее про процесс авторизации: https://github.com/hhru/api/blob/master/docs/authorization.md

**Comment by maizy** [comment]
Мы исследовали этот вопрос и поняли, что в текущей концепции исправить это не возможно из-за соображений безопасности. Вам пока придётся использовать server side запросы для двух случаев: обмена authorization_code на access и refresh токены и обновление токена по истечению времени жизни.

Мы понимаем, что такая возможность полезна, но она будет реализована по каким-то другим технологиям и процессам. Я завёл тикет, чтобы можно было отслеживать появление такой возможности #149 .
