### ISSUE TITLE
Авторизация в API целиком в браузере

### ISSUE THREAD

**Issue by maizy** [hhru/api#149]
В данный момент провести авторизацию в HH API целиком в браузере не возможно.
Единтсвенное, что требует серверной части это обмен [временного authorization_code на пару `access` и `refresh` токенов](https://github.com/hhru/api/blob/master/docs/authorization.md#get-tokens).
А также [обмен refresh токена на новую пару токенов](https://github.com/hhru/api/blob/master/docs/authorization.md#refresh_token) по истечению жизни access токена.

Эти процедуры требуют отправки POST запроса на `https://hh.ru/oauth/*`, где такие запросы будут заблокированы из-за отсутствия `Access-Control-Allow-Origin` заголовков. Это сделано по соображениям безопасности.

Также при обмене authorization_code требуется передавать client_secret, которой задуман как закрытый ключ приложения, который не должен быть доступен пользователям.

Вероятно, будет имплементирован [implicit grand type  из RFC-6749](https://tools.ietf.org/html/rfc6749#section-1.3.2), но мы будем думать над всеми ограничениями и проблемами безопасности, которые этот метод несёт (cм. [10.3](https://tools.ietf.org/html/rfc6749#section-10.3) и [10.16](https://tools.ietf.org/html/rfc6749#section-10.16).

---

Если вам интересна данная возможность, подпишитесь на обновление этого тикета, чтобы получать уведомления о её появлении.

---

linked: #144 #126 #168

**Comment by Disorrder** [comment]
В дополнение этой возможности не помешало бы JS SDK. Например, удобно работать с Linkedin, vkontakte, facebook...
https://developer.linkedin.com/docs/signin-with-linkedin

**Comment by maizy** [comment]
+1 от клиента

**Comment by avoitovich** [comment]
А можно также наоборот - авторизацию без браузера? Я пишу базу на 1С для учета деятельности HR-отдела. Для упрощения загрузки резюме качаю его прямо с HH.ru через API. Но для авторизации без браузера приходится эмулировать отправку формы с логином/пароем и кучу редиректов. Не очень удобно... Можно как-то через API вызов принять логин\пароль и выдать authorization_code?

**Comment by iriss22** [comment]
в ближайшее время реализовано не будет

**Comment by mediaexplorer74** [comment]
> А можно также наоборот - авторизацию без браузера? Я пишу базу на 1С для учета деятельности HR-отдела. Для упрощения загрузки резюме качаю его прямо с HH.ru через API. Но для авторизации без браузера приходится эмулировать отправку формы с логином/пароем и кучу редиректов. Не очень удобно... Можно как-то через API вызов принять логин\пароль и выдать authorization_code?

Вы это не на C# делали случайно?

**Comment by Andrew213** [comment]
До сих пор https://api.hh.ru/token делать через сервер? 

![image](https://github.com/hhru/api/assets/51080918/d024ebdd-d371-4842-9d94-e98edcb3d63b)

![image](https://github.com/hhru/api/assets/51080918/4791834e-927a-4270-bbd0-852ea202300a)

**Comment by DanilKnyazev** [comment]
> До сих пор https://api.hh.ru/token делать через сервер?
> 
> ![image](https://private-user-images.githubusercontent.com/51080918/313819042-d024ebdd-d371-4842-9d94-e98edcb3d63b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzEyMDYsIm5iZiI6MTcxMDgzMDkwNiwicGF0aCI6Ii81MTA4MDkxOC8zMTM4MTkwNDItZDAyNGViZGQtZDM3MS00ODQyLTlkOTQtZTk4ZWRjYjNkNjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA2NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNzYyNDI2ODYwYTIwZDA1YTE2MjVlYjRjYTUzNmU1NGMzNzY0YjE1OWYzNDFjNWNlZmFlODNjZjE3Y2YwZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ymsGV-JD3etXXCKIk2KuKuqVud-BxZJW4Zf0ENs7CSo)
> 
> ![image](https://private-user-images.githubusercontent.com/51080918/313819119-4791834e-927a-4270-bbd0-852ea202300a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzEyMDYsIm5iZiI6MTcxMDgzMDkwNiwicGF0aCI6Ii81MTA4MDkxOC8zMTM4MTkxMTktNDc5MTgzNGUtOTI3YS00MjcwLWJiZDAtODUyZWEyMDIzMDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA2NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MTlmNjlmNGYzN2Q4ZDViOWRjNzYxZjAyMTBlNzlmNjFlMTFiMWVkNDIwODM2MzUxNGNjNzczMmFlNmIyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wXeLBX2Z_SNV3p2NuFhFx0bCWglYloj3HTQe4_Zb5Wc)

да. Тут ничего не изменилось
