### ISSUE TITLE
Страница вакансии. Контакты. Ошибка

### ISSUE THREAD

**Issue by p2972014** [hhru/api#151]
После указании логина skype в своём резюме на странице резюме в разделе контактов отображаются  
LinkedIn
Facebook
Free-lance
LiveJournal
хотя я их не указывал.
Проверено под opera 12 и firefox 43.

**Comment by maizy** [comment]
@p2972014 вы указываете skype логин через API (`POST /resumes`)? Или на сайте hh.ru?

**Comment by p2972014** [comment]
на сайте hh.ru

**Comment by maizy** [comment]
Напишите, пожалуйста, в поддержку по сайту: http://hh.ru/feedback
