### ISSUE TITLE
Проблема получения адресов работодателей

### ISSUE THREAD

**Issue by ilogman** [hhru/api#153]
Пытался получить адреса работодателя по адресу https://api.hh.ru/employers/*/addresses с любыми токенами и работодателя и соискателя возврашает 403. Какой токен нужен, что бы метод отработал корректно? Т.к. в документации по этому методу не нашел информации.

**Comment by maizy** [comment]
Для этого нужно заходить с авторизацией менеджера соответствующей компании (работодателя).
Какой id компании у текущего пользователя, можно узнать в `/me`.
