### ISSUE TITLE
Отсутсвует описание client_secret={client_secret} в документаци.

### ISSUE THREAD

**Issue by ferzescu** [hhru/api#162]
Здравствуйте!
Согласно документации зарегистрировал приложение, перешел по ссылке для авторизации, в ответ был редирект на адрес с параметром Code=...
Однако дальше, для получения access_token необходимо отправить POST запрос, в котором необходимо указать client_secret.
Не нашел в документации описания этого параметра. Могли бы Вы подсказать, где я могу его найти. Спасибо

**Comment by maizy** [comment]
В целом статья про авторизацию:
https://github.com/hhru/api/blob/master/docs/authorization.md

Конкретно client_secret упоминается в получении access токена в обмен на временный код:
https://github.com/hhru/api/blob/master/docs/authorization.md#Получение-access-и-refresh-токенов

**Comment by maizy** [comment]
> Не нашел в документации описания этого параметра. Могли бы Вы подсказать, где я могу его найти.

Client secret будет написан в ЛК (https://dev.hh.ru/admin) после регистрации приложения

**Comment by ferzescu** [comment]
Всё, спасибо огромное. 
Думаю всё-таки в документации стоит упомянуть, откуда брать этот параметр.

**Comment by maizy** [comment]
справедливое замечание. добавим.
