### ISSUE TITLE
Получение списка резюме пользователя.

### ISSUE THREAD

**Issue by ferzescu** [hhru/api#163]
Здравствуйте!
Подскажите, пожалуйста, как с помощью авторизированного приложения я могу получить список активных резюме пользователя, если у меня есть access_token?
Спасибо.

**Comment by maizy** [comment]
https://github.com/hhru/api/blob/master/docs/resumes.md#mine

**Comment by ferzescu** [comment]
Спасибо. Это я видел. 
Подскажите как я могу заправить такой запрос из curl?

**Comment by maizy** [comment]
`curl -v -H 'Authorization: Bearer ACCESS_CODE' https://api.hh.ru/resumes/mine`

**Comment by ferzescu** [comment]
от души.
