### ISSUE TITLE
Напишите более подробно о истчении authorization_code

### ISSUE THREAD

**Issue by caxepok** [hhru/api#166]
документации Authorization.md есть строка

> authorization_code  имеет довольно короткий срок жизни, при его истечении необходимо запросить новый.

Может имелось ввиду access_code? Если да, то поправьте документацию, если нет, то напишите подробнее об этом.

**Comment by 0rbitr** [comment]
Я так понимаю речь шла именно о authorization_code, т.к. когда я попытался через около полу часа после получения authorization_code использовать его мне выдавало ошибку. Мне, кстати, тоже хотелось бы узнать как долго он действителен.

**Comment by iriss22** [comment]
Мы специально не описываем в документации эту информацию, т.к. она может измениться.
