### ISSUE TITLE
Ошибка отправки вакансии в архив

### ISSUE THREAD

**Issue by AnaToliyZ83** [hhru/api#170]
PUT: api.hh.ru/employers/1038532/vacancies/archived/16771565
Возвращает ошибку:
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.8.1</center>
</body>
</html>

**Comment by nmiroshnichenko** [comment]
какое вы шлете тело запроса? (должно быть пустое)

**Comment by AnaToliyZ83** [comment]
Тело запроса пустое.

**Comment by nmiroshnichenko** [comment]
пришлите, пождалуйста, содержимое заголовка X-Request-Id ответа сервера, посмотрим в логах, что происходит с вашим запросом

**Comment by AnaToliyZ83** [comment]
1462884117568737f228483110faf29e

**Comment by nmiroshnichenko** [comment]
логи сможем посмотреть позже (в худшем случае завтра), но вряд ли там что-то новое будет, это же ответ от nginx о том, что вы шлете слишком большое тело запроса, попробуйте другим клиентом отправить запрос
например curl

**Comment by nmiroshnichenko** [comment]
посмотрели логи, ваш клиент пытался отправить более 50мб в теле запроса
