### ISSUE TITLE
"Песочница" для разработчиков

### ISSUE THREAD

**Issue by ghost** [hhru/api#179]
Было здорово иметь что-то подобное, потому что сейчас невозможно реализовать поддержку API hh.ru для "работодателя", не имея реального аккаунта оного. 
Например, dev.api.hh.ru с каким-нибудь минимальным набором данных (фейковых?) и регистрацией по запросу.

**Comment by t1mekiller** [comment]
Здравствуйте!
Предложение по вашему МП: во время использования МП появляется окошко с просьбой оценить приложение и дать коммент. Но пользователи неохотно это делают, им никаких плюшек за это нет. **Если вам интересно нарастить отзывы/комменты, то можно предложить систему бонусов.**
**Сделайте что-то типо временного бонуса за голос+оценку, к примеру: оставил отзыв - резюме будет висеть 3 дня в топе из других со схожими параметрами.** По крайне мере соискатели будут голосовать охотнее. В общем, идея требует доработки, но думаю тема живая
