### ISSUE TITLE
Уведомление (webhook) о новых откликах

### ISSUE THREAD

**Issue by VladimirPal** [hhru/api#180]
Здравствуйте!
Не нашел в документации, поэтому спрашиваю тут.
Есть ли возможность получать уведомления о новых откликах на вакансию? Например чтоб webhook дергался?

**Comment by maizy** [comment]
в данный момент такой возможности нет

**Comment by rogozin** [comment]
Коллеги, это была бы очень замечательная фича, рассмотрите пожалуйста!

**Comment by shlima** [comment]
+1

**Comment by burstmeman** [comment]
эх, жаль в данный момент реализации ещё нет

**Comment by 2naive** [comment]
А в планах есть?

**Comment by iriss22** [comment]
пока что нет
