### ISSUE TITLE
баг в e-mail рассылке

### ISSUE THREAD

**Issue by khazamov** [hhru/api#181]
Не уверен, что это  относится непосредственно к API, но так будет быстрее. Возможно будет хорошей идеей сделать cross reference вакансий, предлагаемых соискателю в рассылке с теми вакансиями, на которые он уже откликнулся и  исключить вакансии, которые имеют какой-либо статус отклика - например, если это статус "отказ" :)

**Comment by maizy** [comment]
Перенаправте ваш вопрос, пожалуйста, сюда:
https://hh.ru/feedback

Он действительно к API не имеет отношения.
