### ISSUE TITLE
Проверка access_token: token_revoked

### ISSUE THREAD

**Issue by AlekseyPiyadin** [hhru/api#183]
Сгенерировал новый access_token. Пытаюсь отправить запрос для проверки:
GET /me HTTP/1.1
Host: api.hh.ru
User-Agent: api-test-agent
Accept: */*
Authorization: Bearer PI5J6HH6HM62AGC0LF7T7253UCSH3409G13P78VA0DSIEQ5OHTRGJ84EVTK8S1D4

Всё время получаю одну и ту же ошибку 403: token-revoked
Перегенерация токена не помогает.

Использую Postman для генерации токена с авторизацией Oauth2, а также для отправки запросов.
![postman](https://cloud.githubusercontent.com/assets/15829842/16804941/b996aeb4-4916-11e6-8aec-a853573cee00.JPG)

**Comment by vera-l** [comment]
Попробуйте зайти под своими учетными данными на сайт hh.ru.
Возможно, вам необходимо восстановить пароль.

**Comment by AlekseyPiyadin** [comment]
Изменил пароль через hh.ru на новый.
При запросе токена выбрал "Это не мой профиль". Заново ввёл логин/пароль.
Получил сгенерированный токен.
Проблема решена.
