### ISSUE TITLE
ответ на /negotiations/hold/ такой {"errors": [{"type": "not_found"}]}

### ISSUE THREAD

**Issue by hlopikit** [hhru/api#184]
В ответ на /negotiations/hold/ стал приходить такой ответ
приходит 404 такой {"errors": [{"type": "not_found"}]}

Раньше работало нормально

В документации не нашел такой ошибки
https://github.com/hhru/api/blob/master/docs/employer_negotiations.md#actions

**Comment by vera-l** [comment]
Пришлите, пожалуйста, url запроса с параметрами и заголовками на адрес api@hh.ru

**Comment by hlopikit** [comment]
Добрый день.

https://github.com/hhru/api/issues/184

curl "https://api.hh.ru//negotiations/hold/748122149" -X POST -H "Pragma:
no-cache" -H "Origin: chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm"
-H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language:
ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4" -H "Authorization: Bearer
SI5318QH34VOCOTAT7TF41BGFTQM32C14J2QBALPONRT844KJGOAMEKN7IDOH8RH" -H
"Accept: */*" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
-H "Cache-Control: no-cache" -H "Cookie:
__gfp_64b=vJCHrvqs0W2H5dCyvTxU5relqTei.cN.jenAaeA5E63.07; vishnu1.cuid=;
vishnu1.userid=E48DCE8737934DAE1C1A410F6E456CB6A5471C6F722104504734B32F0D03E9F8;
_ym_uid=1462354837114490805; hhtoken=vj6AOxgry3OPSYrPUFxv_8PY18JJ;
hhuid=Kffufxnk40FBplVckXI9Ww--; _ym_isad=2;
_ga=GA1.2.1838222305.1443609728;
crypted_id=E48DCE8737934DAE1C1A410F6E456CB6A5471C6F722104504734B32F0D03E9F8;
_ym_visorc_156828=w; _xsrf=d0c7009e67fbe00fbf0520221cfa3655" -H
"Connection: keep-alive" -H "Content-Length: 0" --compressed

2016-07-13 16:41 GMT+03:00 Vera Lobacheva <notifications@github.com>:

**Comment by hlopikit** [comment]
Понял почему.

Раньше работало если урл с двойным слешем
https://api.hh.ru**//**negotiations/hold/748122149

теперь стал на это ругаться
