### ISSUE TITLE
Поиск резюме с пометкой о просмотре

### ISSUE THREAD

**Issue by rozhkovms** [hhru/api#192]
Было бы хорошо, если бы была возможность при поиске резюме получать информацию о статусе просмотра этого резюме.
Сейчас при запросе (GET /resumes) из внешней системы не понятно, просматривалось данное резюме пользователем или нет. В итоге, открывается сохраненный запрос с сотней резюме и какие из них уже просмотрены - не понятно.

**Comment by maizy** [comment]
идея принята. по срокам реалиализации, сказать пока не могу.

**Comment by dev-requestserver** [comment]
Метод поиска остался активным? Я понял, что в сентябре его убрали.

**Comment by maizy** [comment]
всё так, поиска резюме в API более нет. закрываю тикет.

**Comment by dev-requestserver** [comment]
Публично нет или оплаченным работодателем все же доступно?

**Comment by yyakhontov** [comment]
Нет, к сожалению недоступно никому.

**Comment by dev-requestserver** [comment]
А по ID просмотр резюме не планируется убирать?

**Comment by yyakhontov** [comment]
Нет, в просмотр резюме будет доступен.

**Comment by rozhkovms** [comment]
А в связи с чем убрали этот метод?
