### ISSUE TITLE
Дублирование вакансий при поиске с использованием date_from,date_to

### ISSUE THREAD

**Issue by kotovdv** [hhru/api#200]
При поиске на определенных диапазонах периодически встречаются дубликаты вакансий.

Пример:
Запрос 1:
https://api.hh.ru/vacancies?date_from=2016-10-21T14:03:00&date_to=2016-10-21T14:06:00
Запрос 2:
https://api.hh.ru/vacancies?date_from=2016-10-21T14:06:00&date_to=2016-10-21T14:09:00

Оба результата запроса на момент исполнения содержали данные по вакансиям с идентификаторами:

> 
> 18315302
> 18663744
> 18748878
> 18748877
> 18492983
> 18748876
> 18748875
> 18540192
> 18546900
> 18545986
> 18748874
> 18530981
> 17537808
> 17615766
> 18708879
> 18748873
> 18594551
> 18748872
> 18594550
> 18692002

Если смотреть на примере вакансии 18315302. 
Она была опубликована "published_at":"2016-10-21T14:09:55+0300"

Вопрос в том, почему она попадает в эти выборки в принципе?

**Comment by maizy** [comment]
Время в параметрах поиска вакансий округляется с шагом в 5 минут (условно 10:00 - 10:05, 10:05-10:10 ...). Поэтому маленькие промежутки времени лучше не использовать. Это техническое ограничение, возможно, со временем поменяется.

Если вам нужно получать через такой запрос новые вакансии по какому-либо запросу, будьте готовы на своей стороне отфильтровать дубликаты.
