### ISSUE TITLE
интеграция с Boomi

### ISSUE THREAD

**Issue by Lajgut** [hhru/api#202]
Добрый день, пытаюсь законнектиться с помощью интеграционной шины Dell Boomi, программа говорит что все корректно, никаких ошибок нет, но в ответ не приходит ничего, никаких подтверждений со стороны внешнего ресурса о том что подключение работает.

**Comment by maizy** [comment]
В таком виде мы и у себя не сможем никаких подробностей добыть.

Какие HTTP запросы отправляет эта система? Можно ли получить тело и заголовки ответа и запроса от серверов HH API?

**Comment by Lajgut** [comment]
Дело в том что вся система находиться на облаке и не понятно как это получить оттуда. Скажите а есть какой нибудь форму по работе с вашим api? может кто то уже сталкивался с такой проблемаэой


Отправлено с устройства Samsung

-------- Исходное сообщение --------
От: Nikita Kovalev <notifications@github.com> 
Дата: 27.10.2016  15:56  (GMT+03:00) 
Кому: hhru/api <api@noreply.github.com> 
Копия: Lajgut <kirbitkov@mail.ru>, Author <author@noreply.github.com> 
Тема: Re: [hhru/api] интеграция с Boomi (#202) 

В таком виде мы и у себя не сможем никаких подробностей добыть.

Какие HTTP запросы отправляет эта система? Можно ли получить тело и заголовки ответа и запроса от серверов HH API?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hhru/api","title":"hhru/api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hhru/api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maizy in #202: В таком виде мы и у себя не сможем никаких подробностей добыть.\r\n\r\nКакие HTTP запросы отправляет эта система? Можно ли получить тело и заголовки ответа и запроса от серверов HH API?"}],"action":{"name":"View Issue","url":"https://github.com/hhru/api/issues/202#issuecomment-256632965"}}}

**Comment by maizy** [comment]
формат API описан в документации https://github.com/hhru/api, он подразумевает различные HTTP запросы, где результаты возвращаются в виде json.
примеров использования Dell Boomi с API HH мне не известно.

HH API не поддерживает в данный момент каких-либо стандартных протоколов, на которые мог бы надеятся Dell Boomi. Чтобы использовать HH API разработчики Dell Boomi должны были написать специальную поддержку в своём продукте.

обратитесь в поддержку Dell Boomi, при необходимости они могут обратиться с техническими вопросами к нам на email: api@hh.ru
