### ISSUE TITLE
Идентификатор автора сообщения в комментариях к соискателю

### ISSUE THREAD

**Issue by maizy** [hhru/api#206]
У работодателя в [списке комментариев по соискателю](https://github.com/hhru/api/blob/master/docs/applicant_comments.md#list) у работодателя не отражается какой-либо идентификатор, позволяющий сопоставить автора с [менеджерами компании](https://github.com/hhru/api/blob/master/docs/employer_managers.md).

----

Если вам интересна данная возможность, подпишитесь на обновление этого тикета, чтобы получать уведомления о её появлении.

Также за тикет можно проголосовать 👍 .

**Comment by agiltrue** [comment]
Не увидел изменений в API. Подскажите, какой идентификатор автора добавлен?
