### ISSUE TITLE
Просмотр резюме под авторизованным пользователем.

### ISSUE THREAD

**Issue by andrcher** [hhru/api#207]
Под авторизованным пользователем делаю GET-запрос на просмотр резюме, в ответ приходит 404 NotFound. Делаю такой же запрос, только без параметра Authorization в Headers, данные по резюме приходят. В чем причина такого поведения api? Почему под анонимусом данные видны, а под авторизованным пользователем с использованием access-токена - нет?

**Comment by maizy** [comment]
это может зависеть от разных факторов. для начала, нужно понять, как вы получили ссылку на резюме: отклики/приглашения, напрямую от соискателя или ещё как-то, от этого может зависеть поведение API.

также важно с какой авторизацией вы просматривали резюме: работодатель или соискатель.

пришлите, пожалуйста, пример запроса/ответа с заголовками и телом на api@hh.ru, мы посмотрим в чём была точная причина.

**Comment by andrcher** [comment]
Резюме просматривалось с ролью работодателя, ссылка на резюме была получена копированием из адресной строки, а затем с помощью парсера вытащен id резюме для запроса к api. Что важно, такое поведение не со всеми ссылками происходит, только с некоторыми.

**Comment by yyakhontov** [comment]
Добрый день, уточните - на какой адрес вы переслали информацию?

**Comment by andrcher** [comment]
Добрый, на api@hh.ru.

**Comment by maizy** [comment]
к сожалению, не получили от вас письма. попробуйте, пожалуйста, отправить с какого-нибудь другого почтового ящика.

**Comment by andrcher** [comment]
Отправил повторно с gmail аккаунта.

**Comment by maizy** [comment]
для истории продублирую ответ и тут:

Анонимный запрос работает, так как резюме, которое запрашивается создано с типом доступа "видно всему интернету", поэтому оно отображается для анонимного пользователя, но в таком виде по нему не доступна контактная информация соискателя (ФИО, телефон, email ...).

Авторизованный запрос не работает, так как id резюме было получено менеджером одной компании, а запрашивается менеджером другой компании. Такие запросы мы намерено блокируем. Если приложение каким-либо образом получает id резюме с сайта или писем оповещений или ещё как-то, резюме необходимо запрашивать в API от лица менеджера той же компании.
