### ISSUE TITLE
Получение более 2000 вакансий работодателя

### ISSUE THREAD

**Issue by dyfilatov** [hhru/api#209]
Невозможно получить больше 2000 архивных вакансий. С активными вакансиями не проверял.
Api выдаёт 30 страниц с вакансиями по 100 штук. После (включительно) 20 страницы выдаёт ошибку: Удаленный сервер возвратил ошибку: (400) Недопустимый запрос.

**Comment by maizy** [comment]
Ошибка с нашей стороны. Правим. Отпишусь сюда по завершению.

**Comment by maizy** [comment]
в архивных и удалённых вакансиях работодетеля тоже есть проблема.
работаем над исправлением.

**Comment by maizy** [comment]
проблема исправлена.
