### ISSUE TITLE
не работает post artifacts для резюме

### ISSUE THREAD

**Issue by mSok** [hhru/api#211]
делаю POST /artifacts с помощью python библиотеки requests, каждый раз возвращается ошибка b'{"errors":[{"type":"bad_argument","value":"file"}]}'.
пробовал разные варианты, каждый раз одно и тоже.

**Comment by maizy** [comment]
мы принимает данные в формате multipart form data (https://tools.ietf.org/html/rfc7578).
насколько я вижу requests это формат поддерживает - http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file

пришлите, пожалуйста, какие-то фрагменты кода или другие подробности того, как отправляются запросы из библиотеки.
я к сожалению не знаю как работает requests внутри и как но формирует запросы, возможно есть какая-то ошибка на стороне библиотеки.

**Comment by maizy** [comment]
нашлась минутка проверить библиотеку requests.
в ней всё работает правильно, по крайней мере в версии 2.12.3

```python
#!/usr/bin/env python3
# encoding: utf-8

import requests
import sys

print('python: {}'.format(sys.version))
print('requests: {}'.format(requests.__version__))

file_name = 'test.png'
auth_token = 'ABCDEF...'  # insert your own access key

url = 'https://api.hh.ru/artifacts'

r = requests.post(url, files={'file': open('test.png', 'rb')}, data={'type': 'portfolio', 'description': 'test upload'},
                  headers={'Authorization': 'Bearer {}'.format(auth_token)})
print('Response code: {}'.format(r.status_code))
print('Response body: {}'.format(r.text))

```

рез-тат
```
> python3 test_requests.py

python: 3.5.2 (default, Nov 24 2016, 11:23:49)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
requests: 2.12.3
Response code: 201
Response body: {"small":null,"state":{"id":"processing","name":"в обработке"},"medium":null,"id":"104382498","description":"test upload"}
```

**Comment by mSok** [comment]
спасибо. странно конечно но вчера ровно такой же скрипт не работал.
