### ISSUE TITLE
запрос результатов прохождение теста

### ISSUE THREAD

**Issue by xirurg2016** [hhru/api#212]
не нашел инструментов что бы запросить результаты прохождения теста соискателем ?
речь об этой оценке:
![image](https://cloud.githubusercontent.com/assets/19711218/21141158/c1e1eef4-c14c-11e6-9b73-7d6ef2d854de.png)

---

Если вам интересна данная возможность, подпишитесь на обновление этого тикета, чтобы получать уведомления о её появлении.

Также за тикет можно проголосовать 👍 .

**Comment by yyakhontov** [comment]
Добрый день. К сожалению, пока мы не поддерживаем выдачу результатов теста.
