### ISSUE TITLE
не описанная ошибка при обращении с типовым запросом

### ISSUE THREAD

**Issue by xirurg2016** [hhru/api#213]
Подскажите пожалуйста по ошибке.

При обращении из программы по адресу 
https://api.hh.ru/negotiations/response?vacancy_id=17791554&per_page=200

получаю ошибку не описанную в документации:
{"errors":[{"type":"bad_gateway"}],"description":"Bad Gateway"}

при этом  сразу же после этого по адресу
https://api.hh.ru/negotiations/response?vacancy_id=19182291&per_page=200
ответ возвращается нормально.

**Comment by xirurg2016** [comment]
та же проблема с 3 вакансиями с id 
17791554
18917358
19051874
при обращении к ним получаю 
{"errors":[{"type":"bad_gateway"}],"description":"Bad Gateway"}

Остальные 20 нормально обслуживаются сервисом. 
Есть ли возможность уточнить в чем проблема? в списке вакансий визуально они выглядят нормально, отличаются тем что их поднимали из архива и переименовывали несколько раз. 
Это глюк сервиса?

**Comment by maizy** [comment]
перед разбором ошибок в теле смотрите на код ответа. если код ответа 50x, это значит наш сервис по какой-то причине не смог обработать запрос, в таком случае вы можете повторять запрос. 

(это описано [тут](https://github.com/hhru/api/blob/master/docs/general.md#Ошибки-и-коды-ответов), но ничего дополнительного к тому, что я описал там нет.)

мы изучим подробности того, почему именно эти запросы не работали в вашем случае.
напишите, пожалуйста, на api@hh.ru примерное время этих запросов и пользователя от авторизации которого они выполнялись.

с откликами (первый тип запросов, описанных в тиките), рекомендуется взять per_page по меньше, скажем 50. мы планируем уменьшить допустимый per_page в этом и других местах в API.

**Comment by xirurg2016** [comment]
Благодарю за ответ, направил письмо

**Comment by xirurg2016** [comment]
уменьшение до 50 помогло. или вы что то сделали?

**Comment by maizy** [comment]
нет, со своей стороны мы пока ничего не меняли.
ваше письмо получили, изучим проблему и отпишемся о рез-тах.

**Comment by maizy** [comment]
в данный момент решение - уменьшать значение до 20-50 резюме на страницу. в данный момент api позволяет указать и более большие значения per_page, но такие запросы часто (но не всегда) будут возвращать 50x. мы планируем запретить указывать большие значения per_page в API в ближайшее время.
