### ISSUE TITLE
Различия в поиске вакансий по API и на hh.ru

### ISSUE THREAD

**Issue by alexeymarunin** [hhru/api#214]
Здравствуйте!

При поиске вакансий с помощью api [поиске вакансий с помощью api](https://github.com/hhru/api/blob/master/docs/vacancies.md#search) возвращается, среди прочего, также поле `alternate_url`. Если перейти по этой ссылке, то отображаются те же найденные вакансии с одним "но" - на hh.ru сверху будут премиум-вакансии (если я правильно понял). Можно ли как-то унифицировать это? Например, в api добавить поле `include_premium`, позволяющее получать также список премиум-вакансий.

**Comment by maizy** [comment]
Мы поддерживаем параметр поиска вакансий `premium=true`, который включит сортировку вакансий, как на сайте. 

Мы не стали его документировать, так как считали, что в API он мало полезен, но теперь добавим в документацию.
