### ISSUE TITLE
Заголовок User-Agent при AJAX-запросах (поддержка альтернативного заголовка для User-Agent)

### ISSUE THREAD

**Issue by alexeymarunin** [hhru/api#215]
Здравствуйте!

При использовании api [требуется передавать заголовок User-Agent](https://github.com/hhru/api/blob/master/docs/general.md). Но при ajax-запросах браузеры вырезают данный заголовок по соображениям безопасности (выдавая в консоли ошибку `Refused to set unsafe header "User-Agent"`)

Как можно идентифицировать свое приложение в этом случае?

---

Если вам интересна данная возможность, подпишитесь на обновление этого тикета, чтобы получать уведомления о её появлении.

Также за тикет можно проголосовать 👍 .

**Comment by maizy** [comment]
Да, действительно. Не смотря на то, что мы явно разрешает в preflight запросе использование заголовка User-Agent браузеры по соображениям безопасности его блокируют (они даже не делают preflight в таком случае).

```
$ curl -v 'https://api.hh.ru/vacancies?area=1&per_page=3' -X OPTIONS -H 'Access-Control-Request-Method: GET' -H 'Origin: https://example.com' -H 'Access-Control-Request-Headers: user-agent'

> OPTIONS /vacancies?area=1&per_page=3 HTTP/1.1
> Host: api.hh.ru
> User-Agent: curl/7.51.0
> Accept: */*
> Access-Control-Request-Method: GET
> Origin: https://example.com
> Access-Control-Request-Headers: user-agent
>
< HTTP/1.1 200 OK
< Server: nginx/1.8.1
< Date: Tue, 27 Dec 2016 15:06:14 GMT
< Content-Length: 0
< Connection: keep-alive
< Keep-Alive: timeout=60
< X-Request-Id: 1482851174195671b310bb78fdc382fd
< Access-Control-Allow-Headers: Origin, Authorization, X-Requested-With, DNT, Content-Type, User-Agent, If-None-Match
< Access-Control-Expose-Headers: Location, ETag, Date, Expires, Cache-Control, Content-Type, X-Request-ID
< Access-Control-Max-Age: 43200
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: HEAD, GET, POST
< X-Request-ID: 1482851174195671b310bb78fdc382fd
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
<
```

Чтобы обойти эту проблему мы введём какой-нибудь дополнительный заголовок, вроде `X-User-Agent`, если он передан, для идентификации приложения будет использовано его значение, а не значение переданное в User-Agent. Заголовок будет анонсироваться в preflight запросах в `Access-Control-Allow-Headers`.

Пример js кода, который после этого заработает: https://jsfiddle.net/maizy/w38bs8sg/2/


Текущий workaround: не передавать дополнительный заголовок. Мы поддерживаем браузерные user-agent подставляемые в запросах неявно и запросы будут работать, но идентифицировать ваше приложение мы не сможем. Идентификация приложения не повлияет на работу анонимных и авторизованных запросов.

**Comment by maizy** [comment]
Мы добавили поддержку альтернативного заголовка HH-User-Agent. Подробнее [тут](https://github.com/hhru/api/blob/master/docs/general.md#request-requirements).

Заголовок декларируется в числе разрешённых в cors запросах и его можно использовать в XHR запросах.

```
curl -v -X OPTIONS https://api.hh.ru/cors -H 'Origin: example.com' -H 'Access-Control-Request-Method: GET'
> OPTIONS /cors HTTP/1.1
> Host: api.hh.ru
> User-Agent: curl/7.51.0
> Accept: */*
> Origin: example.com
> Access-Control-Request-Method: GET
>
< HTTP/1.1 200 OK
< Server: nginx/1.11.10
< Date: Wed, 05 Apr 2017 07:30:47 GMT
< Content-Length: 0
< Connection: keep-alive
< Keep-Alive: timeout=60
< X-Request-Id: 1491377447734effc125289fc153e492
< Access-Control-Allow-Headers: Origin, Authorization, X-Requested-With, DNT, Content-Type, User-Agent, HH-User-Agent, If-None-Match
< Access-Control-Expose-Headers: Location, ETag, Date, Expires, Cache-Control, Content-Type, X-Request-ID
< Access-Control-Max-Age: 43200
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: HEAD, GET, POST, DELETE, PUT
< X-Request-ID: 1491377447734effc125289fc153e492
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
```
