### ISSUE TITLE
Неправильная выдача при запросе с date_from & date_to

### ISSUE THREAD

**Issue by shiziksama** [hhru/api#216]
https://api.hh.ru/vacancies?per_page=500&area=113&date_from=2016-12-29T14:40:08&date_to=2016-12-29T14:41:35

по такому запросу выдаются вакансии, в которых дата публикации больше, чем date_to.

**Comment by maizy** [comment]
время поиска округляется на нашей стороне с шагом в 5 минут. т.е. ваш диапазон 
`2016-12-29T14:40:08 - 2016-12-29T14:41:35` на самом деле стал
`2016-12-29T14:40:00 - 2016-12-29T14:45:00`.

к сожалению, в документации мы это не отразили. добавим.

также совет использовать `per_page` по-меньше, например `100`. при необходимости получить много значений, лучше делать несколько параллельных запросов с `?page=...&per_page=100`, чем один с `?per_page=500`.

мы планируем уменьшить максимально допустимый per_page в ближайшей перспективе.

**Comment by shiziksama** [comment]
спасибо за ответ.
