### ISSUE TITLE
Поиск резюме

### ISSUE THREAD

**Issue by s0i37** [hhru/api#226]
Здравствуйте. Подскажите можно ли искать резюме по названию компании?

**Comment by yyakhontov** [comment]
Добрый день.

К сожалению, на текущий момент, резюме нельзя искать никак.

**Comment by s0i37** [comment]
Большое спасибо за ответ. Значит будем тянуть через html)

**Comment by MrFirestart** [comment]
Добрый день!
Как на днный момент обстоит дело с поиском резюме. 
Не в рамках вакансии или одной кампании
