### ISSUE TITLE
Ошибка в описании возможных ошибок при публикации ваканасии

### ISSUE THREAD

**Issue by freylis** [hhru/api#227]
Если я пытаюсь опубликовать существующую вакансию - получаю статус 403 в ответ, хотя в документации - 409. Поправьте, пожалуйста
http://joxi.ru/823j4DLuJMVyjm
http://joxi.ru/52aQy3nS4BPwd2

**Comment by maizy** [comment]
спасибо. поправим.

**Comment by maizy** [comment]
поправили: https://github.com/hhru/api/blob/master/docs/errors.md#vacancies-create-n-edit
