### ISSUE TITLE
Слишком много специализаций в вакансии

### ISSUE THREAD

**Issue by freylis** [hhru/api#229]
При попытке публиковать/изменить вакансию, в которой больше шести специализаций возвращается 400ая ошибка `bad_json_data` для поля `specializations`

6 и менее специализаций: http://joxi.ru/82Q7MGecjKqxzr
7 и более: http://joxi.ru/Y2Lq4NeU9bVjKA

Правилами, которые приходят из `/vacancy_conditions` кол-во специализаций не ограничено: http://joxi.ru/xAeeExYfpLadEA

Поправьте пожалуйста документацию или поведение api

**Comment by yyakhontov** [comment]
Добрый день. Пожалуйста, перешлите запрос на саппорт ящик - api@hh.ru

**Comment by maizy** [comment]
по рез-там разбора поняли, что у нас ошибка в выдаче `/vacancy_conditions`.
исправим, отпишусь когда будут изменения или новая информация.

**Comment by maizy** [comment]
исправили выдачу `/vacancy_conditions` теперь так:

```
{
    //...
    "specializations": {
        "max_count": 6,
        "min_count": 1,
        "required": true
    },
    //...
```
