### ISSUE TITLE
API отдает только общедоступные вакансии

### ISSUE THREAD

**Issue by tpah3akt** [hhru/api#232]
В случае забора вакансий через платный аккаунт компании API возвращает только вакансии доступные всем. Если же соискатель указал, что резюме доступно "Компаниям, являющимся клиентами HeadHunter", то через API оно недоступно, что существенно сокращает выборку.

**Comment by maizy** [comment]
не очень понятен ваш вопрос. какое отношение имеет резюме к поиску вакансий? авторизацию какого пользователя вы имеете ввиду (соискатель или работодатель)?

для рабодателей доступен полный список своих вакасий (в том числе скрытые или анонимные), документация вот тут: https://github.com/hhru/api/blob/master/docs/employer_vacancies.md#active
возможно это то, что вам нужно.

**Comment by tpah3akt** [comment]
Уточнил -- действительно все работает, мои извинения и спасибо за скорый ответ.
Нашлась другая проблема, но о ней отдельный топик заведу.
