### ISSUE TITLE
Отсутствует site_lang в справочнике

### ISSUE THREAD

**Issue by DaurenAmanbayev** [hhru/api#233]
https://api.hh.ru/dictionaries

**Comment by maizy** [comment]
вероятнее всего, это у нас какая-то ошибка в документации.

то, что, могло бы быть site_lang - это [локали](https://github.com/hhru/api/blob/master/docs/locales.md), они выдаются в отдельном методе.

разберёмся, поправим, спасибо.

**Comment by DaurenAmanbayev** [comment]
Да, это ошибка в документации https://github.com/hhru/api/blob/master/docs/dictionaries.md
Вам нужно убрать site_lang. Остальные справочники имеются перепроверил

**Comment by maizy** [comment]
> Вам нужно убрать site_lang. Остальные справочники имеются перепроверил

возможно это потерянный в какой-то момент справочник. но судя по всему он не нужен в данный момент.

**Comment by DaurenAmanbayev** [comment]
Хорошо

**Comment by maizy** [comment]
разобрались в документации был описан несуществующий справочник, удалили его.
