### ISSUE TITLE
Параметр запроса updated_after для списка откликов

### ISSUE THREAD

**Issue by shlima** [hhru/api#241]
Здравсвтуйте, в этом пул-реквесте https://github.com/hhru/api/pull/198 обсуждался параметр *updated_after*, для получения новых откликов с указанной даты. Почему этот функционал, в дальнейшем, был аннулирован и имеет ли смысл мне его когда-либо ждать ?

**Comment by maizy** [comment]
в данный момент работы заморожены.

если будут какие-то обновления, я напишу в данном тиките.

**Comment by yyakhontov** [comment]
К сожалению, в ближайшее время не появится.
