### ISSUE TITLE
В ответе от API возвращается 2 одинаковые вакансии

### ISSUE THREAD

**Issue by peshrus** [hhru/api#242]
**Request**: [https://api.hh.ru/vacancies?employment=full&employment=part&employment=project&schedule=remote&specialization=1.10&specialization=1.110&specialization=1.203&specialization=1.221&specialization=1.270&specialization=1.272&specialization=1.274&specialization=1.277&specialization=1.295&specialization=1.3&specialization=1.395&specialization=1.474&specialization=1.475&specialization=1.50&specialization=1.536&specialization=1.82&specialization=1.9&order_by=salary_desc&per_page=500&page=1](https://api.hh.ru/vacancies?employment=full&employment=part&employment=project&schedule=remote&specialization=1.10&specialization=1.110&specialization=1.203&specialization=1.221&specialization=1.270&specialization=1.272&specialization=1.274&specialization=1.277&specialization=1.295&specialization=1.3&specialization=1.395&specialization=1.474&specialization=1.475&specialization=1.50&specialization=1.536&specialization=1.82&specialization=1.9&order_by=salary_desc&per_page=500&page=1)

**Response**: [response-json.txt](https://github.com/hhru/api/files/1004630/response-json.txt)

**Expected Result**: 1 вакансия с ID = 20540824

**Actual Result**: 2 вакансии с ID = 20540824

**Comment by maizy** [comment]
действительно в редких случаях такая проблема сейчас возникает во всех поисках.

разбираемся, о обновлениях буду писать в данный тикет.

**Comment by maizy** [comment]
немного забыл про это тикет. проблема должна была уже исчезнуть несколько недель назад.
если вы такое ещё заметите, пожалуйста, дайте знать.
