### ISSUE TITLE
Пустой ответ при получении активных вакансий работодателя

### ISSUE THREAD

**Issue by seregazhuk** [hhru/api#248]
**Request**: https://api.hh.ru/employers/1743768/vacancies/active
**Expected Result**: 2 активных вакансии, id 20540900 и id 20566903
**Actual Result**: пустой массив

**Comment by seregazhuk** [comment]
Разобрался, вакансии видны тому, кто их создавал.

**Comment by maizy** [comment]
вакансии видны всем менеджерам компании. по-умолчанию выводятся вакансии текущего менеджера. передав доп. параметр manager_id можно посмотреть и вакансии других менеджеров, если на это достаточно прав.
