### ISSUE TITLE
При запросе нескольких специализаций возвращаются не все вакансии

### ISSUE THREAD

**Issue by peshrus** [hhru/api#250]
**Request 1**: https://api.hh.ru/vacancies?schedule=remote&order_by=salary_desc&per_page=500&employment=full&employment=part&employment=project&specialization=1.10&specialization=1.110&specialization=1.203&specialization=1.221&specialization=1.270&specialization=1.272&specialization=1.274&specialization=1.277&specialization=1.295&specialization=1.3&specialization=1.395&specialization=1.474&specialization=1.475&specialization=1.50&specialization=1.536&specialization=1.82&specialization=1.9&page=0

**Request 2**:
https://api.hh.ru/vacancies?schedule=remote&order_by=salary_desc&per_page=500&employment=full&employment=part&employment=project&specialization=1.10&specialization=1.110&specialization=1.203&specialization=1.221&specialization=1.270&specialization=1.272&specialization=1.274&specialization=1.277&specialization=1.295&specialization=1.3&specialization=1.395&specialization=1.474&specialization=1.475&specialization=1.50&specialization=1.536&specialization=1.82&specialization=1.9&page=1

**Request 3**:
https://api.hh.ru/vacancies?schedule=remote&order_by=salary_desc&per_page=500&employment=full&employment=part&employment=project&specialization=1.10&specialization=1.110&specialization=1.203&specialization=1.221&specialization=1.270&specialization=1.272&specialization=1.274&specialization=1.277&specialization=1.295&specialization=1.3&specialization=1.395&specialization=1.474&specialization=1.475&specialization=1.50&specialization=1.536&specialization=1.82&specialization=1.9&page=2

**Request 4**:
https://api.hh.ru/vacancies?schedule=remote&order_by=salary_desc&per_page=500&employment=full&employment=part&employment=project&specialization=1.10&specialization=1.110&specialization=1.203&specialization=1.221&specialization=1.270&specialization=1.272&specialization=1.274&specialization=1.277&specialization=1.295&specialization=1.3&specialization=1.395&specialization=1.474&specialization=1.475&specialization=1.50&specialization=1.536&specialization=1.82&specialization=1.9&page=3

**Responses**: 
[response-1-json.txt](https://github.com/hhru/api/files/1096029/response-1-json.txt)
[response-2-json.txt](https://github.com/hhru/api/files/1096030/response-2-json.txt)
[response-3-json.txt](https://github.com/hhru/api/files/1096032/response-3-json.txt)
[response-4-json.txt](https://github.com/hhru/api/files/1096028/response-4-json.txt)

**Expected Result**: В одном из 4 запросов должна быть вакансия с ID = 21302051

**Actual Result**: Нет вакансии с ID = 21302051, хотя следующий запрос её возвращает: https://api.hh.ru/vacancies?schedule=remote&order_by=salary_desc&per_page=500&employment=full&employment=part&employment=project&specialization=1.475 (см. [response-5-json.txt](https://github.com/hhru/api/files/1096031/response-5-json.txt))

Всего я насчитал таких вакансий 263 (их нет в первых 4 запросах, но они возвращаются при запросе отдельных специализаций).

**Comment by maizy** [comment]
Ожидаемое вами поведение не является верным во всех случаях.

Когда в поиске вы указываете несколько специализаций будут найдены вакансии, где хотя бы одна из них встретиться (логика `OR`). 

Это значит что выдача по нескольким специализациям (`A`), по сравнению с выдачей по одной специализации (`B`), будет шире. Есть вариант, что какая-то вакансия была в выдаче `B`, но в выдаче `A` при сортировке опустилась ниже 2000-ной позиции и не видна (подробнее про это [в документации](https://github.com/hhru/api/blob/master/docs/vacancies.md#search-results)).

Получая 4 страницы по 500 вакансия вы получаете не все вакансии, а первые 2000. Далее в выдаче могут быть ещё элементы. Сколько их было можно оценить по полю `found` - общее кол-во результатов.

**Comment by peshrus** [comment]
Понял, спасибо. Про 2000 забыл, да.
