### ISSUE TITLE
в API возвращаются две станции шоссе Энтузиастов 

### ISSUE THREAD

**Issue by tsypa** [hhru/api#251]
Шоссе Энтузиастов и Шоссе энтузиастов
Энтузиасты (с заглавной буквы) должны быть только одни

**Comment by maizy** [comment]
это две разные станции метро - одна на МЦК, одна на Калининской ветке.

название неправильное - это исправим, спасибо.

**Comment by iriss22** [comment]
название исправили, спасибо
