### ISSUE TITLE
Некорректное описание api

### ISSUE THREAD

**Issue by JLoskin** [hhru/api#252]
date_from – дата, которая ограничивает снизу диапазон дат публикации вакансий.
Нельзя передавать вместе с параметром period.
Значение указывается в формате ISO 8601 - YYYY-MM-DD или с точность до секунды YYYY-MM-DDThh:mm:ss**±hhmm**.

date_to – дата, которая ограничивает сверху диапазон дат публикации вакансий.
Необходимо передавать только в паре с параметром date_from.
Нельзя передавать вместе с параметром period.
Значение указывается в формате ISO 8601 - YYYY-MM-DD или с точность до секунды YYYY-MM-DDThh:mm:ss**±hhmm**.

В реалии же:
Запрос:
https://api.hh.ru/vacancies?clusters=true&enable_snippets=true&specialization=1&text=Xenix&page=0&per_page=500&date_from=2017-06-05T14:14:03+0300&date_to=2017-06-20T14:14:03+0300&area=113
Ответ:
{"errors":[{"type":"bad_argument","value":"date_from"},{"type":"bad_argument","value":"date_to"}],"bad_arguments":[{"name":"date_from","description":"Bad Request"},{"name":"date_to","description":"Bad Request"}],"description":"Bad Request","bad_argument":"date_from"}

Без указания timezone - работает.

**Comment by JLoskin** [comment]
Без указания timezone - работает.

**Comment by maizy** [comment]
в вашем запросе `+` - это символ пробела. Плюс - это `%2b`.

вот так работает:
```
https://api.hh.ru/vacancies?clusters=true&enable_snippets=true&specialization=1&text=Xenix&page=0&per_page=500&date_from=2017-06-05T14:14:03%2b0300&date_to=2017-06-20T14:14:03%2b0300&area=113
```

**Comment by JLoskin** [comment]
Согласен, допустил ошибку.
