### ISSUE TITLE
Отказ на отклик без отправки уведомления на почту

### ISSUE THREAD

**Issue by highander** [hhru/api#257]
"Стянул" отклик через api. В нём есть коллекция возможных действий.
Интересует действие "discard_by_employer".

Чтобы отклонить отклик, нужно сделать запрос вида https://api.hh.ru/negotiations/discard_by_employer/<id отклика>

Если я в запросе передаю текст сообщения (параметр message), то отклик "отказывается" на hh и пользователь получает уведомление на почту с указанным текстом.

Мне же необходимо сделать отказ, но без отправки уведомления на почту соискателя.

1. Если я не передаю этот параметр вообще (а он ведь необязательный), то мне приходит в ответе 204 "No content" (успешный ответ), но при этом с откликом ничего не происходит.
1. Если я передаю параметр в виде message='', то получаю в ответ 403 с ошибкой empty_message

В итоге, можно ли через апи сделать отказ для отклика, но чтобы при этом на почту соискателя не шло уведомление?

**Comment by maizy** [comment]
правильный запрос в данном случае не указывать параметр message совсем.
т.е.
```
PUT /negotiations/discard_by_employer/{id}
```

если на запрос пришёл ответ 204, то отклик должен был переместить в коллекцию "отказ"и сообщение не уйдёт соискателю.

мы проверяли, это работает, возможно в вашем случае что-то ещё пошло не так. пришлите нам, пожалуйста, на api@hh.ru (видел там этот же вопрос от вас) заголовки и тело запроса/ответа на перемещение отклика, который не сработал или хотя бы идентификатор отклика и примерное время запроса.

**Comment by highander** [comment]
Отправил запросы на api@hh.ru если что.
