### ISSUE TITLE
Не могу изменить только некоторые поля из списка доступных для редактирования вакансии

### ISSUE THREAD

**Issue by Nick1994209** [hhru/api#258]
При редактировании вакансии

`url: 'https://api.hh.ru/vacancies/22510836'`
`method: PUT`

При передаче разных параметров, возвращаются разные релузльтаты:
params:
 ```
{} -> 
      Response.status_code=204; # успешное обновление.
```

 ```
  {'code': '306', 
  'area': {'id': '1'}, 
  'name': 'Специалист по контекстной рекламе', 
  'specializations': [{'id': '11.436'}], 
  'billing_type': {'id': 'standard'}, 
  'key_skills': [], 
  'description': 'Новое описание', 
  'site': {'id': 'hh'}} ->
      Response.status_code=403;
      Response.content={"errors":[{"type":"vacancies","value":"conflict_changes"}]}
      # billing_type нельзя передавать; ошибка описана в документации
```

 ```
 {'description': 'new_description'} -> 
      Response.status_code=404, 
      Response.content = {"errors":[{"type":"not_found"}]}
      # странная ошибка. Почему не найдено? вакансия с id=22510836 существует
```

_При изменении нескольких полей, или изменении одного выдается ошибка 404_

**Comment by maizy** [comment]
не все поля вакансии можно менять. некоторые поля можно менять только отдельным запросом, без передачи других полей (техническое ограничение, возможно, однажды станет можно и с другими совместно) подробнее здесь: https://github.com/hhru/api/blob/master/docs/employer_vacancies.md#edit

> # странная ошибка. Почему не найдено? вакансия с id=22510836 существует

вероятнее всего проблема в доступе к вакансии. 404 на изменение вакансии будет, если менеджер, который её изменяет, не имеет на это прав. если выглядет, что все данные правильные - пришлите, пожалуйста, подробности запроса (тело и заголовки) и ответа (тело и заголовки) на изменение вакансии на api@hh.ru, мы посмотрим со своей стороны, что не так.

**Comment by Nick1994209** [comment]
```
PUT /vacancies/22510836 HTTP/1.1
Host: api.hh.ru
Accept-Encoding: gzip, deflate
Connection: keep-alive
User-Agent: Python Client
Accept: */*
Authorization: Bearer (токен могу в личку скинуть, если нужно)
content-type: application/json
Content-Length: 365

{"specializations": [{"id": "11.436"}], "key_skills": [], "description": "\u041d\u043e\u0432\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435", "code": "306", "name": "\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442 \u043f\u043e \u043a\u043e\u043d\u0442\u0435\u043a\u0441\u0442\u043d\u043e\u0439 \u0440\u0435\u043a\u043b\u0430\u043c\u0435"}
```

`
{"specializations": [{"id": "11.436"}], "key_skills": [], "description": "Новое описание", "code": "306", "name": "Специалист по контекстной рекламе"}
`

У пользователя есть права на редактирование (через вебсайт могу редактировать, и через него же создавал вакансию с помочью api).

**Comment by maizy** [comment]
ответственный менеджер по данной вакансии входит в hh.ru с email `a.b***@r***.ru` ("пользователь А"), а запрос, который вы прислали выше от пользователя с email `r.c***@r***.ru` ("пользователь B"). пользователи A и B принадлежат к одной компании, но пользователь В, от имени которого сделан запрос, не имеет доступа к вакансиям пользователя A.

вероятно на сайте вы проверяли редактирование под другим пользователем.
проверить какому пользователю принадлежит токен, который вы использовали можно через запрос `GET /me`.

**Comment by Nick1994209** [comment]
Один человек, проверил.

**Comment by maizy** [comment]
Я попытался повторить вашу проблему, но мне пока это не удалось.

Отображается ли данная вакансия на сайте в списке "мои вакансии" под пользователем B (`r.c***@r***.ru`)?
https://hh.ru/employer/vacancies
Судя по моим данным, там должен быть пустой список.

Также, проверьте, отображаются ли [дополнительные поля по вакансии для автора](https://github.com/hhru/api/blob/master/docs/vacancies.md#Дополнительные-поля-вакансии-для-работодателей) с авторизацией пользователя B в api по `GET /vacancies/22510836`

В частности, совпадает ли в выдаче по вакансии поле `manager.id` с полем `manager.id` в `GET /me`? (В выдаче вакансии поля может не быть).

**Comment by Nick1994209** [comment]
Большое спасибо!
К сожалению вакансию перевели на другого менеджера. Из-за этого вся суматоха с невозможностью редактирования.
