### ISSUE TITLE
Отклики на вакансию

### ISSUE THREAD

**Issue by dyfilatov** [hhru/api#261]
В документации указано (https://github.com/hhru/api/blob/master/docs/employer_negotiations.md#negotiations-list), что поле viewed_by_opponent отвечает за то, был ли отклик просмотрел **соискателем**.
Хотя логичнее было бы добавить поле viewed, который отвечает за то, был ли отклик просмотрен **работодателем**.

В вакансии (https://github.com/hhru/api/blob/master/docs/employer_vacancies.md#active), на сколько я понимаю, поле unread_responses указывает именно на то, сколько откликов не было просмотрено. Как мне получить эти отклики? Поле has_updates в отклике отвечает ещё и за непрочитанные сообщения.

Добавьте, пожалуйста, поле viewed в ответ на список откликов для каждого отклика и дайте возможность фильтровать отклики по этому полю, а то бывают вакансии, на которых по 16 тысяч откликов! Получение всех откликов для самостоятельной фильтрации в таком случае занимает порядка часа.

**Comment by iriss22** [comment]
Логика работы сервиса такова, что мы считаем, что, если в отклике появилось новое сообщение, то он является не прочитанным. Эту логику мы менять не будем.
