### ISSUE TITLE
Возможность работодателю переместить и/или отфильтровать отклики с удалёнными резюме

### ISSUE THREAD

**Issue by maizy** [hhru/api#262]
Сейчас у работодателя в откликах, если резюме было удалено или скрыто соискаталем, отклик "замирает". С ним ничего нельзя сделать, ни удалить, ни переместить в другую коллекцию.

На сайте это не очень заметно, так как такие отклики просто исчезают из списка:

![image](https://user-images.githubusercontent.com/789623/30106657-db95649a-9304-11e7-96d6-537248804d51.png)

но в API остаются "надгробья" - отклики с пустым резюме (`"resume": null`), которые никуда нельзя деть.

Необходимо сделать возможность убирать такие отклики из выдачи списка откликов/приглашений и/или перемещать такие отклики.

---

Если вам интересна данная возможность, подпишитесь на обновление этого тикета, чтобы получать уведомления о её появлении.

Также за тикет можно проголосовать 👍 .

**Comment by maizy** [comment]
+2 от разных клиентов

**Comment by iriss22** [comment]
добрый день. В настоящий момент: никак.
