### ISSUE TITLE
Возможность фильтрации вакансий по ключевым навыкам аналогично имеющейся фильтрации резюме по ключевым навыкам

### ISSUE THREAD

**Issue by sergeyprokhorenko** [hhru/api#263]
Необходима возможность фильтрации вакансий по ключевым навыкам аналогично имеющейся фильтрации резюме по ключевым навыкам

----

Если вам интересна данная возможность, подпишитесь на обновление этого тикета, чтобы получать уведомления о её появлении.

Также за тикет можно проголосовать 👍 .

**Comment by chistyakov** [comment]
Не могу найти в документации поиск (фильтрацию) по резюме. @sergeyprokhorenko, он существует?

**Comment by iriss22** [comment]
добрый день, нет

**Comment by yyakhontov** [comment]
К сожалению, на текущий момент это не возможно.
