### ISSUE TITLE
Использовать нестандартные трехпозиционные чекбоксы с состояниями "Не важно" (по умолчанию), "Да", "Нет" при фильтрации резюме и вакансий по ключевым навыкам и иным критериям

### ISSUE THREAD

**Issue by sergeyprokhorenko** [hhru/api#264]
Использовать нестандартные трехпозиционные чекбоксы с состояниями "Не важно" (по умолчанию), "Да", "Нет" при фильтрации резюме и вакансий по ключевым навыкам и иным критериям
https://habrahabr.ru/post/55881/

**Comment by maizy** [comment]
вы имеете ввиду [поиск в API](https://github.com/hhru/api/blob/master/docs/vacancies.md#search) или на основном сайте?

**Comment by maizy** [comment]
судя по топику на Хабре, на который вы ссылаетесь вы имеете ввиду функциональность на основном сайте hh.ru. запрос таких возможностей рекомедуется направлять в https://hh.ru/feedback

на основе поиска в API такое _почти_ возможно сделать: 
* не важно – нет параметра в запросе
* да – параметр фильтрации по ключевым навыкам стоит
* нет – такое пока не возможно, так как нет возможности исключения вакансий по навыку.
