### ISSUE TITLE
В результатах поиска не показывать повторно вакансии/резюме, помеченные пользователем как подходящие/неподходящие

### ISSUE THREAD

**Issue by sergeyprokhorenko** [hhru/api#265]
В результатах поиска не показывать повторно вакансии/резюме, помеченные пользователем как подходящие или неподходящие. В мобильном интерфейсе пометки могут делаться свайпами вправо (подходит) и влево (не подходит), а в десктопном интерфейсе - кнопкой-переключателем ("Не определено", "Не подходит", "Подходит") на каждой вакансии/резюме

**Comment by maizy** [comment]
В поиске вакансий у соискателей есть возможность указать какие вакансии или вакансии какой компании они не хотят видеть в поиске: https://github.com/hhru/api/blob/master/docs/blacklisted.md

Этот вопрос касается API? Если нет более удачное место для такого предложения: https://hh.ru/feedback

**Comment by maizy** [comment]
закрою запрос. если я правильно понял – ваш вопрос касается сайта hh.
напишите, пожалуйста, если это не так.
