### ISSUE TITLE
Баг с действиями по отклику с резюме = null

### ISSUE THREAD

**Issue by dyfilatov** [hhru/api#267]
При попытке выполнить действие, например, перенос из папки "Неразобранные" в папку "Подумать", по отклику, у которого `resume=null` выдаёт `403` ошибку:
`"{\"errors\":[{\"type\":\"negotiations\",\"value\":\"resume_not_found\"}]}"`

Видимо соискатель резюме удалил , а отклик остался. И ничего сделать с ним теперь нельзя. :(

**Comment by maizy** [comment]
Мы знаем про эту проблему. issue уже есть: #262
