### ISSUE TITLE
Выдача уникального идентификатора владельца резюме

### ISSUE THREAD

**Issue by maizy** [hhru/api#268]
В выдаче по резюме добавить поль `owner.id`, которое будет выдавать уникальный идентификатор владельца резюме. У одного соискателя может быть несколько резюме, с помощью этого идентификатора можно будет "склевать" или связывать эти резюме.

---

Если вам интересна данная возможность, подпишитесь на обновление этого тикета, чтобы получать уведомления о её появлении.

Также за тикет можно проголосовать 👍 .

**Comment by emil-ufa** [comment]
@maizy я правильно понимаю, что это поле уже есть в дополнительных полях для работодателя?

**Comment by shurik2533** [comment]
это поле уже есть
