### ISSUE TITLE
Баг верстки &#x2028; на странице авторизации

### ISSUE THREAD

**Issue by gitspb** [hhru/api#270]
![image](https://user-images.githubusercontent.com/30869598/31170429-ad81b0fc-a904-11e7-96db-36d79d2f1292.png)
https://dev.hh.ru/admin
Usually these are invisible but it seems that in Chrome on Windows 10 they are not all invisible.

**Comment by maizy** [comment]
thanks, we will fix it soon.

**Comment by maizy** [comment]
fixed
