### ISSUE TITLE
Авторизация по токену 

### ISSUE THREAD

**Issue by rogozin** [hhru/api#272]
Ребята, мы для внутреннего сервиса забираем отклики по API через авторизацию по токену (не OAuth):

```
curl -k -H 'Authorization: Bearer TOKEN' -H 'User-Agent: api-test-agent' https://api.hh.ru/resumes/resume_id
```

Свежие токены всегда забирали с https://dev.hh.ru/admin

Сейчас на этой странице нет токенов, а лишь предложение подать заявку на регистрацию приложения. 

Подскажите, это баг/фича?  И где теперь брать токен?

**Comment by yyakhontov** [comment]
Добрый день. 

К сожалению, получение персонального токена более не возможно. Необходима регистрация приложения.

**Comment by rogozin** [comment]
ок, вы бы хотя бы предупредили как-то

**Comment by yyakhontov** [comment]
Персональные токены всегда явно были "временным" решением, и фактически нужно было делать рассылку на почти всех пользователей hh.ru для некоего предупреждения. 

Прошу прощения за неудобства, постараемся продумать процедуру оповещения.

**Comment by emil-ufa** [comment]
> Прошу прощения за неудобства, постараемся продумать процедуру оповещения.

Например, можно в личном кабинете dev.hh.ru/admin написать где-нибудь пометку типа:
_Внимание! С NN ...ября 2017 года для работы с API необходима регистрация приложения._

Чтобы такие как я не думали "ой, что же я сломал(-а)?" и не мучали тех.поддержку вопросами :)

**Comment by GnuriaN** [comment]
А что делать, если я не создаю приложения, но мне хотелось бы собирать информацию из вакансий по разным параметрам. Мне это нужно для себя. Через API раньше, это было сделать очень просто, а сейчас мне нужно "городить" отдельное приложение?

**Comment by iriss22** [comment]
Да, сейчас без регистрации приложения никак.
