### ISSUE TITLE
Поиск по вакансиям с пробелом возвращает некорректные результаты

### ISSUE THREAD

**Issue by gladorange** [hhru/api#278]
Судя по всему, возвращаются вакансии,в которых встречается любое из слов разделенных пробелом.
Например, запрос для "генетический консультант"
https://api.hh.ru/vacancies?text=%D0%B3%D0%B5%D0%BD%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9%20%D0%BA%D0%BE%D0%BD%D1%81%D1%83%D0%BB%D1%8C%D1%82%D0%B0%D0%BD%D1%82&search_field=name

Возвращает много "консультантов", но ни одного "генетического". 
В то же время, в ответе есть поле alternate_url, которые указывает на страничку с этиже результатами на сайте hh.ru.
И на сайте отображается всего две вакансии, если убрать фильтр по имени. 
"alternate_url":"https://hh.ru/search/vacancy?text=%D0%B3%D0%B5%D0%BD%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D0%BA%D0%BE%D0%BD%D1%81%D1%83%D0%BB%D1%8C%D1%82%D0%B0%D0%BD%D1%82&search_field=name&enable_snippets=true

**Comment by maizy** [comment]
здесь сочетание двух фактов.

1. в API включён "умный поиск" (https://hh.ru/newsearch). на сайте его можно включить в явном виде. после этого результат на сайте будет соответствовать результату в api

2. в умном поиске есть ошибка, из-за чего большинство запросов с двумя и более словами работают неправильно. это мы поправим в ближайшее время. напишем по исправлению.

**Comment by gladorange** [comment]
А можно как-нибудь выключить умный поиск в API?

**Comment by fib0n** [comment]
можно добавить сортировку по дате публикации`&order_by=publication_time` (или любую другую из справочника, кроме `relevance`), например, https://api.hh.ru/vacancies?text=%D0%B3%D0%B5%D0%BD%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9%20%D0%BA%D0%BE%D0%BD%D1%81%D1%83%D0%BB%D1%8C%D1%82%D0%B0%D0%BD%D1%82&search_field=name&order_by=publication_time

PS. ошибка проявляется для запросов из двух и более слов только в случае, когда по какому-то из слов вообще не нашлось результатов - такое слово просто выкидывается из запроса и поиск идет по оставшимся словам

**Comment by fib0n** [comment]
починили - теперь все ок, по первому запросу
