### ISSUE TITLE
При отправке POST запроса на создание резюме возвращают ошибку 

### ISSUE THREAD

**Issue by root-vlad** [hhru/api#284]
Сервер возвращает ошибку прав доступа 403:
`{
    "errors": [
        {
            "type": "forbidden"
        }
    ],
    "description": "Forbidden"
}`

Запрос создавался с заголовком 
Authorization:Bearer My_token

При этом удаление и просмотр резюме проходит без ошибок

**Comment by iriss22** [comment]
добрый день.
Подскажите, пожалуйста, вопрос еще актуален?
