### ISSUE TITLE
Нет явной связи между отраслью и работодателем

### ISSUE THREAD

**Issue by azraeldk** [hhru/api#285]
Запрос GET /employers/{employer_id} возвращает данные о компании со ссылкой на выдачу вакансий этой компании, но  не дает информации об отрасли компании,
а документация по запросу GET /industries не дает информацию о наличие какой-то связи между этим справочником и данными компаний.

**Comment by iriss22** [comment]
добавили отрасль в выдачу о компании https://github.com/hhru/api/blob/master/docs/employers.md#%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BE%D0%B4%D0%B0%D1%82%D0%B5%D0%BB%D1%8C--%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D1%8F
