### ISSUE TITLE
Помогите новичку

### ISSUE THREAD

**Issue by Rashid-S** [hhru/api#286]
Здравствуйте.
Есть потребность в Python написать код для обработки вакансий. Опыта работы с API нет. Помогите хоть как-то оттолкнутся - с чего то начать.
Я так понял можно приложение создавать, а можно просто имея токен запросы делать. Второго варианта достаточно.
Заранее благодарю.

**Comment by Rashid-S** [comment]
Простите, но все таки может кто поможет?

**Comment by Mithmi** [comment]
Ну, я могу попытаться, хотя я не эксперт в этом вопросе и с API hh не разобрался до конца. К API стоит относится как к обычной питоновской библиотеке, только вы её не импортируете, а получаете к ней доступ обращаясь к серверу. Таким образом почти все ваши интеракции с API происходят через запросы. И собственно это и описанно в API.

Например чтобы получить список вакансий вам нужно отправить GET запрос. Как это и записанно в документации - `GET /vacancies/` .

Также если читать всю документацию можно заметить, что для обращения к серверу с запросом требуется передать заголовок - `'User-Agent':'Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405'`. Чтобы сервер ответил на запрос. Исходя из этого например я получаю список вакансий таким образом:
Я использую библиотеку requests.

`r = requests.get("https://api.hh.ru/vacancies", headers={'User-Agent':'Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405'})`

На что получаю ответ от севрера в виде JSON. Зачем вам нужны токены я не очень понимаю, так как в API hh не нашел надобности в них, кроме для узконаправленных вещей связанных с пользователем и резюме, но все токен обёртки одинаковы в основной своей массе.

**Comment by iriss22** [comment]
Добрый день.
Если хотите делать соискательские запросы, то достаточно токена. Если работодательские - нужно создать приложение. Если анонимные никакие токены не нужны.
