### ISSUE TITLE
Разные published_at

### ISSUE THREAD

**Issue by BasedGod25** [hhru/api#290]
Есть вакансия https://hh.ru/vacancy/24052140 у которой дата публикации, если верить странице 11 января 2018, но по API возвращается "published_at": "2018-02-07T15:13:17+0300".

**Comment by iriss22** [comment]
спасибо за информацию, будем исправлять

**Comment by maksim-kiryanov** [comment]
@BasedGod25, привет. Спасибо за внимательность. Ошибка была на сайте, ее поправили.
Теперь даты публикации на сайте и в API идентичны.
