### ISSUE TITLE
Вопросы по API

### ISSUE THREAD

**Issue by repman** [hhru/api#292]
Здравствуйте,

Начали изучать ваш API, есть ряд вопросов:

1) Какие у вас лимиты на запросы к API? Хотим повесить на крон запрос на проверку новых откликов по нашим открытым вакансиям.

2) Если мы купим доступ к базе резюме, то есть ли в API функция для поиска этих резюме? Не смогли найти функцию поиска, но нашли функцию приглашения в найденном резюме.

3) Активируйте пожалуйста запрос на доступ # 252

**Comment by iriss22** [comment]
Добрый день!

1. Максимальное количество откликов на страницу скоро будет уменьшено до 50.
2. Такой функции в АПИ нет
3. Ваша заявка рассматривается

**Comment by repman** [comment]
Нашей заявке отказали, без объяснения причин. Я не понимаю - вы сделали такой крутой АПИ, но судя по ИД нашей заявки им никто не пользуется, кроме вас самих. Зачем этот АПИ, документация, гит и прочее?

Все современные ИТ компания стремятся быть открытыми, АПИ делают тоже открытыми. У вас мало того что нужно спросить разрешения, вы еще отказываете на адекватные заявки.

**Comment by iriss22** [comment]
@yyakhontov

**Comment by iriss22** [comment]
по вопросу подтверждения заявки напишите, пожалуйста, на api@hh.ru

**Comment by repman** [comment]
Уже писали туда три письма, тикет 3351 - без результатно.
