### ISSUE TITLE
Обрезка текста responsibility в snippet

### ISSUE THREAD

**Issue by edvbb** [hhru/api#293]
Добрый день!
При поиске вакансий в формате 
`https://api.hh.ru/vacancies?employer_id=(номер)`
столкнулся с тем, что текст требований обрезается. 
Например 
```
requests.get('https://api.hh.ru/vacancies?employer_id=1139714').json() 
'snippet': {'requirement': 'Грамотная речь, нацеленность на результат. Опытный пользователь ПК. Опыт работы в продажах/с холодными звонками/оператором call-центра будет вашим...',
    'responsibility': 'Совершение исходящих телефонных звонков. Работа с электронной почтой и онлайн-консультантом. Консультирование клиентов по услугам компании. Формирование отчетности по результатам...'},

```
Полное описание можно смотреть через
`https://api.hh.ru/vacancies/(номер)`
Но тогда пропадает возможность фильтра по работодателю. 
Теоретически я могу скачать все ID вакансий работодателя, а потом их запустить через цикл, но это не очень удобно.
Есть ли какое-то решение смотреть полное описание responsibility в snippet с поиском по id работодателя?

**Comment by iriss22** [comment]
добрый день.
такого решения нет
