### ISSUE TITLE
Привязка приложения API к аккаунтам HH

### ISSUE THREAD

**Issue by emil-ufa** [hhru/api#294]
Доброго времени суток!
**Ситуация:** в компании есть несколько аккаунтов HH нанимающих менеджеров.
Под 1м аккаунтом заведено приложение API, которое используется для просмотра резюме.

**Вопрос:** возможно ли использовать _одно_ приложение API для просмотра резюме через _2 или более_ аккаунтов нанимающих менеджеров?
Или для этих целей нужно заводить заявку на приложение API из под каждого аккаунта HH?

По документации не нашел/не понял: если там было - буду рад, если укажете на конкретное место.

**Comment by emil-ufa** [comment]
Я правильно понимаю, что для этого достаточно выполнить процедуру получения access_token и refresh_token под нужными аккаунтами нанимающих менеджеров?

**Comment by iriss22** [comment]
Добрый день. Да, достаточно одного приложения
