### ISSUE TITLE
Ошибка в заголовке User-Agent -  400 (Bad Request)

### ISSUE THREAD

**Issue by Teenie-weenie** [hhru/api#296]
Маленькое приложение на React, при заполнении поля надо отправлять запрос на сервер через AJAX (подключен axios), обращение идет на `onKeyUp`

```
handleKeywordsKeyUp(e) {
        axios({
            method: 'GET',
            url: 'https://api.hh.ru/?text='+e.target.value, 
            headers: { 
                'User-Agent': 'MyApp/1.0 (my-app-feedback@example.com)', 
                'HH-User-Agent': 'MyApp/1.0 (my-app-feedback@example.com)', 
                'Content-Type':'application/x-www-form-urlencoded'
            }
            })
          .then(function (response) {
             //this.setState({autosearchresponse: response.data})
            console.log(1);
          })
          .catch(function (error) {
            console.log(error);
          });
    }
```

Приложение запущено на локальном хосте http://localhost:3000/   
В консоли вываливаются ошибки
`GET https://api.hh.ru/vacancies?text=t 400 (Bad Request)`

[https://i.stack.imgur.com/yTs49.png](url)
[https://i.stack.imgur.com/nS8VK.png](url)

Прочитала инфу по ссылкам
[https://github.com/hhru/api/issues/215](url)
[https://github.com/hhru/api/blob/master/docs/general.md#request-requirements](url)

Вроде всё делаю как написано, не могу разобраться что не так?

**Comment by iriss22** [comment]
Добрый день. Вы указали плохой User-Agent: "MyApp/1.0 (my-app-feedback@example.com)", вы не указали корректное название вашего приложения и обратный адрес
