### ISSUE TITLE
Swagger-документация?

### ISSUE THREAD

**Issue by artembeloglazov** [hhru/api#308]
Есть ли уже актуальное swagger-описание методов и параметров? Или у вас описание api только на живом языке?

**Comment by iriss22** [comment]
добрый день. swagger-описания нет. Только то, что тут

**Comment by artembeloglazov** [comment]
@iriss22 планируется? Может быть что-то подобное(RAML, например)? Я просто в списке форков увидел swagger-ui и подумал, что вы над этим работаете)

**Comment by iriss22** [comment]
в ближайшее время не планируется
