### ISSUE TITLE
Предложения по улучшению

### ISSUE THREAD

**Issue by VBagmut** [hhru/api#313]
Не нашел на сайте раздел техподдержки или обратной связи (возможно где-то глубоко запрятан). Чем мне неудобно пользоваться - блок портфолио в резюме. Невозможно изменить порядок элементов. Непонятна логика списка - новые работы запихиваются в конец, хотя HR или тимлид почти наверняка смотрит первые несколько. При редактировании текста в элементе, после нажатия сохранить он не сохраняется и в резюме остается старый текст (кэш сбрасывал, помогает только удаление и добавление этого же пункта портфолио заново). В общем улучшите hh.ru для разработчиков, в частности front-end разработчиков Чтобы им было удобнее редактировать и обновлять резюме. К сожалению складывается такое ощущение что сайт особо не развивается в плане добавления новой функциональности и улучшения существующей. Надеюсь это не так, если у вас есть какие-то отчеты об обновлениях, как у VS Code например https://code.visualstudio.com/updates/v1_24, то дайте пожалуйста ссылку.

**Comment by iriss22** [comment]
Добрый день. 
По вопросам улучшения сайта нужно писать сюда: https://feedback.hh.ru/

**Comment by VBagmut** [comment]
@iriss22 спасибо!
