### ISSUE TITLE
bad_json_data for response_url

### ISSUE THREAD

**Issue by jabjab25** [hhru/api#314]
Hi, 

So i am making the following request to post (omitting a few headers). I am trying to post a job and also add in the response_url but i get the error below. I have tried to post as free and open, standard and open and get the same response when i post with standard and direct i get a different error saying {"errors":[{"type":"vacancies","value":"not_enough_purchased_services"}]} but when i check my hhru account i have standard credits available. Can anyone advise on what i can do or what im doing wrong please

{
   "billing_type" : {
      "id" : "standard"
   },
   "driving_license_type" : [
      {
         "id" : "A"
      },
      {
         "id" : "B"
      },
      {
         "id" : "C"
      }
   ],
   "key_skills" : [
      {
         "name" : "java"
      },
      {
         "name" : " software developer"
      },
      {
         "name" : " HR"
      },
      {
         "name" : " Construction"
      }
   ],
   "salary" : {
      "to" : 6511595,
      "from" : 4596420,
      "currency" : "RUR"
   },
   "type" : {
      "id" : "open"
   },
   "site" : {
      "id" : "hh"
   },
   "contacts" : {
      "name" : "Jay Cena",
      "phones" : [
         {
            "country" : "7",
            "city" : "929",
            "number" : "5581009"
         }
      ],
      "email" : "test@test.com"
   },
   "name" : "Замерщик межкомнатных дверей  отредактированный",
   "employment" : {
      "id" : "project"
   },
   "experience" : {
      "id" : "between3And6"
   },
   "code" : "Замерщик межкомнатны",
   "employer" : "123456",
   "description" : "<p>Обязанности: <br /> <br /> * Осуществление замеров дверных проемов (коробка, доборы, наличник) <br /> * Грамотное оформление бланка замера <br /> * Консультирование заказчика <br /> <br /> Требования: <br /> <br /> * Опыт аналогичной работы - от 2 лет <br /> * ПК - Уверенный пользователь <br /> * Желательные личностные качества: коммуникабельность, внимательность, ответственность <br /> * Наличие а/м <br /> <br /> Условия: <br /> <br /> * Разъездной характер работы (Зона ответственности - Восток Москвы, Московской области) <br /> * Компенсация расходов на бензин, амортизацию и мобильной связи. <br /> * Зарплата сдельная, 2 раза в месяц. <br /> * Оформление по ТК</p><img src=\"https://counter.adcourier.com/amViYWNvbi41NzMxOS4xMDUwN0BkZXYuYXBsaXRyYWsuY29t.gif\">",
   "area" : {
      "id" : "1163"
   },
   "schedule" : {
      "id" : "fullDay"
   },
   "specializations" : [
      {
         "id" : "15.730"
      },
      {
         "id" : "15.388"
      },
      {
         "id" : "15.96"
      },
      {
         "id" : "15.390"
      }
   ],
   "response_url" : "http://www.google.com"
}

{"errors":[{"type":"bad_json_data","value":"response_url"}]}

**Comment by adanilkina** [comment]
Hi, 
you are trying to publish vacancy with type which you haven't.

You add
"response_url" : "https://www.google.com/" and 
"type" : {
"id" : "direct"
}
(this is right combination of this fields) but  you can add them only if you have the type of vacancy for this addition, but you haven't this. 

What kind of vacancy you are trying to publish?
Why do you use "response_url" with type "direct"?

**Comment by jabjab25** [comment]
so type needs to be in this way ? "type" : {
"id" : "direct"
}

im trying to post a test advert for a job and noticed in the api docs that you can send a response_url. 

under what circumstances can we send response_url does the type have to be direct ?

**Comment by jabjab25** [comment]
{
   "contacts" : {
      "name" : "Jay Cena",
      "email" : "test@test.com",
      "phones" : [
         {
            "country" : "7",
            "number" : "5581009",
            "city" : "929"
         }
      ]
   },
   "specializations" : [
      {
         "id" : "15.730"
      },
      {
         "id" : "15.388"
      },
      {
         "id" : "15.96"
      },
      {
         "id" : "15.390"
      }
   ],
   "code" : "Замерщик межкомнатны",
   "experience" : {
      "id" : "between3And6"
   },
   "site" : {
      "id" : "hh"
   },
   "salary" : {
      "to" : 6511595,
      "from" : 4596420,
      "currency" : "RUR"
   },
   "area" : {
      "id" : "1163"
   },
   "key_skills" : [
      {
         "name" : "java"
      },
      {
         "name" : " software developer"
      },
      {
         "name" : " HR"
      },
      {
         "name" : " Construction"
      }
   ],
   "response_url" : "https://www.google.com",
   "name" : "Замерщик межкомнатных дверей  отредактированный",
   "billing_type" : {
      "id" : "standard"
   },
   "employment" : {
      "id" : "project"
   },
   "type" : {
      "id" : "direct"
   },
   "driving_license_type" : [
      {
         "id" : "A"
      },
      {
         "id" : "B"
      },
      {
         "id" : "C"
      }
   ],
   "schedule" : {
      "id" : "fullDay"
   },
   "employer" : "2767422",
   "description" : "<p>Обязанности: <br /> <br /> * Осуществление замеров дверных проемов (коробка, доборы, наличник) <br /> * Грамотное оформление бланка замера <br /> * Консультирование заказчика <br /> <br /> Требования: <br /> <br /> * Опыт аналогичной работы - от 2 лет <br /> * ПК - Уверенный пользователь <br /> * Желательные личностные качества: коммуникабельность, внимательность, ответственность <br /> * Наличие а/м <br /> <br /> Условия: <br /> <br /> * Разъездной характер работы (Зона ответственности - Восток Москвы, Московской области) <br /> * Компенсация расходов на бензин, амортизацию и мобильной связи. <br /> * Зарплата сдельная, 2 раза в месяц. <br /> * Оформление по ТК</p><img src=\"https://counter.adcourier.com/amViYWNvbi40MjUxNC4xMDUwN0BkZXYuYXBsaXRyYWsuY29t.gif\">"
}

I tried what was suggested but this didn't work gives the following error {"errors":[{"type":"vacancies","value":"not_enough_purchased_services"}]}. I have checked my hhru account and i have standard posting credits available so not sure why this is not working

**Comment by adanilkina** [comment]
Yes, right way to sent 
"response_url" : "https://www.google.com/"
"type" : {
"id" : "direct"
}
And you cant sent your response_url, of cause with right type "direct".
But if you want to post advert vacancy you need connect with your personal manager for purchasing *advert* vacancy.

**Comment by adanilkina** [comment]
Yes, this is right error, because you have to buy **advert** vacancy, not standard.
Contact with your personal manager for purchasing.

**Comment by jabjab25** [comment]
to confirm we would need to purchase vacancy advertisment like clickme? and not just have posting vacancy credit

**Comment by adanilkina** [comment]
I can consult only a technical problems.
I advice you to connect with your personal manager for details.

**Comment by jabjab25** [comment]
thanks i will do
