### ISSUE TITLE
Странности пагинации

### ISSUE THREAD

**Issue by galvanom** [hhru/api#321]
При значении параметра `per_page` отличным от 100 возвращаются дубликаты вакансий.
Пример запросов:
```
[16/07/18 11:57:02:002 MSK] DEBUG https://api.hh.ru/vacancies?text=Java&per_page=100&page=0
[16/07/18 11:57:22:022 MSK] DEBUG https://api.hh.ru/vacancies?text=Java&per_page=100&page=1
[16/07/18 11:57:43:043 MSK] DEBUG https://api.hh.ru/vacancies?text=Java&per_page=14&page=2
[16/07/18 11:57:46:046 MSK] Vacancies number: 214
```
В итоге из 214 вакансий 15 являются дубликатами.

Справа порядковые номера дубликатов в списке (100й совпадает с 99-м, 200 с 28-м и т.д. ):
```
Id duplicate: 26576112, 100, 99
Id duplicate: 26225378, 200, 28
Id duplicate: 26632499, 201, 29
Id duplicate: 26652082, 202, 30
Id duplicate: 26760515, 203, 31
Id duplicate: 26370085, 204, 32
Id duplicate: 26576511, 205, 33
Id duplicate: 26629912, 206, 34
Id duplicate: 26722356, 207, 35
Id duplicate: 26722357, 208, 36
Id duplicate: 26722358, 209, 37
Id duplicate: 24473142, 210, 38
Id duplicate: 26594148, 211, 39
Id duplicate: 26794896, 212, 40
Id duplicate: 26722014, 213, 41
```
Если запрашивать `per_page=100` дубликатов не возвращается.

**Comment by iriss22** [comment]
Добрый день. 
Если вы делаете приведенные запросы последовательно, то в последнем запросе вы получаете дубликаты, т.к. запрашиваете с 29 по 42 вакансии, а до этого уже запросили с 0 по 200.

**Comment by galvanom** [comment]
> [16/07/18 11:57:43:043 MSK] DEBUG https://api.hh.ru/vacancies?text=Java&per_page=14&page=2

> Если вы делаете приведенные запросы последовательно, то в последнем запросе вы получаете дубликаты, т.к. запрашиваете с 29 по 42 вакансии, а до этого уже запросили с 0 по 200.

Последний запрос должен возвращать с 200-го по 213-й, а возвращаются с 28-го по 41-й

**Comment by galvanom** [comment]
> Если вы делаете приведенные запросы последовательно, то в последнем запросе вы получаете дубликаты, т.к. запрашиваете с 29 по 42 вакансии, а до этого уже запросили с 0 по 200.
Да, моя ошибка. Не сразу понял, как это работает.
