### ISSUE TITLE
формат txt файла с резюме для импорта.

### ISSUE THREAD

**Issue by vtolstov** [hhru/api#324]
У меня есть резюме на https://github.com/vtolstov/cv хочу софрмировать txt файл так, чтобы автоматически он мог нормально импортироваться на hh.
Можно где-то увидеть спеку по формату текстового файла?

**Comment by iriss22** [comment]
добрый день. Такой спецификации нет. И через API нельзя загружать резюме из файла

**Comment by vtolstov** [comment]
Ну через сайт то можно загрузить, какой формат файла?

**Comment by iriss22** [comment]
Такой спецификации нет.
По вопросам, связанным с сайтом нужно писать сюда: https://feedback.hh.ru/
