### ISSUE TITLE
POST-запрос параметры при отклике на вакансию

### ISSUE THREAD

**Issue by Andrew-VI** [hhru/api#327]
Подскажите, пожалуйста, что не так. Когда я отправляю POST-запрос для отклика на вакансию ко мне возвращается код ошибки 400, не верно заданы параметры запроса. 
ОтветСайта
{"errors":[{"type":"bad_argument","value":"vacancy_id"},
{"type":"bad_argument","value":"resume_id"}],
"bad_arguments":[{"name":"vacancy_id","description":"Vacancy id must be set"},
{"name":"resume_id","description":"Resume id must be set"}],
"description":"Vacancy id must be set","bad_argument":"vacancy_id"}

ТелоPOSTЗапроса
{"vacancy_id":"27072606","resume_id":"738784d0ff0549b6f10039ed1f5a4731503056","message":"Добрый день! Хотел бы у Вас работать."}

**Comment by iriss22** [comment]
добрый день. Ответила на почту
