### ISSUE TITLE
Получение списка отраслей и компаний вместе

### ISSUE THREAD

**Issue by ghost** [hhru/api#336]
Я могу получить список отраслей при помощи `GET /industries`.
Могу получить список компаний при помощи `GET /employers`.
Но как мне получить список компаний по отрасли? Либо, можно просто добавить id отрасли к компанию

**Comment by gooverdian** [comment]
#285

**Comment by vadimdanilovit** [comment]
Когда можно ожидать решения проблемы?

**Comment by iriss22** [comment]
добавили отрасль в выдачу о компании https://github.com/hhru/api/blob/master/docs/employers.md#%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BE%D0%B4%D0%B0%D1%82%D0%B5%D0%BB%D1%8C--%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D1%8F
