### ISSUE TITLE
Ответ <Response [400]>

### ISSUE THREAD

**Issue by DaedricKnight** [hhru/api#338]
При парсинге данных с https://api.hh.ru/vacancies?skills?text=Python&text=Data analysis выдаётся ответ <Response [400]> с пустым списком. Парсинг осуществлялся с помощью следующих библиотек Python - urllib, requests.

**Comment by shurik2533** [comment]
скорее всего что-то не так с параметрами запроса. посмотрите, какой текст в теле ответа возвращается

**Comment by yyakhontov** [comment]
Пожалуйста, перешлите подробности на api@hh.ru
