### ISSUE TITLE
Пересмотр необходимости дефолтного redirect_uri для заявки на приложение 

### ISSUE THREAD

**Issue by colorbash** [hhru/api#340]
Многие юзеры на форме заявки на регистрацию приложения оставляют в redirect_uri что-то вроде ya.ru, localhost, google.com, потому что не понимают, что это такое и для чего нужен.
При это если redirect_uri действилельно нужен, его можно посылать каждый раз непосредственно при получении авторизации пользователя.  
И собственно вопрос.. а нужел ли redirect_uri у приложения, может пусть юзеры сами решают - нужен он им или нет.

плюсы :
1) меньше вопросов, понятнее форма заявки, удобство для пользователей
2) можно сделать как во вконтактике - если не подсунули redirect_uri при получении авторизации пользователя - отправлять на нашу страничку где будет предупреждение - "Юзер,  не копируй ничего из адресной строки без понимания что происходит" 
3) меньше заморочек с проверкой redirect_uri на валидность.

**Comment by SaltOfTheFlame** [comment]
Если используется oauth 2.0, то, при использовании стратегии authorization code уйти от redirect_url не выйдет

**Comment by colorbash** [comment]
@SaltOfTheFlame Возможно я не достаточно хорошо объяснил идею этого issue, речь шла о пересмотре необходимости дефолтного redirect_uri у приложения(который заполняется на форме заявки), а не об отказе от redirect_uri в целом. Если пользователь не предоставил redirect_uri query-параметром во время получения авторизации пользователя приложением, то его можно перенаправить на страницу в доменном пространстве hh.ru на которой будет предупреждение пользователю, чтобы он не копировал ничего из адресной строки если не знает что делает. Так например реализовано во ВК. Если же он послал redirect_uri query-параметром, то перенаправлять его по этому redirect_uri, как раелизовано сейчас.
