### ISSUE TITLE
В документации отсутствует JSON schema 

### ISSUE THREAD

**Issue by MaslovD** [hhru/api#354]
Для более удобной и надежной работы с сервисом было бы неплохо получить JSON schema.

**Comment by MaslovD** [comment]
Я собрал из ответа, но не факт что здесь включены все поля
`  1 {
  2   "definitions": {},
  3   "$schema": "http://json-schema.org/draft-07/schema#",
  4   "$id": "http://example.com/root.json",
  5   "type": "object",
  6   "title": "The Root Schema",
  7   "required": [
  8     "id",
  9     "premium",
 10     "billing_type",
 11     "relations",
 12     "name",
 13     "insider_interview",
 14     "response_letter_required",
 15     "area",
 16     "salary",
 17     "type",
 18     "address",
 19     "allow_messages",
 20     "site",
 21     "experience",
 22     "schedule",
 23     "employment",
 24     "department",
 25     "contacts",
 26     "description",
 27     "branded_description",
 28     "key_skills",
 29     "accept_handicapped",
 30     "accept_kids",
 31     "archived",
 32     "response_url",
 33     "specializations",
 34     "code",
 35     "hidden",
 36     "quick_responses_allowed",
 37     "driver_license_types",
 38     "accept_incomplete_resumes",
 39     "employer",
 40     "published_at",
 41     "created_at",
 42     "negotiations_url",
 43     "suitable_resumes_url",
 44     "apply_alternate_url",
 45     "has_test",
 46     "test",
 47     "alternate_url"
 48   ],
 49   "properties": {
 50     "id": {
 51       "$id": "#/properties/id",
 52       "type": "string",
 53       "title": "The Id Schema",
 54       "default": "",
 55       "examples": [
 56         "8168127"
 57       ],
 58       "pattern": "^(.*)$"
 59     },
 60     "premium": {
 61       "$id": "#/properties/premium",
 62       "type": "boolean",
 63       "title": "The Premium Schema",
 64       "default": false,
 65       "examples": [
 66         false
 67       ]
 68     },
 69     "billing_type": {
 70       "$id": "#/properties/billing_type",
 71       "type": "object",
 72       "title": "The Billing_type Schema",
 73       "required": [
 74         "id",
 75         "name"
 76       ],
 77       "properties": {
 78         "id": {
 79           "$id": "#/properties/billing_type/properties/id",
 80           "type": "string",
 81           "title": "The Id Schema",
 82           "default": "",
 83           "examples": [
 84             "standard"
 85           ],
 86           "pattern": "^(.*)$"
 87         },
 88         "name": {
 89           "$id": "#/properties/billing_type/properties/name",
 90           "type": "string",
 91           "title": "The Name Schema",
 92           "default": "",
 93           "examples": [
 94             "Стандарт"
 95           ],
 96           "pattern": "^(.*)$"
 97         }
 98       }
 99     },
100     "relations": {
101       "$id": "#/properties/relations",
102       "type": "array",
103       "title": "The Relations Schema"
104     },
105     "name": {
106       "$id": "#/properties/name",
107       "type": "string",
108       "title": "The Name Schema",
109       "default": "",
110       "examples": [
111         "Middle веб-разработчик / Full-stack"
112       ],
113       "pattern": "^(.*)$"
114     },
115     "insider_interview": {
116       "$id": "#/properties/insider_interview",
117       "type": "null",
118       "title": "The Insider_interview Schema",
119       "default": null,
120       "examples": [
121         null
122       ]
123     },
124     "response_letter_required": {
125       "$id": "#/properties/response_letter_required",
126       "type": "boolean",
127       "title": "The Response_letter_required Schema",
128       "default": false,
129       "examples": [
130         false
131       ]
132     },
133     "area": {
134       "$id": "#/properties/area",
135       "type": "object",
136       "title": "The Area Schema",
137       "required": [
138         "id",
139         "name",
140         "url"
141       ],
142       "properties": {
143         "id": {
144           "$id": "#/properties/area/properties/id",
145           "type": "string",
146           "title": "The Id Schema",
147           "default": "",
148           "examples": [
149             "92"
150           ],
151           "pattern": "^(.*)$"
152         },
153         "name": {
154           "$id": "#/properties/area/properties/name",
155           "type": "string",
156           "title": "The Name Schema",
157           "default": "",
158           "examples": [
159             "Тула"
160           ],
161           "pattern": "^(.*)$"
162         },
163         "url": {
164           "$id": "#/properties/area/properties/url",
165           "type": "string",
166           "title": "The Url Schema",
167           "default": "",
168           "examples": [
169             "https://api.hh.ru/areas/92"
170           ],
171           "pattern": "^(.*)$"
172         }
173       }
174     },
175     "salary": {
176       "$id": "#/properties/salary",
177       "type": "object",
178       "title": "The Salary Schema",
179       "required": [
180         "from",
181         "to",
182         "currency",
183         "gross"
184       ],
185       "properties": {
186         "from": {
187           "$id": "#/properties/salary/properties/from",
188           "type": "integer",
189           "title": "The From Schema",
190           "default": 0,
191           "examples": [
192             40000
193           ]
194         },
195         "to": {
196           "$id": "#/properties/salary/properties/to",
197           "type": "integer",
198           "title": "The To Schema",
199           "default": 0,
200           "examples": [
201             80000
202           ]
203         },
204         "currency": {
205           "$id": "#/properties/salary/properties/currency",
206           "type": "string",
207           "title": "The Currency Schema",
208           "default": "",
209           "examples": [
210             "RUR"
211           ],
212           "pattern": "^(.*)$"
213         },
214         "gross": {
215           "$id": "#/properties/salary/properties/gross",
216           "type": "boolean",
217           "title": "The Gross Schema",
218           "default": false,
219           "examples": [
220             true
221           ]
222         }
223       }
224     },
225     "type": {
226       "$id": "#/properties/type",
227       "type": "object",
228       "title": "The Type Schema",
229       "required": [
230         "id",
231         "name"
232       ],
233       "properties": {
234         "id": {
235           "$id": "#/properties/type/properties/id",
236           "type": "string",
237           "title": "The Id Schema",
238           "default": "",
239           "examples": [
240             "open"
241           ],
242           "pattern": "^(.*)$"
243         },
244         "name": {
245           "$id": "#/properties/type/properties/name",
246           "type": "string",
247           "title": "The Name Schema",
248           "default": "",
249           "examples": [
250             "Открытая"
251           ],
252           "pattern": "^(.*)$"
253         }
254       }
255     },
256     "address": {
257       "$id": "#/properties/address",
258       "type": "object",
259       "title": "The Address Schema",
260       "required": [
261         "city",
262         "street",
263         "building",
264         "description",
265         "lat",
266         "lng",
267         "raw",
268         "metro",
269         "metro_stations"
270       ],
271       "properties": {
272         "city": {
273           "$id": "#/properties/address/properties/city",
274           "type": "null",
275           "title": "The City Schema",
276           "default": null,
277           "examples": [
278             null
279           ]
280         },
281         "street": {
282           "$id": "#/properties/address/properties/street",
283           "type": "null",
284           "title": "The Street Schema",
285           "default": null,
286           "examples": [
287             null
288           ]
289         },
290         "building": {
291           "$id": "#/properties/address/properties/building",
292           "type": "null",
293           "title": "The Building Schema",
294           "default": null,
295           "examples": [
296             null
297           ]
298         },
299         "description": {
300           "$id": "#/properties/address/properties/description",
301           "type": "null",
302           "title": "The Description Schema",
303           "default": null,
304           "examples": [
305             null
306           ]
307         },
308         "lat": {
309           "$id": "#/properties/address/properties/lat",
310           "type": "integer",
311           "title": "The Lat Schema",
312           "default": 0,
313           "examples": [
314             0
315           ]
316         },
317         "lng": {
318           "$id": "#/properties/address/properties/lng",
319           "type": "integer",
320           "title": "The Lng Schema",
321           "default": 0,
322           "examples": [
323             0
324           ]
325         },
326         "raw": {
327           "$id": "#/properties/address/properties/raw",
328           "type": "string",
329           "title": "The Raw Schema",
330           "default": "",
331           "examples": [
332             "Тула, ул. Ф. Смирнова,28"
333           ],
334           "pattern": "^(.*)$"
335         },
336         "metro": {
337           "$id": "#/properties/address/properties/metro",
338           "type": "null",
339           "title": "The Metro Schema",
340           "default": null,
341           "examples": [
342             null
343           ]
344         },
345         "metro_stations": {
346           "$id": "#/properties/address/properties/metro_stations",
347           "type": "array",
348           "title": "The Metro_stations Schema"
349         }
350       }
351     },
352     "allow_messages": {
353       "$id": "#/properties/allow_messages",
354       "type": "boolean",
355       "title": "The Allow_messages Schema",
356       "default": false,
357       "examples": [
358         true
359       ]
360     },
361     "site": {
362       "$id": "#/properties/site",
363       "type": "object",
364       "title": "The Site Schema",
365       "required": [
366         "id",
367         "name"
368       ],
369       "properties": {
370         "id": {
371           "$id": "#/properties/site/properties/id",
372           "type": "string",
373           "title": "The Id Schema",
374           "default": "",
375           "examples": [
376             "hh"
377           ],
378           "pattern": "^(.*)$"
379         },
380         "name": {
381           "$id": "#/properties/site/properties/name",
382           "type": "string",
383           "title": "The Name Schema",
384           "default": "",
385           "examples": [
386             "hh.ru"
387           ],
388           "pattern": "^(.*)$"
389         }
390       }
391     },
392     "experience": {
393       "$id": "#/properties/experience",
394       "type": "object",
395       "title": "The Experience Schema",
396       "required": [
397         "id",
398         "name"
399       ],
400       "properties": {
401         "id": {
402           "$id": "#/properties/experience/properties/id",
403           "type": "string",
404           "title": "The Id Schema",
405           "default": "",
406           "examples": [
407             "between1And3"
408           ],
409           "pattern": "^(.*)$"
410         },
411         "name": {
412           "$id": "#/properties/experience/properties/name",
413           "type": "string",
414           "title": "The Name Schema",
415           "default": "",
416           "examples": [
417             "От 1 года до 3 лет"
418           ],
419           "pattern": "^(.*)$"
420         }
421       }
422     },
423     "schedule": {
424       "$id": "#/properties/schedule",
425       "type": "object",
426       "title": "The Schedule Schema",
427       "required": [
428         "id",
429         "name"
430       ],
431       "properties": {
432         "id": {
433           "$id": "#/properties/schedule/properties/id",
434           "type": "string",
435           "title": "The Id Schema",
436           "default": "",
437           "examples": [
438             "fullDay"
439           ],
440           "pattern": "^(.*)$"
441         },
442         "name": {
443           "$id": "#/properties/schedule/properties/name",
444           "type": "string",
445           "title": "The Name Schema",
446           "default": "",
447           "examples": [
448             "Полный день"
449           ],
450           "pattern": "^(.*)$"
451         }
452       }
453     },
454     "employment": {
455       "$id": "#/properties/employment",
456       "type": "object",
457       "title": "The Employment Schema",
458       "required": [
459         "id",
460         "name"
461       ],
462       "properties": {
463         "id": {
464           "$id": "#/properties/employment/properties/id",
465           "type": "string",
466           "title": "The Id Schema",
467           "default": "",
468           "examples": [
469             "full"
470           ],
471           "pattern": "^(.*)$"
472         },
473         "name": {
474           "$id": "#/properties/employment/properties/name",
475           "type": "string",
476           "title": "The Name Schema",
477           "default": "",
478           "examples": [
479             "Полная занятость"
480           ],
481           "pattern": "^(.*)$"
482         }
483       }
484     },
485     "department": {
486       "$id": "#/properties/department",
487       "type": "null",
488       "title": "The Department Schema",
489       "default": null,
490       "examples": [
491         null
492       ]
493     },
494     "contacts": {
495       "$id": "#/properties/contacts",
496       "type": "object",
497       "title": "The Contacts Schema",
498       "required": [
499         "name",
500         "email",
501         "phones"
502       ],
503       "properties": {
504         "name": {
505           "$id": "#/properties/contacts/properties/name",
506           "type": "string",
507           "title": "The Name Schema",
508           "default": "",
509           "examples": [
510             "Светлана Шурухнова"
511           ],
512           "pattern": "^(.*)$"
513         },
514         "email": {
515           "$id": "#/properties/contacts/properties/email",
516           "type": "string",
517           "title": "The Email Schema",
518           "default": "",
519           "examples": [
520             "hr@techart.ru"
521           ],
522           "pattern": "^(.*)$"
523         },
524         "phones": {
525           "$id": "#/properties/contacts/properties/phones",
526           "type": "array",
527           "title": "The Phones Schema",
528           "items": {
529             "$id": "#/properties/contacts/properties/phones/items",
530             "type": "object",
531             "title": "The Items Schema",
532             "required": [
533               "comment",
534               "city",
535               "number",
536               "country"
537             ],
538             "properties": {
539               "comment": {
540                 "$id": "#/properties/contacts/properties/phones/items/properties/comment",
541                 "type": "string",
542                 "title": "The Comment Schema",
543                 "default": "",
544                 "examples": [
545                   "доб. 153"
546                 ],
547                 "pattern": "^(.*)$"
548               },
549               "city": {
550                 "$id": "#/properties/contacts/properties/phones/items/properties/city",
551                 "type": "string",
552                 "title": "The City Schema",
553                 "default": "",
554                 "examples": [
555                   "4872"
556                 ],
557                 "pattern": "^(.*)$"
558               },
559               "number": {
560                 "$id": "#/properties/contacts/properties/phones/items/properties/number",
561                 "type": "string",
562                 "title": "The Number Schema",
563                 "default": "",
564                 "examples": [
565                   "250450"
566                 ],
567                 "pattern": "^(.*)$"
568               },
569               "country": {
570                 "$id": "#/properties/contacts/properties/phones/items/properties/country",
571                 "type": "string",
572                 "title": "The Country Schema",
573                 "default": "",
574                 "examples": [
575                   "7"
576                 ],
577                 "pattern": "^(.*)$"
578               }
579             }
580           }
581         }
582       }
583     },
584     "description": {
585       "$id": "#/properties/description",
586       "type": "string",
587       "title": "The Description Schema",
588       "default": "",
589       "examples": [
590         "<p><em>На рынке с 1999 года. В штате 170 сотрудников, из них 30 разработчиков. Делаем сайты любой сложности, интранет / экстранет-решения. В портфолио более 1000 проектов. Собcтвенная платформа TAO.CMS/CMF. Работаем с технологиями: PHP, MySQL, Git, Docker, JavaScript (ES6), Composer, npm, Webpack.</em></p> <p> </p> <p><strong>Почему у нас стоит работать:</strong></p> <ul> <li><strong>Мы входим в ТОП-100 лучших работодателей России и №1 в Туле по версии Headhunter!</strong></li> <li><strong>Лауреат в номинации «HR digital-решение года» (HR TECH AWARD 2018);</strong></li> <li>Мы оказываем качественные услуги, наши клиенты работают с нами долго и рекомендуют нас своим партнерам;</li> <li>Внутри компании принят демократичный стиль общения, нет барьеров между управляющей командой и другими сотрудниками, все открыты для диалога;</li> <li>Мы поощряем инициативных сотрудников;</li> <li>Карьерный и профессиональный рост - это реальность;</li> <li>Мы вкладываемся в обучение новичков и развитие опытных сотрудников. У нас есть собственные программы обучения. Наши сотрудники посещают все основные отраслевые конференции;</li> <li>Мы соблюдаем нормы ТК, оформляем официально с первого рабочего дня и своевременно выплачиваем зарплату;</li> <li>У нас комфортные рабочие места, на мини-кухнях всегда есть чай и кофе;</li> <li>У нас удобный график работы с 8-30 до 17-30, мы не стоим в пробках. У нас есть велопарковка;</li> <li>Мы регулярно проводим корпоративные мероприятия;</li> <li>Занимаемся активным туризмом, ходим в горы, пещеры, сплавляемся по рекам;</li> <li>Организуем для сотрудников групповые поездки в Европу;</li> <li>О нашем здоровье заботится корпоративный терапевт;</li> <li>Мы активно занимаемся спортом (вело, кроссфит);</li> <li>У нас есть курсы английского языка.</li> </ul> <p> </p> <p><strong>Требования:</strong></p> <ul> <li>PHP7;</li> <li>Знание принципов объектно-ориентированного программирования;</li> <li>Уверенное знание MySQL, HTML5, CSS, JavaScript, SQL;</li> <li>Опыт адаптивной верстки.</li> </ul> <p> </p> <p><strong>Будет плюсом:</strong></p> <ul> <li>Знакомство с Linux;</li> <li>Опыт работы с системами контроля версий;</li> <li>Базовые навыки настройки веб-серверов Apache. Nginx.</li> </ul> <p><br /><strong>Обязанности:</strong></p> <ul> <li>Разработка и поддержка веб-проектов;</li> <li>Создание и интеграция верстки;</li> <li>Разработка и поддержка компонентов и инструментов для внутреннего использования.</li> </ul>"
591       ],
592       "pattern": "^(.*)$"
593     },
594     "branded_description": {
595       "$id": "#/properties/branded_description",
596       "type": "null",
597       "title": "The Branded_description Schema",
598       "default": null,
599       "examples": [
600         null
601       ]
602     },
603     "key_skills": {
604       "$id": "#/properties/key_skills",
605       "type": "array",
606       "title": "The Key_skills Schema",
607       "items": {
608         "$id": "#/properties/key_skills/items",
609         "type": "object",
610         "title": "The Items Schema",
611         "required": [
612           "name"
613         ],
614         "properties": {
615           "name": {
616             "$id": "#/properties/key_skills/items/properties/name",
617             "type": "string",
618             "title": "The Name Schema",
619             "default": "",
620             "examples": [
621               "PHP7"
622             ],
623             "pattern": "^(.*)$"
624           }
625         }
626       }
627     },
628     "accept_handicapped": {
629       "$id": "#/properties/accept_handicapped",
630       "type": "boolean",
631       "title": "The Accept_handicapped Schema",
632       "default": false,
633       "examples": [
634         true
635       ]
636     },
637     "accept_kids": {
638       "$id": "#/properties/accept_kids",
639       "type": "boolean",
640       "title": "The Accept_kids Schema",
641       "default": false,
642       "examples": [
643         false
644       ]
645     },
646     "archived": {
647       "$id": "#/properties/archived",
648       "type": "boolean",
649       "title": "The Archived Schema",
650       "default": false,
651       "examples": [
652         false
653       ]
654     },
655     "response_url": {
656       "$id": "#/properties/response_url",
657       "type": "null",
658       "title": "The Response_url Schema",
659       "default": null,
660       "examples": [
661         null
662       ]
663     },
664     "specializations": {
665       "$id": "#/properties/specializations",
666       "type": "array",
667       "title": "The Specializations Schema",
668       "items": {
669         "$id": "#/properties/specializations/items",
670         "type": "object",
671         "title": "The Items Schema",
672         "required": [
673           "id",
674           "name",
675           "profarea_id",
676           "profarea_name"
677         ],
678         "properties": {
679           "id": {
680             "$id": "#/properties/specializations/items/properties/id",
681             "type": "string",
682             "title": "The Id Schema",
683             "default": "",
684             "examples": [
685               "1.221"
686             ],
687             "pattern": "^(.*)$"
688           },
689           "name": {
690             "$id": "#/properties/specializations/items/properties/name",
691             "type": "string",
692             "title": "The Name Schema",
693             "default": "",
694             "examples": [
695               "Программирование, Разработка"
696             ],
697             "pattern": "^(.*)$"
698           },
699           "profarea_id": {
700             "$id": "#/properties/specializations/items/properties/profarea_id",
701             "type": "string",
702             "title": "The Profarea_id Schema",
703             "default": "",
704             "examples": [
705               "1"
706             ],
707             "pattern": "^(.*)$"
708           },
709           "profarea_name": {
710             "$id": "#/properties/specializations/items/properties/profarea_name",
711             "type": "string",
712             "title": "The Profarea_name Schema",
713             "default": "",
714             "examples": [
715               "Информационные технологии, интернет, телеком"
716             ],
717             "pattern": "^(.*)$"
718           }
719         }
720       }
721     },
722     "code": {
723       "$id": "#/properties/code",
724       "type": "null",
725       "title": "The Code Schema",
726       "default": null,
727       "examples": [
728         null
729       ]
730     },
731     "hidden": {
732       "$id": "#/properties/hidden",
733       "type": "boolean",
734       "title": "The Hidden Schema",
735       "default": false,
736       "examples": [
737         false
738       ]
739     },
740     "quick_responses_allowed": {
741       "$id": "#/properties/quick_responses_allowed",
742       "type": "boolean",
743       "title": "The Quick_responses_allowed Schema",
744       "default": false,
745       "examples": [
746         false
747       ]
748     },
749     "driver_license_types": {
750       "$id": "#/properties/driver_license_types",
751       "type": "array",
752       "title": "The Driver_license_types Schema"
753     },
754     "accept_incomplete_resumes": {
755       "$id": "#/properties/accept_incomplete_resumes",
756       "type": "boolean",
757       "title": "The Accept_incomplete_resumes Schema",
758       "default": false,
759       "examples": [
760         false
761       ]
762     },
763     "employer": {
764       "$id": "#/properties/employer",
765       "type": "object",
766       "title": "The Employer Schema",
767       "required": [
768         "id",
769         "name",
770         "url",
771         "alternate_url",
772         "logo_urls",
773         "vacancies_url",
774         "trusted"
775       ],
776       "properties": {
777         "id": {
778           "$id": "#/properties/employer/properties/id",
779           "type": "string",
780           "title": "The Id Schema",
781           "default": "",
782           "examples": [
783             "71287"
784           ],
785           "pattern": "^(.*)$"
786         },
787         "name": {
788           "$id": "#/properties/employer/properties/name",
789           "type": "string",
790           "title": "The Name Schema",
791           "default": "",
792           "examples": [
793             "Текарт, консалтинговая группа"
794           ],
795           "pattern": "^(.*)$"
796         },
797         "url": {
798           "$id": "#/properties/employer/properties/url",
799           "type": "string",
800           "title": "The Url Schema",
801           "default": "",
802           "examples": [
803             "https://api.hh.ru/employers/71287"
804           ],
805           "pattern": "^(.*)$"
806         },
807         "alternate_url": {
808           "$id": "#/properties/employer/properties/alternate_url",
809           "type": "string",
810           "title": "The Alternate_url Schema",
811           "default": "",
812           "examples": [
813             "https://hh.ru/employer/71287"
814           ],
815           "pattern": "^(.*)$"
816         },
817         "logo_urls": {
818           "$id": "#/properties/employer/properties/logo_urls",
819           "type": "object",
820           "title": "The Logo_urls Schema",
821           "required": [
822             "90",
823             "240",
824             "original"
825           ],
826           "properties": {
827             "90": {
828               "$id": "#/properties/employer/properties/logo_urls/properties/90",
829               "type": "string",
830               "title": "The 90 Schema",
831               "default": "",
832               "examples": [
833                 "https://hhcdn.ru/employer-logo/2809423.jpeg"
834               ],
835               "pattern": "^(.*)$"
836             },
837             "240": {
838               "$id": "#/properties/employer/properties/logo_urls/properties/240",
839               "type": "string",
840               "title": "The 240 Schema",
841               "default": "",
842               "examples": [
843                 "https://hhcdn.ru/employer-logo/2809424.jpeg"
844               ],
845               "pattern": "^(.*)$"
846             },
847             "original": {
848               "$id": "#/properties/employer/properties/logo_urls/properties/original",
849               "type": "string",
850               "title": "The Original Schema",
851               "default": "",
852               "examples": [
853                 "https://hhcdn.ru/employer-logo-original/592042.jpg"
854               ],
855               "pattern": "^(.*)$"
856             }
857           }
858         },
859         "vacancies_url": {
860           "$id": "#/properties/employer/properties/vacancies_url",
861           "type": "string",
862           "title": "The Vacancies_url Schema",
863           "default": "",
864           "examples": [
865             "https://api.hh.ru/vacancies?employer_id=71287"
866           ],
867           "pattern": "^(.*)$"
868         },
869         "trusted": {
870           "$id": "#/properties/employer/properties/trusted",
871           "type": "boolean",
872           "title": "The Trusted Schema",
873           "default": false,
874           "examples": [
875             true
876           ]
877         }
878       }
879     },
880     "published_at": {
881       "$id": "#/properties/published_at",
882       "type": "string",
883       "title": "The Published_at Schema",
884       "default": "",
885       "examples": [
886         "2018-12-26T11:24:30+0300"
887       ],
888       "pattern": "^(.*)$"
889     },
890     "created_at": {
891       "$id": "#/properties/created_at",
892       "type": "string",
893       "title": "The Created_at Schema",
894       "default": "",
895       "examples": [
896         "2018-12-26T11:24:30+0300"
897       ],
898       "pattern": "^(.*)$"
899     },
900     "negotiations_url": {
901       "$id": "#/properties/negotiations_url",
902       "type": "null",
903       "title": "The Negotiations_url Schema",
904       "default": null,
905       "examples": [
906         null
907       ]
908     },
909     "suitable_resumes_url": {
910       "$id": "#/properties/suitable_resumes_url",
911       "type": "null",
912       "title": "The Suitable_resumes_url Schema",
913       "default": null,
914       "examples": [
915         null
916       ]
917     },
918     "apply_alternate_url": {
919       "$id": "#/properties/apply_alternate_url",
920       "type": "string",
921       "title": "The Apply_alternate_url Schema",
922       "default": "",
923       "examples": [
924         "https://hh.ru/applicant/vacancy_response?vacancyId=8168127"
925       ],
926       "pattern": "^(.*)$"
927     },
928     "has_test": {
929       "$id": "#/properties/has_test",
930       "type": "boolean",
931       "title": "The Has_test Schema",
932       "default": false,
933       "examples": [
934         false
935       ]
936     },
937     "test": {
938       "$id": "#/properties/test",
939       "type": "null",
940       "title": "The Test Schema",
941       "default": null,
942       "examples": [
943         null
944       ]
945     },
946     "alternate_url": {
947       "$id": "#/properties/alternate_url",
948       "type": "string",
949       "title": "The Alternate_url Schema",
950       "default": "",
951       "examples": [
952         "https://hh.ru/vacancy/8168127"
953       ],
954       "pattern": "^(.*)$"
955     }
956   }
957 }`

**Comment by iriss22** [comment]
Да, мы думали об этом, не уверена, что сделаем в ближайшее время
