### ISSUE TITLE
В описании метода GET /vacancies/{vacancy_id} присутствуют не все поля

### ISSUE THREAD

**Issue by MaslovD** [hhru/api#355]
Фактически, в ответе приходит больше полей, чем указано в примере. Например, нет полей: created_at, hidden, response_letter_required, response_url, site, suitable_resumes_url

**Comment by iriss22** [comment]
Спасибо за замечание. Поправим

**Comment by iriss22** [comment]
Добавила поля, которых не хватало. Поле site устаревшее (оставлено для обратной совместимости), его описывать в доке не буду
