### ISSUE TITLE
Метод GET /vacancies/{vacancy_id} не содержит поле industry 

### ISSUE THREAD

**Issue by MaslovD** [hhru/api#356]
метод GET employers/{employer_id} также не содержит industry

**Comment by iriss22** [comment]
да, не содержит и в ответе и в документации. В чем вопрос?

**Comment by xxx44yyy** [comment]
> да, не содержит и в ответе и в документации. В чем вопрос?

Ну вопрос в том, что видимо хотелось бы получать.

**Comment by iriss22** [comment]
добавили отрасль в выдачу о компании https://github.com/hhru/api/blob/master/docs/employers.md#%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BE%D0%B4%D0%B0%D1%82%D0%B5%D0%BB%D1%8C--%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D1%8F

**Comment by xxx44yyy** [comment]
А вы очень быстрые :)
