### ISSUE TITLE
Описание параметра no_magic

### ISSUE THREAD

**Issue by fkhodkov** [hhru/api#362]
Здравствуйте,
в описании параметра `no_magic` в файле [vacancies.md](https://github.com/hhru/api/blob/master/docs/vacancies.md) утверждается:

> `no_magic` – Если значение `false` – отключить автоматическое преобразование вакансий. По-умолчанию – `true`. При включённом автоматическом преобразовании, будет предпринята попытка изменить текстовый запрос пользователя на набор параметров. Например, запрос `text=москва бухгалтер 100500` будет преобразован в `text=бухгалтер&only_with_salary=true&area=1&salary=100500`.

Однако и по логике, и по тому, как этот параметр реально работает (https://api.hh.ru/vacancies?text=%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%20%D0%B1%D1%83%D1%85%D0%B3%D0%B0%D0%BB%D1%82%D0%B5%D1%80%20100500&no_magic=true против https://api.hh.ru/vacancies?text=%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%20%D0%B1%D1%83%D1%85%D0%B3%D0%B0%D0%BB%D1%82%D0%B5%D1%80%20100500&no_magic=false), `true` и `false` должны иметь прямо противоположный смысл.

**Comment by mxv2** [comment]
Да, вы правы. Спасибо за внимательность!
Поправили.
