### ISSUE TITLE
Можно ли использовать в коммерческих целях?

### ISSUE THREAD

**Issue by xxx44yyy** [hhru/api#368]

**Comment by mxv2** [comment]
Добрый день.

Можете описать подробнее, что вы хотите делать?

Также напомню вам о правилах использования API, с которыми вы можете ознакомиться на странице https://dev.hh.ru/admin/developer_agreement.

**Comment by xxx44yyy** [comment]
> Добрый день.
> 
> Можете описать подробнее, что вы хотите делать?
> 
> Также напомню вам о правилах использования API, с которыми вы можете ознакомиться на странице https://dev.hh.ru/admin/developer_agreement.

Ну вот я собираю у вас информацию следующих типов:
а) компания (только название + идентификатор)
б) названия вакансий этой компании
в) профобласть вакансии
г) зарплата вакансии
д) город вакансии
е) регион вакансии
ё) опыт работы вакансии
ж) тип занятости вакансии

Собрал и теперь два варианта:
а) ко мне пришла компания и говорит: продай за 100 рублей что там насобирал сегодня и вчера по компании АБВ.
б) я решил показать у себя на сайте вакансии компании АБВ и рядом поставил рекламный банер.

Вопрос: что из этих схем нарушает ваши правила, если нарушает?

**Comment by mxv2** [comment]
Напишите, пожалуйста, на api@hh.ru - там вас проконсультируют.

**Comment by xxx44yyy** [comment]
> Напишите, пожалуйста, на [api@hh.ru](mailto:api@hh.ru) - там вас проконсультируют.

Я туда писал полгода назад дважды - ответа не было. Поэтому уже сюда написал.

**Comment by xxx44yyy** [comment]
отправил только что
