### ISSUE TITLE
Молчание поддержки

### ISSUE THREAD

**Issue by xxx44yyy** [hhru/api#370]
Написал на api@hh.ru по тикету https://github.com/hhru/api/issues/368

Никто так и не ответил. Зарегистрировали запрос, затем пришло письмо:

> Ю#и# Я#о#т#в (HeadHunter API)
> 15 мар., 15:26 MSK
> 
> Добрый день.
> 
> Сейчас уточняем информацию и обязательно ответим Вам в ближайшее время.
> Ю#и# Я#о#т#в
> Руководитель проектов

Прошла неделя, но так никто и не ответил.

**Comment by iriss22** [comment]
разобрались в почте
