### ISSUE TITLE
Пример из документации не работает

### ISSUE THREAD

**Issue by Karganak** [hhru/api#372]
Put на обновление языков из 
https://github.com/hhru/api/blob/master/docs/resumes.md#create_edit 
возвращает 
```
{
    "description": "Bad Request",
    "bad_argument": "language",
    "bad_arguments": [
        {
            "name": "language",
            "description": "Bad Request"
        }
    ],
    "errors": [
        {
            "value": "language",
            "type": "bad_json_data"
        }
    ]
}
```

Все put, где в json есть массив, у меня не проходят.

**Comment by iriss22** [comment]
добрый день.
Напишите, пожалуйста, подробнее по адресу api@hh.ru, какой запрос вы вызываете и что передаете
