### ISSUE TITLE
Получение токенов пользователя работает через m.hh.ru, не работает через hh.ru или api.hh.ru

### ISSUE THREAD

**Issue by Karganak** [hhru/api#373]
Один и тот же пост корректно выполняется на https://m.hh.ru/oauth/token , но возвращает 404 через https://hh.ru/oauth/token . По документации, https://hh.ru/oauth/token должен работать.

**Comment by iriss22** [comment]
Добрый день. Напишите, пожалуйста, более подробно о вашей проблеме в по адресу: api@hh.ru
Мы обязательно вам поможем разобраться.
