### ISSUE TITLE
Дубли названий регионов

### ISSUE THREAD

**Issue by Jeider** [hhru/api#375]
Здравствуйте, обнаружил дубли следующих населенных пунктов в России:

Пушкинские Горы
Красные Баррикады
Шабровский

Например, Пушкинские Горы продублированы  в рамках одной Псковской области (parent_id тоже одинаковый):

```
{
    "id": "4032",
    "parent_id": "1090",
    "name": "Пушкинские Горы",
    "areas": [ ]
},
{
    "id": "3728",
    "parent_id": "1090",
    "name": "Пушкинские Горы",
    "areas": [ ]
},
```

Поэтому  если зайти на сайт hh.ru в форму регистрации и поискать эти Пушкинские Горы, то появится 2 результата и оба будут в Псковской области.

**Comment by shurik2533** [comment]
Здравствуйте! Спасибо за обращение. Нам известно о проблеме. Точных сроков исправления пока назвать не можем
