### ISSUE TITLE
Поле contact при публикации вакансии

### ISSUE THREAD

**Issue by lushkovsky-s** [hhru/api#379]
Посылаю вакансию с информацией о контактах: 
```
...
"contact": [
        { 
            "type": {"id": "email"},
            "value": "s.lushkovsky@gmail.com",
            "preferred": true
        }
]
...
```

Получаю 400: 
```
{
"description":"Bad Request",
"bad_argument":"contact",
"bad_arguments":[{"name":"contact","description":"Bad Request"}],
"errors":[{"value":"contact","type":"bad_json_data"}]}
```

Аналогично с вариантами:
```
"contact": [
        { 
            "type": "email",
            "value": "s.lushkovsky@gmail.com",
            "preferred": true
        }
    ]
```
```
"contact": [
        { 
            "type": {"id": "email"},
            "value": "s.lushkovsky@gmail.com"
        }
    ]
```
Так-же пробовал указывать телефон вместо email и указывать comment - не помогло

При убирании поля contact вакансия успешно создается

**Comment by lushkovsky-s** [comment]
Решил после прочтения
https://github.com/hhru/api/blob/master/docs/resumes.md#%D1%83%D1%81%D0%BB%D0%BE%D0%B2%D0%B8%D1%8F-%D0%B7%D0%B0%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D0%BE%D0%B2-%D0%B2-%D1%80%D0%B5%D0%B7%D1%8E%D0%BC%D0%B5

Думаю лучше добавить ссылку на этот раздел в описание поля contact здесь https://github.com/hhru/api/blob/master/docs/resumes.md#create_edit

**Comment by adanilkina** [comment]
Добрый день, очевидно, вы все-таки публикуете резюме, а не вакансию, т.к. при публикации вакансии поле называется `contacts` и не содержит `value`
https://github.com/hhru/api/blob/master/docs/employer_vacancies.md#creation

Что касается публикации резюме, поле телефон является обязательным при заполнении контактов резюме, соответственно, при попытке создания резюме без телефона, возникает ошибка, ссылку на условия заполнения контактов, добавим.
