### ISSUE TITLE
Оптимизация запросов и рекомендации

### ISSUE THREAD

**Issue by diyelise** [hhru/api#389]
Добрый день!

Использую данные hh.ru для построения некой статистики в рамках исследования определенной области.

Например, мне удалось получить все специализации
[api.hh.ru/specializations](url) и все города России

Придерживаясь рекомендаций вашего сервиса (не более 30 req/sec/ip) я пытаюсь асинхронно спарсить данные за последний день в таком формате:
https://api.hh.ru/vacancies?&period=1&page=0&per_page=100&text={}&area={}

Т.к возможных вариантов (~600 специальностей * ~3800 городов) ~ 2 млн запросов (без учета перехода по вложенным страницам)

Подскажите, может как-то улучшить запрос, чтобы он работал быстрее?

**Comment by shurik2533** [comment]
id вакансий идут по порядку. как вариант, вы можете запоминать id последней скачанной, а на следующий день инкрементить id о тех пор, пока вакансии не перестанут появляться. но из-за того, что некоторые вакансии закрывают, надо учесть, что несколько вакансий могут быть пропущены

**Comment by diyelise** [comment]
> 
> 
> id вакансий идут по порядку. как вариант, вы можете запоминать id последней скачанной, а на следующий день инкрементить id о тех пор, пока вакансии не перестанут появляться. но из-за того, что некоторые вакансии закрывают, надо учесть, что несколько вакансий могут быть пропущены

Мне кажется этот подход не совсем подходит мне, т.к в этом случае могут потеряться достаточно большое кол-во данных.

Может есть возможность узнать перед запуском парсера в каких городах каких вакансий нет?

**Comment by shurik2533** [comment]
В описанном подходе не должны теряться вакансии. Вы же перебираете абсолютно все новые вакансии.

Про наличие вакансий в городе можно узнать только сделав запрос на поиск вакансий
