### ISSUE TITLE
Возвращать id вакансии при ошибке duplicate

### ISSUE THREAD

**Issue by Melodyn** [hhru/api#392]
Сейчас при создании вакансии через api мы передаём флаг ignore_duplicates, при этом иногда происходит ситуация, что вакансия не создаётся, возвращая `duplicate`, а в интерфейсе "Мои вакансии" дубликаты не наблюдаются. Воспроизвести условия для вылова бага не удаётся и ошибка не поддаётся анализу.

Добавьте в ответ идентификатор вакансии, чтобы можно было понять какая именно вакансия была ранее опубликована.

**Comment by shurik2533** [comment]
Спасибо за обращение. Добавил в список хотелок. Данная ошибка выдается если совпадают поля name и area
