### ISSUE TITLE
the program on the phone does not update the resume date

### ISSUE THREAD

**Issue by rabotalya** [hhru/api#393]
1. Open the program on iOS.
2. Go to the resume section.
3. Click on the button «update resume date».
4. We see window with error. 
![206C7CF8-920C-447E-BC29-176B449AB62E](https://user-images.githubusercontent.com/54157749/63131688-42b3fd80-bfc7-11e9-90c1-1256e6f1b019.png)

**Comment by colorbash** [comment]
Добрый день, не могли бы вы выслать на почту api@hh.ru ваш логин и дату запроса, мы попытаемся выяснить в чем была проблема.

**Comment by colorbash** [comment]
Hello, could you please send a email on api@hh.ru with your login and date of request, we try to solve this problem soon, thank you!

**Comment by shurik2533** [comment]
Please make sure that all resume fields are completed. Regarding mobile app problems, please contact the application support. You can find contacts on application's help page
