### ISSUE TITLE
Получить список вакансий с заданными полями

### ISSUE THREAD

**Issue by nikitarui92** [hhru/api#396]
Проблема: Отсутсвие нескольких полей в вакансиях полученных через поиск https://api.hh.ru/vacancies. Например: schedule, description и.т.д.

Вопрос: Есть ли возможность передавать список полей вакансии в запрос https://api.hh.ru/vacancies? Например: https://api.hh.ru/vacancies?fields=schedule,description

**Comment by colorbash** [comment]
Добрый день, поля вакансии в поиске которые отдаются в апи описаны тут https://github.com/hhru/api/blob/master/docs/vacancies.md#%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%BF%D0%BE-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8F%D0%BC
Среди них нет schedule, description так как информация по вакансии в поиске вакансий выдаётся не полностью, как и на сайте в поиске вакансий нет полного описания.
Вся информация по получению вакансий через АПИ находится в нашей документации, возможности передавать список полей нет.
