### ISSUE TITLE
Поле specialization

### ISSUE THREAD

**Issue by diyelise** [hhru/api#397]
Добрый день! Проясните, пожалуйста такой момент

Например, есть вакансия ( 32832388 ) https://api.hh.ru/vacancies/32832388
У нее в поле специализация указаны несколько направлений
![image](https://user-images.githubusercontent.com/38560879/63221221-7eed8680-c19e-11e9-8c27-4219995ab636.png)
Там есть и 20 категория и 17. 
Так вот вопрос, эта вакансия входит и в 20 категорию (Туризм, гостиницы, рестораны) и в  17 (Продажи)?

**Comment by diyelise** [comment]
up!

**Comment by iriss22** [comment]
Добрый день. Да

**Comment by diyelise** [comment]
спасибо!
