### ISSUE TITLE
Авторизация приложением и доступ к определённым API

### ISSUE THREAD

**Issue by yuriuss** [hhru/api#405]
Здравствуйте.

Не совсем понятен механизм доступа к апи через приложение. (
Если я авторизуюсь как приложение, могу ли я запросить информацию по менеджерам? 
В общем описании стоит нотация emp, это что, получается что только через клиентскую вторизация я могу запросить апи менеджеров?

Спасибо за быстрый ответ. :)

**Comment by mxv2** [comment]
Добрый день.

Да, только через пользовательскую авторизацию работодателя.
