### ISSUE TITLE
не работает ссылка "подтвердить телефон" 

### ISSUE THREAD

**Issue by stasst777** [hhru/api#410]
по адресу:  https://tver.hh.ru/resume/a5f1ceb6ff05fbf7cc0039ed1f56635a4b386d?utm_medium=email&utm_source=email&utm_campaign=resume_approved&utm_content=2019_12_31&customDomain=1
1.в выпадающем окне под надписью " предпочитаемый способ связи" не работает ссылка "подтвердить телефон"  
2. и это окно не закрывается при нажатии на закрывающий крестик в правом верхнем углу.

ОС window 8.1 prof / Google Chrome Версия 79.0.3945.88 (Официальная сборка), (32 бит)

![bag hh](https://user-images.githubusercontent.com/59387135/71615405-3a4d0f80-2bc2-11ea-9ede-30b13901b727.jpg)

**Comment by iriss22** [comment]
Добрый день. Мы отвечаем только за проблемы связанные с API. По проблемам работы сайта напишите, пожалуйста: https://feedback.hh.ru/
