### ISSUE TITLE
Неверные данные геокодирования.

### ISSUE THREAD

**Issue by denanhel** [hhru/api#414]
Станции Текстильщики и Кубанская линии МЦД-2 Московского метрополитена имеют неверные координаты.

**Comment by denanhel** [comment]
Пришлось исправить данные Московского метро. Поправьте у себя.
Код линии | Линия | Код станции | Станция | Широта | Долгота
1 | Сокольническая | 1.117 | Преображенская площадь | 55,796322 | 37,713582
1 | Сокольническая | 1.118 | Проспект Вернадского | 55,676549 | 37,504584
1 | Сокольническая | 1.134 | Сокольники | 55,789282 | 37,679895
1 | Сокольническая | 1.135 | Спортивная | 55,722388 | 37,562041
1 | Сокольническая | 1.143 | Чистые пруды | 55,76499 | 37,638293
1 | Сокольническая | 1.149 | Университет | 55,69329 | 37,534511
1 | Сокольническая | 1.152 | Фрунзенская | 55,727462 | 37,58022
1 | Сокольническая | 1.155 | Черкизовская | 55,802787 | 37,744863
1 | Сокольническая | 1.162 | Юго-Западная | 55,663146 | 37,482852
1 | Сокольническая | 1.165 | Воробьевы горы | 55,709169 | 37,557293
1 | Сокольническая | 1.4 | Библиотека им.Ленина | 55,752123 | 37,610388
1 | Сокольническая | 1.505 | Тропарево | 55,6459 | 37,4725
1 | Сокольническая | 1.513 | Румянцево | 55,633 | 37,4419
1 | Сокольническая | 1.514 | Саларьево | 55,6227 | 37,424
1 | Сокольническая | 1.60 | Красносельская | 55,780014 | 37,666097
1 | Сокольническая | 1.61 | Красные ворота | 55,768307 | 37,6478
1 | Сокольническая | 1.64 | Кропоткинская | 55,745297 | 37,604217
1 | Сокольническая | 1.66 | Лубянка | 55,759889 | 37,625336
1 | Сокольническая | 1.678 | Филатов луг | 55,5997 | 37,4075
1 | Сокольническая | 1.679 | Прокшино | 55,5813 | 37,4425
1 | Сокольническая | 1.680 | Ольховая | 55,5677 | 37,459
1 | Сокольническая | 1.681 | Коммунарка | 55,5602999 | 37,4678071
1 | Сокольническая | 1.98 | Охотный ряд | 55,757228 | 37,615078
2 | Замоскворецкая | 2.12 | Аэропорт | 55,800441 | 37,530477
2 | Замоскворецкая | 2.122 | Тверская | 55,765343 | 37,603918
2 | Замоскворецкая | 2.125 | Речной вокзал | 55,854152 | 37,476728
2 | Замоскворецкая | 2.133 | Сокол | 55,805564 | 37,515245
2 | Замоскворецкая | 2.257 | Алма-Атинская | 55,63349 | 37,765678
2 | Замоскворецкая | 2.29 | Водный стадион | 55,838978 | 37,487515
2 | Замоскворецкая | 2.30 | Войковская | 55,818923 | 37,497791
2 | Замоскворецкая | 2.34 | Динамо | 55,789704 | 37,558212
2 | Замоскворецкая | 2.38 | Домодедовская | 55,610131 | 37,717111
2 | Замоскворецкая | 2.42 | Кантемировская | 55,636107 | 37,656218
2 | Замоскворецкая | 2.512 | Технопарк | 55,695 | 37,664167
2 | Замоскворецкая | 2.53 | Коломенская | 55,677423 | 37,663719
2 | Замоскворецкая | 2.558 | Ховрино | 55,8784245 | 37,4811753
2 | Замоскворецкая | 2.57 | Красногвардейская | 55,614075 | 37,742697
2 | Замоскворецкая | 2.674 | Беломорская | 55,8651 | 37,4764
2 | Замоскворецкая | 2.80 | Маяковская | 55,769808 | 37,596192
2 | Замоскворецкая | 2.89 | Новокузнецкая | 55,742391 | 37,62928
2 | Замоскворецкая | 2.96 | Орехово | 55,61269 | 37,695214
2 | Замоскворецкая | 2.99 | Театральная | 55,758808 | 37,61768
3 | Арбатско-Покровская | 3.100 | Площадь Революции | 55,756741 | 37,62236
3 | Арбатско-Покровская | 3.105 | Партизанская | 55,788401 | 37,74882
3 | Арбатско-Покровская | 3.106 | Первомайская | 55,794376 | 37,799364
3 | Арбатско-Покровская | 3.130 | Семеновская | 55,783096 | 37,719289
3 | Арбатско-Покровская | 3.159 | Щелковская | 55,809962 | 37,798261
3 | Арбатско-Покровская | 3.161 | Электрозаводская | 55,782057 | 37,7053
3 | Арбатско-Покровская | 3.17 | Бауманская | 55,772405 | 37,67904
3 | Арбатско-Покровская | 3.174 | Строгино | 55,803831 | 37,402405
3 | Арбатско-Покровская | 3.176 | Славянский бульвар | 55,729542 | 37,470973
3 | Арбатско-Покровская | 3.181 | Мякинино | 55,823342 | 37,385214
3 | Арбатско-Покровская | 3.183 | Митино | 55,846098 | 37,36122
3 | Арбатско-Покровская | 3.40 | Измайловская | 55,787713 | 37,779896
3 | Арбатско-Покровская | 3.463 | Пятницкое шоссе | 55,8559997 | 37,3546385
3 | Арбатско-Покровская | 3.65 | Крылатское | 55,756842 | 37,408139
3 | Арбатско-Покровская | 3.84 | Молодежная | 55,741375 | 37,415627
4 | Филевская |   | Кунцевская | 55,7305981 | 37,4453939
4 | Филевская | 4.11 | Арбатская | 55,752122 | 37,601553
4 | Филевская | 4.110 | Пионерская | 55,736027 | 37,466728
4 | Филевская | 4.132 | Смоленская | 55,749083 | 37,582173
4 | Филевская | 4.136 | Студенческая | 55,738761 | 37,54842
4 | Филевская | 4.14 | Багратионовская | 55,743544 | 37,497042
4 | Филевская | 4.150 | Филевский парк | 55,739665 | 37,483902
4 | Филевская | 4.150 | Кутузовская | 55,7397556 | 37,5350119
4 | Филевская | 4.150 | Фили | 55,7459097 | 37,514584
4 | Филевская | 4.150 | Киевская | 55,7430592 | 37,5638859
4 | Филевская | 4.172 | Выставочная | 55,750243 | 37,542641
4 | Филевская | 4.179 | Международная | 55,748324 | 37,533282
4 | Филевская | 4.6 | Александровский сад | 55,752255 | 37,608775
5 | Кольцевая | 5.102 | Павелецкая | 55,731414 | 37,636294
5 | Кольцевая | 5.104 | Парк культуры | 55,735221 | 37,593095
5 | Кольцевая | 5.119 | Проспект Мира | 55,779584 | 37,633646
5 | Кольцевая | 5.36 | Добрынинская | 55,728994 | 37,622533
5 | Кольцевая | 5.49 | Курская | 55,7574181 | 37,6580734
5 | Кольцевая | 5.49 | Белорусская | 55,7760562 | 37,5850628
5 | Кольцевая | 5.49 | Курская | 55,7574181 | 37,6580734
5 | Кольцевая | 5.49 | Киевская | 55,74361 | 37,56735
5 | Кольцевая | 5.55 | Комсомольская | 55,775672 | 37,654772
5 | Кольцевая | 5.58 | Краснопресненская | 55,760378 | 37,577114
5 | Кольцевая | 5.76 | Таганская | 55,742396 | 37,653334
5 | Кольцевая | 5.82 | Новослободская | 55,779606 | 37,601252
5 | Кольцевая | 5.93 | Октябрьская | 55,729264 | 37,611049
6 | Калужско-Рижская | 6.121 | Профсоюзная | 55,677671 | 37,562595
6 | Калужско-Рижская | 6.129 | Свиблово | 55,855558 | 37,653379
6 | Калужско-Рижская | 6.13 | Бабушкинская | 55,870641 | 37,664341
6 | Калужско-Рижская | 6.137 | Сухаревская | 55,772315 | 37,63285
6 | Калужско-Рижская | 6.140 | Теплый Стан | 55,61873 | 37,505912
6 | Калужско-Рижская | 6.144 | Тургеневская | 55,765371 | 37,636732
6 | Калужско-Рижская | 6.157 | Шаболовская | 55,718828 | 37,607892
6 | Калужско-Рижская | 6.164 | Ясенево | 55,606182 | 37,5334
6 | Калужско-Рижская | 6.164 | Китай-Город | 55,755468 | 37,6342304
6 | Калужско-Рижская | 6.164 | Октябрьская | 55,7303806 | 37,6117563
6 | Калужско-Рижская | 6.164 | Проспект Мира | 55,7808832 | 37,6325699
6 | Калужско-Рижская | 6.164 | Рижская | 55,7937505 | 37,6360027
6 | Калужско-Рижская | 6.164 | Ботанический Сад | 55,8451288 | 37,6379663
6 | Калужско-Рижская | 6.21 | Беляево | 55,642357 | 37,526115
6 | Калужско-Рижская | 6.23 | Новоясеневская | 55,601947 | 37,553017
6 | Калужско-Рижская | 6.27 | ВДНХ | 55,819626 | 37,640751
6 | Калужско-Рижская | 6.3 | Академическая | 55,687147 | 37,5723
6 | Калужско-Рижская | 6.41 | Калужская | 55,656682 | 37,540075
6 | Калужско-Рижская | 6.56 | Коньково | 55,631857 | 37,519156
6 | Калужско-Рижская | 6.74 | Ленинский проспект | 55,70678 | 37,58499
6 | Калужско-Рижская | 6.8 | Алексеевская | 55,807794 | 37,638699
6 | Калужско-Рижская | 6.81 | Медведково | 55,888103 | 37,661562
6 | Калужско-Рижская | 6.90 | Третьяковская | 55,74073 | 37,625624
6 | Калужско-Рижская | 6.92 | Новые Черемушки | 55,670077 | 37,554493
7 | Таганско-Краснопресненска | 7.111 | Планерная | 55,859676 | 37,436808
7 | Таганско-Краснопресненска | 7.114 | Полежаевская | 55,777201 | 37,517895
7 | Таганско-Краснопресненска | 7.124 | Пушкинская | 55,765607 | 37,604356
7 | Таганско-Краснопресненска | 7.127 | Рязанский проспект | 55,716139 | 37,792694
7 | Таганско-Краснопресненска | 7.138 | Сходненская | 55,84926 | 37,44076
7 | Таганско-Краснопресненска | 7.146 | Улица 1905 года | 55,763944 | 37,562271
7 | Таганско-Краснопресненска | 7.16 | Баррикадная | 55,760793 | 37,581242
7 | Таганско-Краснопресненска | 7.160 | Щукинская | 55,8094 | 37,463241
7 | Таганско-Краснопресненска | 7.31 | Волгоградский проспект | 55,725546 | 37,685197
7 | Таганско-Краснопресненска | 7.31 | Текстильщики | 55,7084869 | 37,7317585
7 | Таганско-Краснопресненска | 7.31 | Таганская | 55,7399126 | 37,6520219
7 | Таганско-Краснопресненска | 7.31 | Беговая | 55,7731958 | 37,5452577
7 | Таганско-Краснопресненска | 7.31 | Тушинская | 55,8263791 | 37,4373367
7 | Таганско-Краснопресненска | 7.33 | Выхино | 55,715983 | 37,816788
7 | Таганско-Краснопресненска | 7.464 | Лермонтовский проспект | 55,702036 | 37,851044
7 | Таганско-Краснопресненска | 7.465 | Жулебино | 55,684722 | 37,855833
7 | Таганско-Краснопресненска | 7.507 | Спартак | 55,8182 | 37,4352
7 | Таганско-Краснопресненска | 7.508 | Котельники | 55,6743 | 37,8582
7 | Таганско-Краснопресненска | 7.51 | Китай-город | 55,75436 | 37,633877
7 | Таганско-Краснопресненска | 7.62 | Пролетарская | 55,731546 | 37,666917
7 | Таганско-Краснопресненска | 7.67 | Кузнецкий мост | 55,761498 | 37,624423
7 | Таганско-Краснопресненска | 7.68 | Кузьминки | 55,705493 | 37,763295
7 | Таганско-Краснопресненска | 7.95 | Октябрьское поле | 55,793581 | 37,493317
8 | Калининская | 8.1 | Авиамоторная | 55,751933 | 37,717444
8 | Калининская | 8.107 | Перово | 55,75098 | 37,78422
8 | Калининская | 8.112 | Площадь Ильича | 55,747115 | 37,680726
8 | Калининская | 8.112 | Третьяковская | 55,7406313 | 37,6269144
8 | Калининская | 8.189 | Новокосино | 55,745113 | 37,864052
8 | Калининская | 8.78 | Марксистская | 55,740746 | 37,65604
8 | Калининская | 8.88 | Новогиреево | 55,752237 | 37,814587
9 | Серпуховско-Тимирязевская | 9.10 | Аннино | 55,583477 | 37,596999
9 | Серпуховско-Тимирязевская | 9.115 | Полянка | 55,736795 | 37,618594
9 | Серпуховско-Тимирязевская | 9.116 | Пражская | 55,610962 | 37,602386
9 | Серпуховско-Тимирязевская | 9.123 | Чеховская | 55,765747 | 37,608493
9 | Серпуховско-Тимирязевская | 9.128 | Савеловская | 55,794054 | 37,587163
9 | Серпуховско-Тимирязевская | 9.142 | Тульская | 55,70961 | 37,622569
9 | Серпуховско-Тимирязевская | 9.147 | Улица Академика Янгеля | 55,5948638 | 37,5999552
9 | Серпуховско-Тимирязевская | 9.147 | Дмитровская | 55,806927 | 37,5808777
9 | Серпуховско-Тимирязевская | 9.147 | Тимерязевская | 55,8175313 | 37,575052
9 | Серпуховско-Тимирязевская | 9.147 | Петровско-Разумовская | 55,8351646 | 37,5738716
9 | Серпуховско-Тимирязевская | 9.147 | Владыкино | 55,8473514 | 37,5895367
9 | Серпуховско-Тимирязевская | 9.154 | Цветной бульвар | 55,771653 | 37,620466
9 | Серпуховско-Тимирязевская | 9.156 | Чертановская | 55,640538 | 37,606065
9 | Серпуховско-Тимирязевская | 9.163 | Южная | 55,622436 | 37,609047
9 | Серпуховско-Тимирязевская | 9.170 | Бульвар Дмитрия Донского | 55,568201 | 37,576856
9 | Серпуховско-Тимирязевская | 9.22 | Бибирево | 55,883868 | 37,603011
9 | Серпуховско-Тимирязевская | 9.37 | Серпуховская | 55,726548 | 37,624792
9 | Серпуховско-Тимирязевская | 9.43 | Севастопольская | 55,651451 | 37,59809
9 | Серпуховско-Тимирязевская | 9.7 | Боровицкая | 55,750399 | 37,60934
9 | Серпуховско-Тимирязевская | 9.83 | Менделеевская | 55,781999 | 37,599141
9 | Серпуховско-Тимирязевская | 9.85 | Нагатинская | 55,682099 | 37,620917
9 | Серпуховско-Тимирязевская | 9.86 | Нагорная | 55,672962 | 37,610397
9 | Серпуховско-Тимирязевская | 9.87 | Нахимовский проспект | 55,662379 | 37,605274
9 | Серпуховско-Тимирязевская | 9.9 | Алтуфьево | 55,899034 | 37,586473
9 | Серпуховско-Тимирязевская | 9.97 | Отрадное | 55,864273 | 37,605066
10 | Люблинско-Дмитровская | 10.109 | Печатники | 55,692921 | 37,728338
10 | Люблинско-Дмитровская | 10.113 | Римская | 55,747027 | 37,679996
10 | Люблинско-Дмитровская | 10.175 | Сретенский бульвар | 55,766106 | 37,635688
10 | Люблинско-Дмитровская | 10.177 | Трубная | 55,76771 | 37,621926
10 | Люблинско-Дмитровская | 10.184 | Достоевская | 55,781667 | 37,613889
10 | Люблинско-Дмитровская | 10.185 | Марьина Роща | 55,793723 | 37,61618
10 | Люблинско-Дмитровская | 10.186 | Зябликово | 55,611944 | 37,745278
10 | Люблинско-Дмитровская | 10.187 | Борисово | 55,6325 | 37,743333
10 | Люблинско-Дмитровская | 10.188 | Шипиловская | 55,621667 | 37,743611
10 | Люблинско-Дмитровская | 10.25 | Братиславская | 55,658817 | 37,748415
10 | Люблинско-Дмитровская | 10.32 | Волжская | 55,690446 | 37,754314
10 | Люблинско-Дмитровская | 10.32 | Дубровка | 55,7188703 | 37,6763006
10 | Люблинско-Дмитровская | 10.32 | Окружная | 55,84614 | 37,574184
10 | Люблинско-Дмитровская | 10.52 | Кожуховская | 55,706156 | 37,68544
10 | Люблинско-Дмитровская | 10.546 | Бутырская | 55,813333 | 37,602778
10 | Люблинско-Дмитровская | 10.547 | Фонвизинская | 55,822778 | 37,588056
10 | Люблинско-Дмитровская | 10.548 | Петровско-Разумовская | 55,836667 | 37,575556
10 | Люблинско-Дмитровская | 10.597 | Селигерская | 55,86483 | 37,55005
10 | Люблинско-Дмитровская | 10.598 | Верхние Лихоборы | 55,85566 | 37,56282
10 | Люблинско-Дмитровская | 10.63 | Крестьянская застава | 55,732278 | 37,665325
10 | Люблинско-Дмитровская | 10.72 | Чкаловская | 55,755951 | 37,659293
10 | Люблинско-Дмитровская | 10.75 | Люблино | 55,676596 | 37,761639
10 | Люблинско-Дмитровская | 10.79 | Марьино | 55,649158 | 37,743844
11 | Каховская | 11.26 | Варшавская | 55,653294 | 37,619522
11 | Каховская | 11.44 | Каховская | 55,652923 | 37,596573
11 | Каховская | 11.46 | Каширская | 55,654327 | 37,647705
12 | Бутовская | 12.166 | Улица Скобелевская | 55,548103 | 37,552721
12 | Бутовская | 12.167 | Бунинская аллея | 55,537977 | 37,515899
12 | Бутовская | 12.168 | Улица Горчакова | 55,542281 | 37,532063
12 | Бутовская | 12.169 | Бульвар Адмирала Ушакова | 55,545207 | 37,542329
12 | Бутовская | 12.171 | Улица Старокачаловская | 55,569194 | 37,576074
12 | Бутовская | 12.466 | Лесопарковая | 55,581656 | 37,577816
12 | Бутовская | 12.467 | Битцевский Парк | 55,600066 | 37,556058
95 | МЦК | 95.516 | Владыкино | 55,847222 | 37,591944
95 | МЦК | 95.517 | Ботанический сад | 55,845556 | 37,640278
95 | МЦК | 95.518 | Ростокино | 55,839444 | 37,667778
95 | МЦК | 95.518 | Стрешнево | 55,8135106 | 37,4864751
95 | МЦК | 95.518 | Шелепиха | 55,7573335 | 37,5249278
95 | МЦК | 95.518 | Новохохловская | 55,7241939 | 37,7166307
95 | МЦК | 95.519 | Белокаменная | 55,83 | 37,700556
95 | МЦК | 95.520 | Бульвар Рокоссовского | 55,817222 | 37,736944
95 | МЦК | 95.521 | Локомотив | 55,803219 | 37,745742
95 | МЦК | 95.522 | Измайлово | 55,788611 | 37,742778
95 | МЦК | 95.523 | Соколиная Гора | 55,77 | 37,745278
95 | МЦК | 95.524 | Шоссе Энтузиастов | 55,758633 | 37,748477
95 | МЦК | 95.525 | Андроновка | 55,7462297 | 37,7364465
95 | МЦК | 95.525 | Окружная | 55,8486343 | 37,571566
95 | МЦК | 95.526 | Нижегородская | 55,732222 | 37,72825
95 | МЦК | 95.528 | Угрешская | 55,718333 | 37,697778
95 | МЦК | 95.529 | Дубровка | 55,71268 | 37,677775
95 | МЦК | 95.530 | Автозаводская | 55,70631 | 37,66314
95 | МЦК | 95.531 | ЗИЛ | 55,698333 | 37,648333
95 | МЦК | 95.532 | Верхние Котлы | 55,69 | 37,618889
95 | МЦК | 95.533 | Крымская | 55,690038 | 37,605
95 | МЦК | 95.534 | Площадь Гагарина | 55,706944 | 37,585833
95 | МЦК | 95.535 | Лужники | 55,720278 | 37,563056
95 | МЦК | 95.536 | Кутузовская | 55,740833 | 37,533333
95 | МЦК | 95.539 | Хорошево | 55,777222 | 37,507222
95 | МЦК | 95.540 | Зорге | 55,787778 | 37,504444
95 | МЦК | 95.541 | Панфиловская | 55,799167 | 37,498889
95 | МЦК | 95.543 | Балтийская | 55,825833 | 37,496111
95 | МЦК | 95.544 | Коптево | 55,839637 | 37,520037
95 | МЦК | 95.545 | Лихоборы | 55,847222 | 37,551389
96 | Монорельс | 96.550 | Улица Милашенкова | 55,821876 | 37,591206
96 | Монорельс | 96.551 | Телецентр | 55,821795 | 37,608975
96 | Монорельс | 96.552 | Улица Академика Королёва | 55,821821 | 37,627167
96 | Монорельс | 96.553 | Выставочный центр | 55,824086 | 37,638494
96 | Монорельс | 96.554 | Улица Сергея Эйзенштейна | 55,829305 | 37,644997
97 | Большая кольцевая линия | 97.601 | Хорошевская | 55,77643 | 37,51981
98 | Некрасовская | 98.641 | Некрасовка | 55,7029 | 37,9264
98 | Некрасовская | 98.675 | Косино | 55,7026 | 37,8511
98 | Некрасовская | 98.676 | Улица Дмитриевского | 55,7093 | 37,8792
98 | Некрасовская | 98.677 | Лухмановская | 55,7078 | 37,9004
131 | МЦД - 1 | 131.687 | Лобня | 56,0137153 | 37,4842973
131 | МЦД - 1 | 131.687 | Савёловская | 55,794426 | 37,5890312
131 | МЦД - 1 | 131.687 | Сколково | 55,7003742 | 37,3417521
131 | МЦД - 1 | 131.688 | Шереметьевская | 55,983882 | 37,498752
131 | МЦД - 1 | 131.689 | Хлебниково | 55,970682 | 37,504638
131 | МЦД - 1 | 131.690 | Водники | 55,953419 | 37,511143
131 | МЦД - 1 | 131.691 | Долгопрудная | 55,938656 | 37,520542
131 | МЦД - 1 | 131.692 | Новодачная | 55,924459 | 37,527877
131 | МЦД - 1 | 131.693 | Марк | 55,904458 | 37,538242
131 | МЦД - 1 | 131.694 | Лианозово | 55,897316 | 37,553261
131 | МЦД - 1 | 131.695 | Бескудниково | 55,882713 | 37,567768
131 | МЦД - 1 | 131.696 | Дегунино | 55,86586 | 37,573235
131 | МЦД - 1 | 131.697 | Окружная | 55,848889 | 37,571111
131 | МЦД - 1 | 131.698 | Тимирязевская | 55,81866 | 37,574498
131 | МЦД - 1 | 131.700 | Белорусская | 55,775179 | 37,582303
131 | МЦД - 1 | 131.701 | Беговая | 55,773505 | 37,545518
131 | МЦД - 1 | 131.702 | Тестовская | 55,754292 | 37,531551
131 | МЦД - 1 | 131.703 | Фили | 55,744263 | 37,514526
131 | МЦД - 1 | 131.704 | Кунцевская | 55,7267194 | 37,4492988
131 | МЦД - 1 | 131.705 | Рабочий Посёлок | 55,726957 | 37,415577
131 | МЦД - 1 | 131.706 | Сетунь | 55,723713 | 37,397259
131 | МЦД - 1 | 131.707 | Немчиновка | 55,715668 | 37,374611
131 | МЦД - 1 | 131.709 | Баковка | 55,682816 | 37,315205
131 | МЦД - 1 | 131.710 | Одинцово | 55,6724623 | 37,2832821
132 | МЦД - 2 | 132.711 | Нахабино | 55,841522 | 37,185204
132 | МЦД - 2 | 132.712 | Аникеевка | 55,832099 | 37,219829
132 | МЦД - 2 | 132.713 | Опалиха | 55,82333 | 37,246843
132 | МЦД - 2 | 132.714 | Красногорская | 55,814571 | 37,303337
132 | МЦД - 2 | 132.715 | Павшино | 55,815231 | 37,341461
132 | МЦД - 2 | 132.715 | Покровская | 55,602459 | 37,632033
132 | МЦД - 2 | 132.716 | Пенягино | 55,8230222 | 37,360969
132 | МЦД - 2 | 132.717 | Волоколамская | 55,835154 | 37,382453
132 | МЦД - 2 | 132.718 | Тушинская | 55,825479 | 37,437024
132 | МЦД - 2 | 132.719 | Покровское-Стрешнево | 55,814247 | 37,47678
132 | МЦД - 2 | 132.720 | Стрешнево | 55,8152105 | 37,4899643
132 | МЦД - 2 | 132.721 | Красный Балтиец | 55,815514 | 37,526367
132 | МЦД - 2 | 132.722 | Гражданская | 55,805527 | 37,55315
132 | МЦД - 2 | 132.723 | Дмитровская | 55,808056 | 37,581734
132 | МЦД - 2 | 132.724 | Рижская | 55,7936479 | 37,6392112
132 | МЦД - 2 | 132.725 | Каланчёвская | 55,7763518 | 37,6513556
132 | МЦД - 2 | 132.726 | Курская | 55,757622 | 37,660767
132 | МЦД - 2 | 132.727 | Москва Товарная | 55,745358 | 37,688839
132 | МЦД - 2 | 132.728 | Калитники | 55,733981 | 37,702203
132 | МЦД - 2 | 132.729 | Новохохловская | 55,7246168 | 37,7128966
132 | МЦД - 2 | 132.730 | Текстильщики | 55,708934 | 37,731283
132 | МЦД - 2 | 132.731 | Кубанская | 55,6851294 | 37,7342575
132 | МЦД - 2 | 132.732 | Депо | 55,674257 | 37,728446
132 | МЦД - 2 | 132.733 | Перерва | 55,660809 | 37,716278
132 | МЦД - 2 | 132.734 | Москворечье | 55,641239 | 37,689789
132 | МЦД - 2 | 132.735 | Царицыно | 55,618309 | 37,668846
132 | МЦД - 2 | 132.737 | Красный строитель | 55,589455 | 37,615093
132 | МЦД - 2 | 132.738 | Битца | 55,571186 | 37,611443
132 | МЦД - 2 | 132.739 | Бутово | 55,5409578 | 37,5706958
132 | МЦД - 2 | 132.740 | Щербинка | 55,509724 | 37,562008
132 | МЦД - 2 | 132.741 | Остафьево | 55,4856495 | 37,5552465
132 | МЦД - 2 | 132.742 | Силикатная | 55,470278 | 37,555278
132 | МЦД - 2 | 132.743 | Подольск | 55,431667 | 37,565
132 | МЦД - 2 | 132.744 | Трикотажная | 55,8330317 | 37,3990667
133 | Солнцевская | 133.745 | Савёловская | 55,792707 | 37,586349
133 | Солнцевская | 133.746 | Петровский парк | 55,7917902 | 37,5574785
133 | Солнцевская | 133.747 | ЦСКА | 55,7864215 | 37,53366
133 | Солнцевская | 133.748 | Хорошёвская | 55,7769975 | 37,5187253
133 | Солнцевская | 133.749 | Шелепиха | 55,75723 | 37,52571
133 | Солнцевская | 133.750 | Деловой центр | 55,7491 | 37,5395
133 | Солнцевская | 133.751 | Парк Победы | 55,735895 | 37,5180602
133 | Солнцевская | 133.752 | Минская | 55,723644 | 37,4981041
133 | Солнцевская | 133.753 | Ломоносовский проспект | 55,7055557 | 37,5128058
133 | Солнцевская | 133.754 | Раменки | 55,6979557 | 37,4982123
133 | Солнцевская | 133.755 | Мичуринский проспект | 55,6898226 | 37,4825809
133 | Солнцевская | 133.756 | Озёрная | 55,6708952 | 37,4491173
133 | Солнцевская | 133.757 | Говорово | 55,6592887 | 37,416866
133 | Солнцевская | 133.758 | Солнцево | 55,6492709 | 37,391224
133 | Солнцевская | 133.759 | Боровское шоссе | 55,6479209 | 37,370068
133 | Солнцевская | 133.760 | Новопеределкино | 55,6391294 | 37,3553038
133 | Солнцевская | 133.761 | Рассказовка | 55,6336853 | 37,3347047

**Comment by iriss22** [comment]
Добрый день. Завела задачу, спасибо за бдительность. Когда поправим, тут напишу

**Comment by denanhel** [comment]
В комментарии вложил верные данные. Все геокоординаты проверены и соответствуют действительности. Погрешность не более 20 метров.

  
>Пятница, 7 февраля 2020, 11:54 +03:00 от Irina Petrova <notifications@github.com>:
> 
>Добрый день. Завела задачу, спасибо за бдительность. Когда поправим, тут напишу
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,

starboytor@mail.ru

**Comment by iriss22** [comment]
координаты поправили, спасибо
