### ISSUE TITLE
autosuggest регионов

### ISSUE THREAD

**Issue by 90dend** [hhru/api#42]
Можно ли каким-нибудь образом, проверить присутствует ли город в базе данных городов, получить id города чтобы потом использовать его, а не загружать все города, которых много, а работать только с одним городом.

**Comment by maizy** [comment]
Забыл написать.

Выпустили некоторое время назад - https://github.com/hhru/api/blob/master/docs/suggests.md#areas.
Есть как подсказки по всем регионам, так и по листьям дерева регионов.
