### ISSUE TITLE
Не получили ответ от техподдержки по api hh

### ISSUE THREAD

**Issue by Allcv** [hhru/api#425]
Доброго времени суток.

Уже длительное время назад отправили в техподдержку hh.ru запрос на получение тестового токена для разработки . Но так и не получили ответ.

Почему так долго не можем получить ответ и тестовый токен?

Вот текст запроса, который был ранее отправлен:
"Здравствуйте.
Уже довольно рассматривается заявка на регистрацию приложения.
Когда примерно оно будет зарегистрировано?
Сейчас сервис в процессе создания и работает на временном урле:
 
Для отправки данных приложение должно получать токен и возможность создавать резюме.
Однако, у меня отсутствуют client_id и client_secret......"

Спасибо.

Сергей

**Comment by verkhovin** [comment]
Добрый день.
Заявка на создание приложения должна пройти проверку нескольких отделов, этот процесс может занимать до 20 рабочих дней (это явно указано на форме регистрации). Мы можем предоставить информацию о статусе заявки, но не влиять на скорость/обсуждение/результат.

Если у Вас возникли сложности и вопросы, напишите, пожалуйста, еще раз на api@hh.ru. Приложите к письму номер заявки на создание приложения

**Comment by Allcv** [comment]
Добрый день. 
Ждем тогда ответ по результатам проверки.

Спасибо за оперативный ответ!
