### ISSUE TITLE
Фильтрация удаленной работы по часовым поясам. (Новая функция)

### ISSUE THREAD

**Issue by Foxonn** [hhru/api#431]
Не увидел куда писать предложения, потому пишу сюда.

Почему бы не сделать фильтрацию вакансий на удаленной работы в пределах указанных часовых поясов?

Для примера. 
У меня GMT+6, в выдаче на удаленную работу мне выпадает Москва GMT+3, но мне такой GMT не устраивает я бы хотел видеть объявление из городов где часовой пояс, от GMT+4 до GMT+8, что сразу бы отсеяло ненужные объявления.

**Comment by shurik2533** [comment]
Спасибо за идею. Передал менеджерам
