### ISSUE TITLE
Формат данных Word

### ISSUE THREAD

**Issue by ceasar13m** [hhru/api#440]
Передо мной стоит задача получения данных из doc - файлов с резюме с сайта hh.ru. Есть ли у вас стандарт структуры файла? Можно ли его получить?

**Comment by ceasar13m** [comment]
Еще один момент. 
Библиотека Apache POI ругается на ваш doc файл. Пишет, что на самом деле это rtf. Не могли бы вы прокомментировать?

**Comment by iriss22** [comment]
У нас нет формата структуры файла.
Да, он на самом деле rtf, вы правы, так исторически сложилось.
Зачем вам парсить док файл, если можно воспользоваться методом, получения резюме https://github.com/hhru/api/blob/master/docs/resumes.md#%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80-%D1%80%D0%B5%D0%B7%D1%8E%D0%BC%D0%B5

**Comment by ceasar13m** [comment]
> У нас нет формата структуры файла.
> Да, он на самом деле rtf, вы правы, так исторически сложилось.
> Зачем вам парсить док файл, если можно воспользоваться методом, получения резюме https://github.com/hhru/api/blob/master/docs/resumes.md#%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80-%D1%80%D0%B5%D0%B7%D1%8E%D0%BC%D0%B5

Задача сформулирована именно так, поэтому не могу воспользоваться api.

**Comment by iriss22** [comment]
К сожалению, у нас нет нужной вам информации.
Для задач такого рода правильнее и легче пользоваться методами API.
