### ISSUE TITLE
Не показывать/ Эту вакансию - не работает!

### ISSUE THREAD

**Issue by Vermilleon** [hhru/api#441]
После обновления страницы с вакансиями, снова показывает только что скрытые вакансии или скрытые ранее. По крайней мере в моём аккаунте. Исправьте пожалуйста. (браузер Chrome/ настольный ПК)

**Comment by adanilkina** [comment]
Добрый день, здесь мы можем подсказать, только по вопросам использования API HH или вопросам связанным с API. Если что-то не работает на сайте, обратитесь пожалуйста в поддержку сайта - в вашем личном кабинете есть кнопка Помощь -> Сообщество поддержки.
