### ISSUE TITLE
HH API resumes/{id}/publish get 405 Method Not Allowed

### ISSUE THREAD

**Issue by kenny-michael** [hhru/api#445]
[HTTP STATUS] (https://api.hh.ru/resumes/e2624921ff0385fd870039ed1f4f6633366a52/status) 200: OK
```
Array
(
	[status] => Array
		(
			[id] => published
			[name] => опубликовано
		)
	[blocked] => 
	[finished] => 1
	[moderation_note] => Array
		(
		)
	[can_publish_or_update] => 1
	[publish_url] => https://api.hh.ru/resumes/e2624921ff0385fd870039ed1f4f6633366a52/publish
	[progress] => Array
		(
			[percentage] => 77
			[mandatory] => Array
				(
				)
			[recommended] => Array
				(
					[0] => Array
						(
							[id] => education
							[name] => Образование
						)
					[1] => Array
						(
							[id] => hidden_fields
							[name] => Список скрытых полей
						)
					[2] => Array
						(
							[id] => relocation
							[name] => Переезд
						)
					[3] => Array
						(
							[id] => recommendation
							[name] => Рекомендации
						)
					[4] => Array
						(
							[id] => salary
							[name] => Зарплата
						)
					[5] => Array
						(
							[id] => portfolio
							[name] => Портфолио
						)
				)
		)
)
```

[HTTP STATUS] (https://api.hh.ru/resumes/e2624921ff0385fd870039ed1f4f6633366a52/publish) 405: Method Not Allowed
```
Array
(
	[errors] => Array
		(
			[0] => Array
				(
					[type] => method_not_allowed
				)
		)
	[request_id] => 159947751467247ed53ef7aa7c661cdb
)	
```

Отсутствует поле [next_publish_at].

**Comment by kenny-michael** [comment]
без глубокого изучения кода, понятно, что даже если запрос составлен был бы не верно, то получать должны
"errors":[{"type":"forbidden"}] ну никак не "errors":[{"type":"method_not_allowed"}]
метод поломался, почините пожалуйста или дайте новую реализацию, если метод и инструкция по API устарели.

**Comment by kenny-michael** [comment]
@ixth @tanchu @mikesub @aognev дайте решение пожалуйста.

**Comment by colorbash** [comment]
@kenny-michael  Добрый день, судя по логам, вы делали GET запрос на публикацию резюме, который требует POST, мы не можем выводить ошибку формата входных данных запроса при неправильном `method` запроса, тк как минимум не известно какой метод подразумевался пользовтелем изначально, если доступных методов больше чем один то ошибка может быть разной в зависимости от конкретного метода, не понятно какой метод пользователь хотел ввести.. 
В конкретном частном случае вам может казаться это логичным, маппить гет на пост, потому что по этому урлу 1 метод, но в общем случае это вызовет путаницу у интеграторов. Мы не любим неоднозначность
Мы не будем менять логику..

**Comment by ByxaAKALibovski** [comment]
@colorbash Здравствуйте, столкнулся с такой же проблемой, но я указывал метод POST, сможете помочь?

**Comment by colorbash** [comment]
@ByxaAKALibovski а request_id можно?

**Comment by igorkravitz** [comment]
Здравствуйте, аналогичная проблема с методом publish
Вызываю команду 
POST https://api.hh.ru/resumes/{resume_id}/publish
В ответ приходит
Код состояния: 403
{"description":"Forbidden","errors":[{"type":"forbidden"}],"request_id":"171604212398694f4de196568fa2d337"}
Другая команда с теми же заголовками, параметрами
GET https://api.hh.ru/resumes/{resume_id}/status
Возвращает
Код состояния: 200
{"status":{"id":"published","name":"опубликовано"},"blocked":false,"finished":true,"moderation_note":[],"can_publish_or_update":false,"publish_url":"https://api.hh.ru/resumes/*************/publish?locale=RU&host=hh.ru","progress":{"percentage":93,"mandatory":[],"recommended":[{"id":"birth_date","name":"Дата рождения"},{"id":"education","name":"Образование"},{"id":"district","name":"Район проживания"},{"id":"hidden_fields","name":"Список скрытых полей"}]}}
Авторизацию пользователя успешно выполнил. Получил access_token, refresh_token.
Просьба помочь разобраться с ошибкой.
