### ISSUE TITLE
Из поиска вакансий пропало поле contacts

### ISSUE THREAD

**Issue by olegklimakov** [hhru/api#451]
```https://api.hh.ru/vacancies?per_page=100&page=0&area=90&order_by=publication_time&clusters=true&enable_snippets=true&only_with_salary=true```
Запрос
До сегодняшнего дня поле контакты приходило нормально, теперь везде null. С чем это связано?

**Comment by yyakhontov** [comment]
Добрый день. Уточняем информацию. 

Уточните пожалуйста все параметры запроса который вы делаете на api@hh.ru

**Comment by yyakhontov** [comment]
Обязательно с заголовками

**Comment by olegklimakov** [comment]
:authority: api.hh.ru
:method: GET
:path: /vacancies?per_page=100&page=0&area=90&order_by=publication_time&clusters=true&enable_snippets=true
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
origin: http://81.173.114.160:8081
referer: http://81.173.114.160:8081/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

**Comment by iriss22** [comment]
Добрый день!
Для безопасности наших пользователей, контакты более не доступны в анонимной части API.
Рекомендуем подать заявку на регистрацию приложения (https://dev.hh.ru/admin) и использовать авторизацию (https://github.com/hhru/api/blob/master/docs/authorization_for_application.md) на уровне приложения.

**Comment by ushakov-s** [comment]
Но контакты всё ещё доступны в анонимной части сайта!
Если не залогиниться на сайте - контакты всё равно видны.
Тут видится какая-то неконсистентность.
Кроме того, такое положение вещей может привести к тому, что разработчики переключатся с использования API на скраппинг.

**Comment by iriss22** [comment]
Добрый день!
Это сделано для того, чтобы мы могли контролировать массовую выгрузку резюме, чтобы видеть, когда контакты выгружаются для каких-то других целей, не связанных с рекрутингом. Мы понимаем, что обходные пути всегда будут. Но если партнер заинтересован легально с нами работать, то мы даем ему инструмент и просим авторизовать приложение + готовы оказывать поддержку. Другие решения мы не поддерживаем, о чем прямо написано в политике пользования сайтом.
Поход в API с токеном приложения равносилен анонимному походу (вы не авторизуете при этом пользователя). Этот способ авторизации значительно проще, чем авторизация пользователя (достаточно дернуть 1 запрос и вы получаете вечный токен). При этом нам удобнее, когда мы знаем, какие приложения какими методами пользуются, зная это мы можем заранее предупреждать пользователей об изменениях в API. При анонимной авторизации, конечно, тоже есть механизм для этого (передача email в User-Agent), но он менее надежный.
