### ISSUE TITLE
contacts : null

### ISSUE THREAD

**Issue by VicLo2020** [hhru/api#453]
Здравствуйте
С чем связано НЕ получение информации о контакте
например запрос
https://api.hh.ru/vacancies?employer_id=4890554
получаю
"contacts":null
вместо
"contacts": {
        "name": "Имя",
        "email": "user@example.com",
        "phones": [
            {
                "country": "7",
                "city": "985",
                "number": "000-00-00",
                "comment": null
            }
        ]
    },

**Comment by adanilkina** [comment]
Добрый день!
Для безопасности наших пользователей, контакты более не доступны в анонимной части API.
Рекомендуем подать заявку на регистрацию приложения (https://dev.hh.ru/admin) и использовать авторизацию (https://github.com/hhru/api/blob/master/docs/authorization_for_application.md) на уровне приложения.
