### ISSUE TITLE
Не могу получить вакансии за 2 прошлых года

### ISSUE THREAD

**Issue by Volkonenkoff** [hhru/api#456]
Не могу получить вакансии за прошлые 2 года, даже с указанием на то, что выборка производится на 2 года раньше текущего и что записи имеют архивный тип

**Comment by Volkonenkoff** [comment]
Это, к слову, вообще возможно то?

**Comment by adanilkina** [comment]
Добрый день, подскажите, пожалуйста, каким методом вы пользуетесь для выгрузки архивных вакансий и что значит `даже с указанием на то, что выборка производится на 2 года раньше текущего`?

**Comment by Volkonenkoff** [comment]
> Добрый день, подскажите, пожалуйста, каким методом вы пользуетесь для выгрузки архивных вакансий
А каким методом нужно пользоваться? Я делал так:
` req = requests.get('https://api.superjob.ru/2.0/vacancies/', params) # Посылаем запрос к API
    data = req.content.decode() # Декодируем его ответ, чтобы Кириллица отображалась корректно
    req.close()`
  
Где params - список параметров из документации, там я прописывал date_from, date_to (это к тому, что выборка производилась с периода на два года раньше чем этот и по текущий год), также пытался указывать поле archived: true и hidden:true

**Comment by adanilkina** [comment]
Добрый день, `https://api.superjob.ru/2.0/vacancies/` - могу предположить, что это API superjob, а не HH. 
Урл для поиска вакансий через API HH будет следующим: `https://api.hh.ru/vacancies`
Более того, у нас нет соритровки по параметрам archived и hidden, все допустимые для поиска параметры перечислены в документации https://github.com/hhru/api/blob/master/docs/vacancies.md#%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%BF%D0%BE-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8F%D0%BC
причем обратите внимание, что неизвестные параметры и параметры с ошибкой в названии игнорируются.

Если вы пытаетесть выгрузить вакансии двухгодичной давности, убедитесь, что такие же вакансии выгружаются и на сайте, т.к. API HH работает аналогично сайту и если на сайте нет возможности выгрузить такие вакансии, то через API это также не получится сделать.
