### ISSUE TITLE
Безопасность токена или CORS хотябы

### ISSUE THREAD

**Issue by vasilyman** [hhru/api#457]
Добрый день! Скажите, как обезопасить свой токен приложения? В доках указано что токен не имеет ни ограничения жизни, ни ограничения CORS. Переписывать все методы на своем сервере??

**Comment by verkhovin** [comment]
Здравствуйте!
Для коммуникаций с API лучше всего использовать https.
Также можете чаще перезапращивать токен приложения (проходить процесс авторизации приложения). Старый токен после получения нового токена становится недействительным.
