### ISSUE TITLE
Настраиваемый вывод полей в поиске

### ISSUE THREAD

**Issue by Yuribtr** [hhru/api#460]
Подскажите  пожалуйста, я правильно понимаю, что в  вашем API нет метода возврата определенных полей в поиске вакансий (ну кроме responses_count_enabled)?

Мне   хотелось  бы  получать  некоторые  поля  вакансии  (description, key_skills)  в  поиске  по вакансиям (/vacancies), чтобы не заходить в каждую вакансию отдельно (так уменьшится число запросов).

Сейчас в поиск выводится много информации, но нужной мне к сожалению нет. Было бы круто добавить параметр - список полей, которые может возвращать поиск.

**Comment by verkhovin** [comment]
Здравствуйте!
Спасибо за обращение!
В поиске вакансий выводятся короткое представление вакансии для первичного ознакомления. В настоящее время мы не планируем делать описанный вами функционал.

**Comment by Yuribtr** [comment]
Жаль. Спасибо.
