### ISSUE TITLE
Не выходит прочитать все найденные вакансии с помощью пагинации

### ISSUE THREAD

**Issue by MrKamaBullet05** [hhru/api#461]
Всем привет! Недавно я заметил, что не выходит прочитать все найденные вакансии с помощью пагинации. Приведу конкретный пример, я решил найти все вакансии специализации 1 в городе 26, у меня вышел такой запрос:
`GET /vacancies?page=0&per_page=100&specialization=1&area=26&order_by=publication_time`

Вот послал я первый запрос и получил что найдено 1520 вакансий. Далее, посылая тот же запрос, заменяя page от 0 до 15, я считал 1520 вакансий. Вроде бы все хорошо, но сделав distinct по id вакансии у меня получилось 1518 вакансий. Отмечу, что каждый посланный запрос возвращал ответ, в котором общее число найденных вакансий не менялось (1520). Пробежаться по всем 16-ти страницам поиска заняло несколько секунд, никто бы не успел добавить/удалить вакансию в 2 часа ночи.

Далее я начал с периодичностью 30-120 секунд запускать считывание вакансий. Иногда у меня получалось прочитать все 1520 вакансий, но чаще всего я получал 1517-1519 вакансий.

Похоже проблемы возникают из-за order_by=publication_time

**Comment by MrKamaBullet05** [comment]
Похоже проблемы возникают из-за _order_by=publication_time_

**Comment by Diacrome** [comment]
Благодарим вас за обращение.
Мы проведем расследование ситуации.

**Comment by MrKamaBullet05** [comment]
@Diacrome дайте знать если не выйдет воспроизвести проблему. Судя по всему именно использование _order_by=publication_time_ как-то влияет на результат, без этого параметра все работает четко.

**Comment by MrKamaBullet05** [comment]
Сейчас проблема с город №26 при использовании _order_by=publication_time_ ушла. Но попробуйте считать первые 2к найденных вакансий с использованием _order_by=publication_time_ в городе №3. После distinct по id вакансии получается не 2000 вакансий, а 1998 или 1999, если _per_page=100_, а если _per_page=50_, то 1994-1996 вакансий.

**Comment by Diacrome** [comment]
Провели проверку.
Дело в том, что количество вакансий меняется очень часто. Они публикуются и снимаются, в том числе и автоматизированными системами, в том числе и ночью.
Если пробежаться по всем вакансиям при контроле общего количества найденных(вакансии не обязательно те же, если добавить и убрать разные вакансии одновременно — общее количество не изменится), то не удалось воспроизвести ошибку.
При уменьшении per_page - количество запросов увеличивается в 2 раза, а значит увеличивается время, за которое кто-то может убрать или опубликовать вакансию.
order_by=publication_time позволяет заметить эти изменения, так как вакансии попадают в начало списка
Дополнительно обращаю ваше внимание на лимит в [2000 элементов](https://github.com/hhru/api/blob/master/docs/vacancies.md#%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81)
Код тестов https://repl.it/@Diacrome/HhApiPaginationTest

**Comment by MrKamaBullet05** [comment]
> Дело в том, что количество вакансий меняется очень часто. Они публикуются и снимаются, в том числе и автоматизированными системами, в том числе и ночью.
> order_by=publication_time позволяет заметить эти изменения, так как вакансии попадают в начало списка

Спасибо за ответ!
