### ISSUE TITLE
Вакансия без id работодателя?

### ISSUE THREAD

**Issue by MrKamaBullet05** [hhru/api#463]
Добрый день! Столкнулся c вакансией, которая в объекте _employer_, содержит только _name_, даже _id_ нет. Это значит, что работодатель приватный? 

Пример:  [https://api.hh.ru/vacancies/40730471](https://api.hh.ru/vacancies/40730471)

**Comment by iriss22** [comment]
Добрый день! Да, это значит, что вакансия анонимная

**Comment by iriss22** [comment]
это можно понять по 
`"type": {
"id": "anonymous",
"name": "Анонимная"
}`
