### ISSUE TITLE
Брендированное описание "перекрывает" стандартное описание (вакансии/работодателя)?

### ISSUE THREAD

**Issue by MrKamaBullet05** [hhru/api#464]
Добрый день! Нигде не могу найти информацию о том, будет ли где-то использоваться (напр. при поиске или на мобильных платформах) стандартное описание (вакансии/работодателя), если имеется брендированное описание? Есть ли смысл заглядывать в стандартное описание если есть брендированное? Ведь сделав брендированное описание, работодатель может перестать обновлять (забить) стандартное описание, таким образом стандартное описание может быть не актуальным. Существуют ли какие-то механизмы, заставляющие работодателя поддерживать актуальным стандартное описание?

**Comment by adanilkina** [comment]
Добрый день, на всякий случай дублирую ответ из переписки в твиттере :) 
В целом то, как работает поиск по брендированным вакансиям лучше уточнить в сообществе поддержки, т.к. api будет работать аналогично поиску на сайте. Также запросили информацию у коллег по поводу поиска:
Обычно в брендированное описание подтягивается обычное, но если прям специфическое поставили, то в поиск все равно попадет обычное.

Что касается механизмов поддержки актуальным описания, то таких механизмов в api нет.
