### ISSUE TITLE
Через API я получил описание вакансии, которой нет на сайте (404)

### ISSUE THREAD

**Issue by MrKamaBullet05** [hhru/api#465]
Добрый день! Я наткнулся на вакансию [27294](https://api.hh.ru/vacancies/27294), описание которой выходит получить через API, хотя вакансии [на сайте нет](https://hh.ru/vacancies/27294) (ошибка 404).

**Comment by verkhovin** [comment]
Добрый день!
Вы пытаетесь получить вакансию на сайте по неправильному адресу. Вот вакансия, о которой вы говорите, на сайте: https://hh.ru/vacancy/27294.
Тот же url можно получить из ответа от API, на который вы ссылаетесь: 
```
...
"alternate_url": "https://hh.ru/vacancy/27294"
...
```
