### ISSUE TITLE
доступ к API самого соискателя

### ISSUE THREAD

**Issue by aliczin** [hhru/api#468]
Возможно ли мне как физическому лицу использовать доступ к API со стороны соискателя ? Пока интересует только редактирование резюме. Вызов предполагается при помощи Github Action Request

**Comment by iriss22** [comment]
Добрый день. Возможно, но для этого нужно зарегистрировать приложение тут https://dev.hh.ru/admin
На счет того, получится то сделать через Github Action Request, подсказать не могу, не знаю что это.

**Comment by aliczin** [comment]
>  Github Action Request

@iriss22 у вас в репозитории именно оно используется https://github.com/hhru/api/blob/master/.github/workflows/main.yml#L14 - автоматически операции средствами Github
