### ISSUE TITLE
Не сохраняется разрешение пользователя на доступ к приложению

### ISSUE THREAD

**Issue by dmitrylaabe** [hhru/api#469]
Здравствуйте!

В документации сказано: Если пользователь авторизован на сайте и доступ данному приложению однажды ранее выдан, ответом будет сразу вышеописанный редирект с authorization_code (без показа формы логина и выдачи прав).

Многократно прохожу на разных устройствах первый этап (https://spb.hh.ru/oauth/authorize?response_type=code&client_id=XXX&redirect_uri=http://XXX), получаю окно с запросом подтверждения, подтверждаю доступ. Повторный запуск приводит к появлению этой формы снова.
В итоге не получается реализовать бездиалоговый доступ приложения к методам требующим авторизацию пользователя.

**Comment by iriss22** [comment]
добрый день!
При повторном входе Вам показывается какое окно: логина; подтверждения, что вы хотите зайти под текущим пользователем; выдачи прав?

**Comment by dmitrylaabe** [comment]
Использовать приложение ХХХ пользователем YYY. Кнопки Продолжить и Использовать другой профиль

**Comment by iriss22** [comment]
Это окно возникает всегда. От него нельзя избавиться. Поправим доку

**Comment by dmitrylaabe** [comment]
Понятно. Как тогда авторизоваться программно и в чем смысл api, если нужно отображать диалог, для корректной работы которого нужна еще и поддержка скриптов?
