### ISSUE TITLE
Невозможна автоматическая пользовательская авторизация

### ISSUE THREAD

**Issue by dmitrylaabe** [hhru/api#470]
Здравствуйте!
Проблема описана в Issue #469. Из ответа следует, что авторизация невозможна без прохождения страницы подтверждения прав, которая требует отображения и работы скриптов, что делает невозможным автоматическую пользовательскую авторизацию. 
Например, мне нужно написать внутренний сервис для фильтрации резюме по определенным критериям для наших сотрудников. Как это сделать с учетом такой специфики авторизации?

**Comment by iriss22** [comment]
Добрый день! 
Да, вы правы, на текущий момент нет возможности авторизовываться без участия пользователя.
Есть вариант авторизоваться 1 раз, сохранить токен и обновлять его раз в 2 недели (для обновления участия пользователя не требуется). Но такая схема иногда будет ломаться, например, если пользователь сменит пароль или токен будет отозван из-за подозрительной активности, придется авторизовываться вручную заново.
