### ISSUE TITLE
Нужна помощь с получением информации по резюме.

### ISSUE THREAD

**Issue by trofimov1988** [hhru/api#475]
Доброго времени суток, есть задача и проблема:
Задача:
Пользователь работая на сайте находит интересного кандидата, копирует его идентификатор резюме и используя АПИ добавляет его во внутреннюю систему для дальнейшей обработки.
Текущий результат:
Есть резюме, например: https://hh.ru/resume/b330ad2c000148f41d001d12aa5268466a6a6e идентификатор: b330ad2c000148f41d001d12aa5268466a6a6e, при запросе: https://api.hh.ru/resumes/b330ad2c000148f41d001d12aa5268466a6a6e отлуп: 
{
    "description": "Not Found",
    "errors": [
        {
            "type": "not_found"
        }
    ],
    "request_id": "1613779812495a915c74eb0b4bf54427"
}

Если я используя АПИ делаю поиск по резюме, то тот id который в результатах позволяет запросить информацию по резюме используя этот же запрос но с другим ID.
Предполагаю что идентификаторы резюме в выдаче по апи и на сайте отличаются. Есть ли способы решения моей проблемы?

**Comment by adanilkina** [comment]
Добрый день, прошу прощение за долгий ответ. 
Насколько могу видеть, вы запрашиваете резюме с токеном пользователя компании `employerId=3845543` ("Школа программирования Kodland"), а резюме `b330ad2c000148f41d001d12aa5268466a6a6e` было найдено менеджером другой компании. 
Вы можете выполнить поиск менеджером компании "Школа программирования Kodland" и затем выполнить запрос того же резюме через API, в таком случае проблем быть не должно.
