### ISSUE TITLE
Проблема с полем contacts при чтении вакансии

### ISSUE THREAD

**Issue by newissue** [hhru/api#476]
При чтении вакансии по идентификатору поле контакс всегда приходит пустое, даже если в вакансии оно заполнено.
Проверил около 10 вакансий везде пришло пустое.
Пример: 
http://api.hh.ru/vacancies/42488582

**Comment by adanilkina** [comment]
Добрый день!
Для безопасности наших пользователей, контакты более не доступны в анонимной части API.
Рекомендуем подать заявку на регистрацию приложения (https://dev.hh.ru/admin) и использовать авторизацию (https://github.com/hhru/api/blob/master/docs/authorization_for_application.md) на уровне приложения.
