### ISSUE TITLE
Пропал виджет вакансий

### ISSUE THREAD

**Issue by smkabsinelnikov** [hhru/api#490]
Здравствуйте. Вставляю код виджета на сайт на Битриксе, но виджет не отображается, почему?

<script class="hh-script" src="https://api.hh.ru/widgets/vacancies/employer?employer_id=1356527&locale=RU&links_color=1560b2&border_color=1560b2"></script>

https://smkab.online/company/vacancy/

**Comment by Ilyakonovalov** [comment]
Добрый день! 
Попробуйте отключить блокировку рекламы в браузере.
![image](https://user-images.githubusercontent.com/82891423/120990023-d05a7180-c788-11eb-8158-a1db5c9222ef.png)
С блокировщиком по типу Adblock действительно виджет не отображается.

**Comment by smkabsinelnikov** [comment]
Спасибо.
