### ISSUE TITLE
Неверные координаты у станции метро "Проспект Славы" в г. Санкт-Петербург

### ISSUE THREAD

**Issue by Zmoroz** [hhru/api#491]
API выдает координаты 59.2127, 30.2339 (это за пределами города). Правильные координаты 59.856704, 30.395402.

**Comment by Ilyakonovalov** [comment]
Добрый день.
Спасибо за замечание!
Координаты обновятся в ближайшее время (ориентировочно - вечером)

**Comment by adanilkina** [comment]
координаты поменяли 🚇
