### ISSUE TITLE
Добавить фильтр по industries в /employers

### ISSUE THREAD

**Issue by ilyalesik** [hhru/api#504]
Query параметр, с помощью которого можно будет ограничить выдачу только компаниями требуемой индустрии

Например: `/employers?industries=41.525` будет возвращать только Интернет магазины

Related: #285 (добавлено поле в ответ)

**Comment by adanilkina** [comment]
Добрый день, внесла в список обсуждаемых улучшений функционала api, обсудим с менеджером и командой ваше предложение :)

**Comment by ilyalesik** [comment]
Спасибо!
