### ISSUE TITLE
'status_code': 403, 'headers': {'Server': 'ddos-gua...':         '8213'},

### ISSUE THREAD

**Issue by tst32** [hhru/api#506]
помимо обязательных заголовков описанных в hhru/api endpoint https://hh.ru/oauth/token добавлял 
  "Content-Type": "text/html;charset=UTF-8" (также пробовал менять на "content-type": "application/json"  )  и "HH-User-Agent": "GITsyncCVonHH/0.1 

На любой реквест получаю от гварда 403. Я ддосю, да? Подскажите время когда  можно отправлять реквесты, и частоту. Или что-т еще не так отправляю?

**Comment by iriss22** [comment]
Добрый день! Подскажите, пожалуйста, когда именно вы выполняли этот запрос и, если можете, скажите, пожалуйста, адреса, с которых подключались

**Comment by iriss22** [comment]
Наша служба безопасности утверждает, что проблему решили вчера примерно в 18-30. Подскажите, пожалуйста, с 19-00 вчерашнего дня приходили ошибки?

**Comment by tst32** [comment]
Спс, все ОК сегодня  делал запрос на  /me res: 200 
 req: <PreparedRequest [GET]>, 

 `Got response from server: '{"auth_type":"application","is_applicant":false,"is_employer":false,"is_admin":false,"is_application":true}'
`
