### ISSUE TITLE
publish

### ISSUE THREAD

**Issue by 9vvk** [hhru/api#531]
Извините, не нашёл где уточнить
Такая конструкция не работает?
> curl -k -H 'Authorization: Bearer токен_приложения' -X PUT https://api.hh.ru/resumes/адрес_резюме/publish
> {"errors":[{"type":"method_not_allowed"}],"request_id":"16364965281202b4e36ced175ce1183e"}

**Comment by DanilKnyazev** [comment]
Здравствуйте. Для публикации резюме необходимо использовать метод POST:

> curl -k -H 'Authorization: Bearer токен_приложения' -X **POST** https://api.hh.ru/resumes/адрес_резюме/publish

**Comment by 9vvk** [comment]
{"description":"Unrecognized authorization","oauth_error":"token-revoked","errors":[{"value":"token_revoked","type":"oauth"}],"request_id":"163655183783867bb9cd3dcdd2283e01"}

**Comment by DanilKnyazev** [comment]
Вам нужно запросить новую авторизацию пользователя.

**Comment by 9vvk** [comment]
То есть тут должен быть не "токен приложения"?
Токен пользователя?

**Comment by 9vvk** [comment]
curl -k -H 'Authorization: Bearer **токен_пользователя**' -X POST https://api.hh.ru/resumes/адрес_резюме/publish
Понял наконец где ошибался, токен приложения пихал.
А как долго живёт токен_пользователя? После рефреша остаётся тот же?

**Comment by DanilKnyazev** [comment]
При получении access_token в ответе возвращается поле expires_in - со сроком жзни 14 дней на текущий момент. пара access_token и refresh_token меняют свои значения при обновлении.

**Comment by 9vvk** [comment]
спасибо
