### ISSUE TITLE
Не подтягиваются контакты работодателя

### ISSUE THREAD

**Issue by Vladimir155** [hhru/api#533]
Через API не подтягиваются контакты, хотя в вакансиях они указаны.

**Comment by Vladimir155** [comment]
> Здравствуйте. Для безопасности наших пользователей, контакты более не доступны в анонимной части API. Рекомендуем подать заявку на регистрацию приложения (https://dev.hh.ru/admin) и использовать авторизацию (https://github.com/hhru/api/blob/master/docs/authorization.md).

Спасибо, получилось!

Возник еще 1 вопрос: что за ограничения на просмотр лишь 2000 вакансий?
Я через API в т.ч. пытаюсь построить тренд по интересующим меня сферам, но из-за ограничения картина получается достаточно неполной.

Что необходимо сделать, чтоб выйти за рамки per_page=100&page=19?

**Comment by DanilKnyazev** [comment]
К сожалению, подобной возможности API не предоставляет. Указанное ограничение было введено из соображения скорости и стабильности работы данного функционала сайте. Могу посоветовать воспользоваться фильтрами поиска вакансий, такими как регион `GET /vacancies?area=1`

**Comment by Vladimir155** [comment]
> К сожалению, подобной возможности API не предоставляет. Указанное ограничение было введено из соображения скорости и стабильности работы данного функционала сайте. Могу посоветовать воспользоваться фильтрами поиска вакансий, такими как регион `GET /vacancies?area=1`

Печально, благодарю!
