### ISSUE TITLE
Не отображается ЗП (до) в виджете

### ISSUE THREAD

**Issue by kirill-trofimov** [hhru/api#540]
Здравствуйте. Используем ваш виджет вакансий на сайте https://job.intensa.ru. Всё хорошо, кроме отображения зарплаты. Показывается "от", но не показывается "до". При этом в вакансиях почти всегда мы указываем "до". Возможно это доработать? Спасибо.

**Comment by DanilKnyazev** [comment]
Здравствуйте. Мы постараемся решить этот вопрос. Спасибо за замечание! Всего Вам доброго.
