### ISSUE TITLE
Тестирование публикации вакансий

### ISSUE THREAD

**Issue by nostalgie** [hhru/api#55]
Добрый день, есть ли возможность как-то тестировать разработку публикации вакансии? Тестовый аккаунт или размещение тестовой вакансии?

**Comment by maizy** [comment]
Схоже по целям с #89

**Comment by andrey158** [comment]
Не совсем схоже.
#89 предназначено для продуктивного использования, а здесь речь о "песочнице", чтобы проверять свои разработки.

**Comment by maizy** [comment]
Да, я понимаю. С помощью #89 можно, в том числе проверить приложение на правильность передачи данных при публикации, не осуществляя после этого саму публикацию.

Задачи не объединяю, добавил ссылку скорее для информации.

**Comment by Afigan** [comment]
Добрый день, появился ли подобный функционал?

**Comment by maizy** [comment]
ещё пока нет

**Comment by Nyholm** [comment]
:+1:

**Comment by syabro** [comment]
Any news?

**Comment by maizy** [comment]
@syabro пока ничего нового по срокам сказать не можем.

**Comment by maizy** [comment]
+6 от различных клиентов

**Comment by maizy** [comment]
+1 от клиента

**Comment by barsuk** [comment]
+1 от клиента и +2 от нас, разработчиков.

**Comment by no-cat-no** [comment]
+1

**Comment by aleksandrzen** [comment]
+1

**Comment by morozovivan95** [comment]
+1

**Comment by PlusRT** [comment]
+1

**Comment by iriss22** [comment]
в ближайшее время не планируется
