### ISSUE TITLE
Unsupported grant type

### ISSUE THREAD

**Issue by xxxenobyte** [hhru/api#553]
При запросе `POST https://hh.ru/oauth/token`
с body:
```
{
    "code": "AUTH_CODE",
    "client_id": "CLIENT_ID",
    "client_secret": "CLIENT_SECRET",
    "grant_type": "authorization_code"
}
```
headers:
```
{
  'Content-Type': 'application/x-www-form-urlencoded'
}
```

в ответ приходит ошибка:
```
     data: {
       error: 'unsupported_grant_type',
       error_description: 'unsupported grant_type'
     }
```

что нужно прописать в `grant_type`? Запрос на получение временного `authorization_code` для получения `acess_token`, `refresh_token` отрабатывает удачно. В чем может быть еще затык?

**Comment by soa4work** [comment]
@xxxenobyte как решили проблему?
