### ISSUE TITLE
Ошибка при получении уведомлений об ответе или приглашении заказчика на вакансию

### ISSUE THREAD

**Issue by Alex345** [hhru/api#562]
Здравствуйте, разработчики!
У меня изначально был зарегистрирован аккаунт на украинском домене grc.ua, после того как я перебрался в Россию я сменил местоположение и думал что все на этом решилось, но почему-то в последнее время(раньше приходили приглашения и ссылка была на hh.ru) мне оповещение приходит от grc.ua. Причем я общался с работодателем, который прислал мне приглашение и он сказал, что у него нет вообще вакансий по Украине, т.е. вакансия заказчика была размещена в России, а мне ссылка на него приходит на grc.ua, мой почтовый ящик на яндексе - ale-wp345, думаю по базе найдете, заранее спасибо!

P.S.Один раз чуть не удалил приглашение, пожалуйста посмотрите данную ошибку.

**Comment by DanilKnyazev** [comment]
Здравствуйте!
В этом разделе мы решаем проблемы и отвечаем на вопросы, связанные с программными интеграциями с hh.ru сторонних разработчиков через API. Для решения Вашего вопроса обратитесь, пожалуйста, в [сообщество поддержки](https://feedback.hh.ru/). 
Спасибо за обращение и хорошего дня.

**Comment by Alex345** [comment]
Извините, спасибо за ответ!
