### ISSUE TITLE
💡 Добавить «Внутренний код вакансии работодателя» в поиск по вакансиям

### ISSUE THREAD

**Issue by griboder** [hhru/api#569]
Добавьте, пожалуйста, в поиск по вакансиям https://api.hh.ru/vacancies параметр, который позволяет получать `code` (Внутренний код вакансии работодателя), либо отображайте это поле по умолчанию.

Мы используем поле `code` для классификации вакансий по направлениям (frontend, backend, qa и пр.): https://selectel.ru/careers/all/. Его отсутствие в поиске по вакансиям вынуждает нас запрашивать данные каждой вакансии для формирования общего списка.

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Мы учтем Ваше пожелание. В свою очередь можем порекомендовать конструировать запросы следующим образом:
vacancies?employer_id={emploer_id}&[professional_roles](https://github.com/hhru/api/blob/master/docs/role_catalog_article.md)&text={[название_вакансии](https://github.com/hhru/api/blob/master/docs/suggests.md#%D0%BF%D0%BE%D0%B4%D1%81%D0%BA%D0%B0%D0%B7%D0%BA%D0%B8-%D0%BF%D0%BE-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8F%D0%BC)} 
также будет полезным использовать подсказки по:
- [профессиональным ролям](https://api.hh.ru/openapi/redoc#tag/Spravochniki/paths/~1suggests~1professional_roles/get)
- [профессиям](https://github.com/hhru/api/blob/master/docs/suggests.md#%D0%BF%D0%BE%D0%B4%D1%81%D0%BA%D0%B0%D0%B7%D0%BA%D0%B8-%D0%BF%D0%BE-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8F%D0%BC)
- [ключевым словам в поиске вакансий](https://github.com/hhru/api/blob/master/docs/suggests.md#%D0%BF%D0%BE%D0%B4%D1%81%D0%BA%D0%B0%D0%B7%D0%BA%D0%B8-%D0%BF%D0%BE-%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B2%D1%8B%D0%BC-%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC-%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B9)
- [язык поисковых запросов](https://sosensky.hh.ru/article/1175)
Например для группировки бекенд-разработчиков по региону Москва можно использовать запрос вида:
`https://api.hh.ru/vacancies?employer_id=633069&area=1&text='python OR java'&professional_role=96`
