### ISSUE TITLE
Конкурентный доступ к токену

### ISSUE THREAD

**Issue by jet-desk** [hhru/api#570]
Здравствуйте!
Тестируем API работодателя и в процессе сверяемся с данными в интерфейсе hh.ru, при этом каждый логин на сайт hh.ru сопровождается отзывом API токена.
Подскажите, пожалуйста, как с этим бороться? Просмотрел тут другие issue и не нашел подобного вопроса, так же в документации тоже нет на этот счет ничего. Замечу, что "протухает" токен не по периоду жизни, а именно при логине в интерфейсе hh.ru.
Спасибо.

**Comment by Kozin-br** [comment]
clear

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Не могли бы Вы, пожалуйста, уточнить какую [ошибку](https://github.com/hhru/api/blob/master/docs/errors.md#%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA-%D0%BF%D1%80%D0%B8-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B8%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B8-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%BE%D0%B2) из списка получаете и логин пользователя(как пример)?

**Comment by jet-desk** [comment]
{
  "message": "Client error: `GET https://api.hh.ru/me` resulted in a `403 Forbidden` response:\n{\"description\":\"Unrecognized authorization\",\"oauth_error\":\"token-revoked\",\"errors\":[{\"value\":\"token_revoked\",\"type\":\"oau (truncated...)\n"
}

**Comment by DanilKnyazev** [comment]
Подобная ошибка может происходить если пользователь входит в систему по паролю, который он запрашивает нажимая "Получить пароль". Не могли бы Вы прислать request_id? я смог посмотреть хронологию запросов и описать более точную причину.

**Comment by jet-desk** [comment]
простите, но я не понимаю где мне получить request_id моего запроса. не могли бы вы пояснить?
так же для лучшего понимания расскажу схему по которой мы работаем и в итоге получаем ошибку.
у нас есть серверное приложение, которое по api периодически (раз в N минут) получает данные о вакансиях и откликах. Так же есть пользователь (менеджер), который параллельно работает в web-интерфейсе hh.ru. Вот до тех пор пока менеджер в интерфейсе не перелогинивается (без получения нового пароля) - с api все хорошо. Если пользователь закрывает страницу, потом открывает и корректно логинится по-новой, то используемый в api access_token отзывается - мы получаем ошибку, которую я показал ранее.
Прошу помощи с данной ситуацией, т.к. в итоге мы не можем автоматизировать необходимые процессы и параллельно работать в интерфейсе.
Спасибо.

**Comment by DanilKnyazev** [comment]
Добрый день!
Пользователя разлогинивает, в том числе деактивируется токен, в случае одновременного использования сайта с разных устройств на протяжении некоторого времени. То есть открываются с разных устройств различные страницы сайта. Обычный переход с одного устройства на другое, например сидел за ноутом, пошел на собеседование - с айпада смотрит резюме - это не одновременное использование. Часто такое случается при одновременной работе с одного аккаунта нескольких человек/устройств. Как вариант для API и для сайта использовать разные аккаунты: учетку для автоматизации(с соответствующими правами), остальные для работы с web-интерфейсом.

**Comment by jet-desk** [comment]
спасибо!
