### ISSUE TITLE
Кастомные запросы для поиска резюме

### ISSUE THREAD

**Issue by Veinqt9** [hhru/api#572]
Добрый вечер, просмотрела существующую документацию, но не смогла найти ответ на свой вопрос:
В обычном hh.ru есть галочки для скрытия резюме просмотренных мною или кем-то из моей компании, реализован ли этот функционал в API?
Если да, то где можно почитать об этом подробнее:)
![image](https://user-images.githubusercontent.com/90092473/161787608-97d59179-fbf5-4054-bd30-08403c224615.png)

**Comment by DanilKnyazev** [comment]
Здравствуйте.
К сожалению, подобного фильтра нет. Но, возможно, Вам будет полезно использовать [сохраненные поиски резюме](https://github.com/hhru/api/blob/master/docs/resumes_saved_searches.md#resumes-saved-search-list), по которым есть возможность смотреть обновления. 
Также можно ориентироваться на поле viewed [при поиске](https://github.com/hhru/api/blob/master/docs/employer_resumes.md#%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%BF%D0%BE%D0%BB%D1%8F-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BE%D0%B4%D0%B0%D1%82%D0%B5%D0%BB%D1%8F).
