### ISSUE TITLE
Скрипт отображается под футером в Битрикс

### ISSUE THREAD

**Issue by YauheniShakau** [hhru/api#574]
Добрый день! Что я делаю не так? Скрипт добавил в файл index.html после текста

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35776796/162423955-6b2a75bd-c468-4092-9c81-58de369b8d0d.png">

**Comment by DanilKnyazev** [comment]
Здравствуйте. 
Здесь мы обсуждаем проблемы/вопросы, связанные с работой виджета. По поводу размещения виджета на страницах сайта рекомендую обратиться к производителю данной CRM.
