### ISSUE TITLE
ошибка 403 при вызове refresh_token(обновить токен с помощью refresh токена) через api

### ISSUE THREAD

**Issue by YuriyKor** [hhru/api#575]
работает ддос, мой айпи(динамический от провайдера - 195.133.31.79) прошу проверить

<!DOCTYPE html><html><head><title>DDOS-GUARD</title><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><script>var DOMReady=function(t){var e=document,d="addEventListener";e[d]?e[d]("DOMContentLoaded",t):window.attachEvent("onload",t)},loadScript=function(t,e){var d=document.createElement("script");d.type="text/javascript",d.src=t,"string"==typeof e&&""!==e&&(d.id=e),(document.getElementsByTagName("head")[0]||document.body).appendChild(d)};DOMReady(function(){loadScript("/.well-known/ddos-guard/check?context=free_splash","ddg_script_f"),loadScript("https://check.ddos-guard.net/check.js")});</script><style>*{margin:0;padding:0}body,html{font-family:Open Sans,Arial,Helvetica,sans-serif;height:100%;background:linear-gradient(to top,#e5f3fb,#fff)}.logo{width:120px;margin-bottom:35px}#title{font-size:32px;font-weight:900;margin-bottom:40px}#description{color:#8f9390;margin-bottom:30px}#link-ddg{white-space:nowrap;margin-bottom:30px;font-size:18px}#link-

**Comment by DanilKnyazev** [comment]
Здравствуйте. Не могли бы Вы, пожалуйста, предоставить http-логи содержащие информацию о заголовках, запрашиваемом адресе, коде ответа и временем запроса?
