### ISSUE TITLE
Проблема с обновлением токена

### ISSUE THREAD

**Issue by Shatoidil** [hhru/api#580]
Добрый день. 

у меня возникает проблема с обновлением токена у пользователя.

по истечению срока. я пропуб обновить токен

```
            var client = new RestClient("https://hh.ru/oauth/token");
            client.Timeout = -1;
            var request = new RestRequest(Method.POST);
            request.AddHeader("Content-Type", "application/x-www-form-urlencoded");

            request.AddParameter("refresh_token", refreshToken); <---- здесь передается токен для обновления
            request.AddParameter("grant_type", "refresh_token");
```

И кадый раз я получаю ошибку `"{\"error\": \"invalid_grant\", \"error_description\": \"token has already been refreshed\"}"`

Как будто токен уже обновлен. Ну он никак не мог быть обновлен. уже несколько раз проверил. Еще проблема, чтобы сделать эту процедуру небоходимо ждать 2 недели, пока токен протухнет. 

Помогите разобраться пожалуйста

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Указанная ошибка приходит только в случае попытки повторно использовать refresh_token. Необходимо убедиться, что при обновлении пары токенов, до этого не было повторных попыток обновления, возможно, логировать запросы и ответы от этого урла. Имеет смысл проверить, что авторизационными данными не могли воспользоваться посторонние. В случае утери пары токенов при обновлении, можно получить авторизацию пользователя заново. Если у Вас имеются логи с получением этой пары токенов(рефреш из которой Вы пытаетесь использовать) и получением ошибок при запросе обновления можете направить их на почту api@hh.ru
