### ISSUE TITLE
Есть ли возможность в теле ответа также получить professional_roles при поиске /vacancies и/или /employers/{employer_id}/vacancies/active?

### ISSUE THREAD

**Issue by WartVader** [hhru/api#590]
На данный момент при попытке вывести полный список вакансий у компании, в теле ответа нету поля` professional_roles`, на сколько я понимаю оно есть только когда идет поиск по определенной вакансии (`/vacancies/{vacancy_id}`)

**Comment by DanilKnyazev** [comment]
Здравствуйте. 
Действительно на данный момент в API поле professional_roles доступно только при получении конкретной вакансии. 
Но есть возможность воспользоваться [кластерами вакансий](https://github.com/hhru/api/blob/master/docs/clusters.md), чтобы просматривать профессиональные роли в опубликованных вакансиях компании. Например:
https://api.hh.ru/vacancies?clusters=true&employer_id=1455
