### ISSUE TITLE
Несовпадение данных получаемых через API и мобильное приложение

### ISSUE THREAD

**Issue by Sa6a** [hhru/api#599]
Данные по количеству откликнувшихся на вакансию (counters.responses), получаемые через API, и количество откликнувшихся, указанных в кнопке "Откликнуться" в приложении hh на андроид, - не совпадают.  Это разные счетчики? В чем причина?

**Comment by DanilKnyazev** [comment]
> Данные по количеству откликнувшихся на вакансию (counters.responses), получаемые через API, и количество откликнувшихся, указанных в кнопке "Откликнуться" в приложении hh на андроид, - не совпадают. Это разные счетчики? В чем причина?

Здравствуйте.
Не могли бы Вы, пожалуйста, прислать примеры того, как это выглядит?

**Comment by Sa6a** [comment]
> > Данные по количеству откликнувшихся на вакансию (counters.responses), получаемые через API, и количество откликнувшихся, указанных в кнопке "Откликнуться" в приложении hh на андроид, - не совпадают. Это разные счетчики? В чем причина?
> 
> Здравствуйте. Не могли бы Вы, пожалуйста, прислать примеры того, как это выглядит?

Вот пример вакансии https://hh.ru/vacancy/55544528 - через API количество откликнувшихся на вакансию (counters.responses) = 0, а согласно мобильному приложению - 46.

через API отдается:
{'accept_temporary': False,
  'address': {'building': None,
   'city': None,
   'description': None,
   'id': '354198',
   'lat': None,
   'lng': None,
   'metro': None,
   'metro_stations': [],
   'raw': 'Москва, ул. Гиляровского, 47/5',
   'street': None},
  'adv_response_url': 'https://api.hh.ru/vacancies/55544528/adv_response?host=hh.ru',
  'alternate_url': 'https://hh.ru/vacancy/55544528',
  'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=55544528',
  'archived': False,
  'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'},
  'contacts': None,
  'counters': {'responses': 0},
  'created_at': '2022-06-15T12:46:42+0300',
  'department': None,
  'employer': {'alternate_url': 'https://hh.ru/employer/3280',
   'id': '3280',
   'logo_urls': {'240': 'https://hhcdn.ru/employer-logo/1827307.jpeg',
    '90': 'https://hhcdn.ru/employer-logo/1827306.jpeg',
    'original': 'https://hhcdn.ru/employer-logo-original/346260.jpg'},
   'name': 'ТехноНИКОЛЬ',
   'trusted': True,
   'url': 'https://api.hh.ru/employers/3280',
   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=3280'},
  'has_test': False,
  'id': '55544528',
  'insider_interview': None,
  'name': 'Senior Разработчик EDWH Python SQL',
  'premium': False,
  'published_at': '2022-06-15T12:46:42+0300',
  'relations': [],
  'response_letter_required': True,
  'response_url': None,
  'salary': None,
  'schedule': {'id': 'fullDay', 'name': 'Полный день'},
  'snippet': {'requirement': '<highlighttext>Python</highlighttext> (уверенное знание языка и библиотек <highlighttext>Python</highlighttext>). Flask (приветствуется Django / Pyramid / Tornado). AsyncIO. Приветствуется Docker  Docker-compose. Приветствуется Unit и...',
   'responsibility': 'Проектирование и разработка Корпоративного хранилища данных (EDWH) «ТехноНиколь». Проектирование и разработка Технологических компонентов EDWH (Система управления метаданными; Система извлечения, трансформации...'},
  'sort_point_distance': None,
  'type': {'id': 'open', 'name': 'Открытая'},
  'url': 'https://api.hh.ru/vacancies/55544528?host=hh.ru',
  'working_days': [],
  'working_time_intervals': [],
  'working_time_modes': []}
![photo_2022-06-21_11-06-30](https://user-images.githubusercontent.com/38852061/174749572-379ddf61-85f9-4dca-af51-13661db4e7c6.jpg)
,

**Comment by DanilKnyazev** [comment]
Здравствуйте. 
Нашел эту публикацию через мобильное приложение, количество откликнувшихся по указанной вакансии не отображается сейчас, что совпадает со значением counters.responses = 0. Это значение отображает количество откликнувшихся с момента последнего обновления публикации. В случае этой публикации было обновлено значение опыта работы 16.06.22. Если у Вас есть замечания по работе мобильного приложения, рекомендуем обратиться в техническую поддержку.
