### ISSUE TITLE
обновление токенов не работает корректно

### ISSUE THREAD

**Issue by BAKAWAKALAKA** [hhru/api#619]
тестирую обновление токенов 
1) обновленная сегодня пара токенов 
делаю запрос https://hh.ru/oauth/token
ожидая получить в теле ошибке в описании token not expired
получаю token deactivated
2) пытаюсь обновить токен с истекшим временем, пользователь не авторизовывался до этого
делаю запрос https://hh.ru/oauth/token
получаю ошибку token deactivated

**Comment by DanilKnyazev** [comment]
Здравствуйте. token_deactivated возвращается, когда пользователь сменил пароль. Не могли бы Вы прислать, пожалуйста, request_id (возвращается в теле ответа ошибки или в http-заголовке X-Request-Id)

**Comment by BAKAWAKALAKA** [comment]
@DanilKnyazev 
X-Request-Id - 1661348108406d8bb5e5e3ef73bba597
