### ISSUE TITLE
Позиции в experience в ответе /resumes

### ISSUE THREAD

**Issue by vetka925** [hhru/api#626]
Здравствуйте.
Скажите, пожалуйста, почему при поиске можно получить только последнюю позицию в опыте резюме?

На сайте при поиске доступны все позиции из опыта.

Есть ли возможность добавить в API все позиции в опыте при поиске резюме?

**Comment by DanilKnyazev** [comment]
Здравствуйте.
В документации есть пример по составлению поискового запроса резюме:
`GET /resumes?text=Headhunter&text.logic=all&text.field=experience&text.period=last_three_years` – найдет все резюме, в опыте работы которых за последние 3 года встречается 'Headhunter'.
в этом примере text.field=experience - поле по которому производится поиск
text.period = last_three_years - промежуток за который необходимо показать совпадения
значения text.period и text.field можно обнаружить в [справочнике](https://github.com/hhru/api/blob/master/docs/dictionaries.md)
чтобы посмотреть опыт работы за все время, можно изменить запрос выше следующим образом:
`GET /resumes?text=Headhunter&text.logic=all&text.field=experience&text.period=all_time` - найдет все резюме, в опыте работы которых за все время встречается 'Headhunter'.

**Comment by vetka925** [comment]
Мой вопрос был о конкретном поле "position". Например, я хочу найти резюме АНАЛИТИКА, который занимал позицию АНАЛИТИКА не просто один раз за последние 3 года, 1 год, все время, в все 3 года, либо все 6 лет и т.п. Средствами поискового запроса это сделать не возможно.

Есть ли возможность добавить в API все позиции в опыте при поиске резюме?

**Comment by DanilKnyazev** [comment]
есть [поле experience](https://github.com/hhru/api/blame/master/docs/resumes_search.md#L73) со значениями из справочника [/dictionaries](https://api.hh.ru/dictionaries) массив с доступными значениями в массиве experience:
```
"experience": [
    {
      "id": "noExperience",
      "name": "Нет опыта"
    },
    {
      "id": "between1And3",
      "name": "От 1 года до 3 лет"
    },
    {
      "id": "between3And6",
      "name": "От 3 до 6 лет"
    },
    {
      "id": "moreThan6",
      "name": "Более 6 лет"
    }
  ],
```

**Comment by vetka925** [comment]
Еще раз.
**Что я хочу узнать?** Есть ли возможность добавить все позиции в опыте из резюме ?

**Подробнее**
Вот [здесь](https://github.com/hhru/api/blob/master/docs/resumes_search.md) есть пример ответа. Нас интересует вот этот кусочек.

`"experience": [
                {
                    "position": "пастух",
                    "start": "2010-01-01",
                    "end": null,
                    "company": "Рога и копыта",
                    "industries": [
                        {
                            "id": "51.643",
                            "name": "Благоустройство и уборка территорий и зданий"
                        },
                        {
                            "id": "29.503",
                            "name": "Земледелие, растениеводство, животноводство"
                        }
                    ],
                    "company_url": "http://example.com/",
                    "area": {
                        "id": "1",
                        "name": "Москва",
                        "url": "https://api.hh.ru/areas/1"
                    },
                    "company_id": null,
                    "employer": null
                },
                {
                    "start": "2005-01-01",
                    "end": "2009-03-01",
                    "company": "HeadHunter",
                    "area": {
                        "id": "1",
                        "name": "Москва",
                        "url": "https://api.hh.ru/areas/1"
                    },
                    "industries": [
                        {
                            "id": "7.513",
                            "name": "Интернет-компания (поисковики, платежные системы, соц.сети, информационно-познавательные и развлекательные ресурсы, продвижение сайтов и прочее)"
                        }
                    ],
                    "company_url": "http://hh.ru",
                    "company_id": "1455",
                    "employer": {
                        "alternate_url": "http://hh.ru/employer/1455",
                        "id": "1455",
                        "logo_urls": {
                            "90": "http://hh.ru/employer/logo/1455"
                        },
                        "name": "HeadHunter",
                        "url": "https://api.hh.ru/employers/1455"
                    }
                }
            ]`

Здесь доступна только последняя позиция в опыте.

**Чем мотивировано желание получать все позиции в опыте?** 
Такая возможность необходима для поиска кандидатов с релевантным опытом. НАПРИМЕР, я хочу найти резюме АНАЛИТИКА, который работал АНАЛИТИКОМ 3 года. 
Такой запрос 
`https://api.hh.ru/resumes?text=аналитик&text.logic=all&text.field=experience_position&text.period=last_three_years&text=аналитик&text.logic=all&text.field=title&text.period=all_time&experience=between3And6` 
Вернет резюме АНАЛИТИКов, у которых общий стаж от 3 до 6 лет, а АНАЛИТИКом соискатель мог поработать только месяц на последнем месте работы, а до этого работал кем угодно, кроме аналитика.

**Альтернативные варианты решения проблемы поиска кандидатов с конкретным опытом.**
Возможно вы знаете вариант решения этой проблемы использованием инструментов поиска? Было бы здорово, если Вы поделитесь такой информацией.

**Замечания**
Используя поиск резюме в браузере, есть возможность просмотреть все позиции в опыте, не переходя на страницу с конкретным резюме. Мне показалось странным, что нет такой функции в API.

**Comment by DanilKnyazev** [comment]
> Такая возможность необходима для поиска кандидатов с релевантным опытом. НАПРИМЕР, я хочу найти резюме АНАЛИТИКА, который работал АНАЛИТИКОМ 3 года.
Такой запрос
https://api.hh.ru/resumes?text=аналитик&text.logic=all&text.field=experience_position&text.period=last_three_years&text=аналитик&text.logic=all&text.field=title&text.period=all_time&experience=between3And6
Вернет резюме АНАЛИТИКов, у которых общий стаж от 3 до 6 лет, а АНАЛИТИКом соискатель мог поработать только месяц на последнем месте работы, а до этого работал кем угодно, кроме аналитика.

Такой запрос вернет резюме с опытом аналитика за последние 3 года, также в выдаче будут резюме с таким опытом за все время, также в выдаче будут резюме с опытом от 3 до 6. Чтобы найти резюме с опытом работы АНАЛИТИК 3 года можно ограничиться параметром experience=between3And6 и text=аналитик. Либо в Ваш запрос добавить тип сортировки order_by=relevance Если я Вас неправильно понял, не могли бы Вы прислать url-адрес со страницы hh.ru поиска резюме?
