### ISSUE TITLE
Сократить время публикации вакансии с помощью API

### ISSUE THREAD

**Issue by xenos18** [hhru/api#636]
Вакансия с помощью API публикуется 5-10 минут. Просьба ускорить время публикации до секунд, это критично для развития сервисов ваших клиентов)

**Comment by DanilKnyazev** [comment]
Здравствуйте. 
Не могли бы Вы, пожалуйста, предоставить значение http-заголовка X-Request-Id подобного запроса?

**Comment by xenos18** [comment]
Даниил, добрый день!

Запрос проверили, он отрабатывает быстро, спасибо. Подскажите, почему
превью вакансии в поисковой выдаче может в течение 5-10 минут показываться
по старому описанию вакансии (хотя новое уже загружено), и обновляется так
долго?

чт, 22 сент. 2022 г. в 14:30, Daniil Knyazev ***@***.***>:

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Не могли бы Вы предоставить для примера id вакансии, пожалуйста?

**Comment by xenos18** [comment]
Доброе утро!
Например эти:
69934791
67221052
69496888
68155287

Но вообще задержка есть по всем вакансиям, которые публикуются компанией
BIOCAD

вт, 27 сент. 2022 г. в 18:35, Daniil Knyazev ***@***.***>:

**Comment by DanilKnyazev** [comment]
Здравствуйте.
К сожалению, не удается воспроизвести ошибку. Не могли бы Вы, пожалуйста, прислать скриншот поисковой выдачи, значение X-Request-Id заголовка запроса и идентификатор вакансии, которая была изменена.

**Comment by xenos18** [comment]
Добрый день!

Воспроизвести задержку можно с помощью следующих действий:
1. Опубликовать вакансию на сайте (версия 1).
2. Редактировать описание вакансии с помощью API (версия 2). Меняем
требуемый опыт работы до 6 лет.
3. Найти вакансию через поиск hh. Прочитать превью, увидеть что оно
сформировано на основании версии 1, хотя при переходе открывается версия 2.

Скриншоты доступны по ссылке:

https://drive.google.com/file/d/1iBoMXIm8wteTqoHgP9w5yGkbol2rrrT1/view?usp=sharing

Старое описание превью (в поисковой выдаче) обновляется, в среднем, за 5-10
минут. Но эти 5-10 минут висит неактуальное превью. Вопрос, можно ли
сделать это обновление моментальным?

пт, 30 сент. 2022 г. в 18:33, Daniil Knyazev ***@***.***>:

**Comment by xenos18** [comment]
Добрый день!

1. да, так же.
2. проверим, напишу по результатам. Но, кажется, это не решит проблему с
попытками выгрузить превью с помощью API?

ср, 5 окт. 2022 г. в 10:55, Daniil Knyazev ***@***.***>:

**Comment by xenos18** [comment]
Даниил, доброе утро!

Потестировали выгрузку превью с помощью API c почищенным кэшем и кукисами.
Результат тот же, есть задержка обновления превью в поисковой выдаче.
Скриншоты прикладываю.
чт, 6 окт. 2022 г. в 17:56, Daniil Knyazev ***@***.***>:

**Comment by DanilKnyazev** [comment]
Здравствуйте. 
Время обновления полей [snippet](https://github.com/hhru/api/blob/master/docs/vacancies.md#%D0%BE%D1%82%D0%B2%D0%B5%D1%82-1) в поисковой выдаче вакансий составляет 3-5 минут. Не могли бы Вы, пожалуйста, прокомментировать, как это влияет на качество подбора с Вашей стороны?

**Comment by xenos18** [comment]
Добрый день, Даниил!

Мы разрабатываем инструмент для оценки качества подбора. И формирование
превью вакансий с помощью API  - важный элемент приложения, нам часто
приходится отправлять запрос на поиск превью для новых вариантов вакансий.
Это значительно тормозит работу приложения, поскольку превью
формируются недетерминированными правилами, и каждый такой запрос занимает
от 5 до 10 минут у наших и ваших пользователей.
Подскажите, пожалуйста, можно ли обновление превью ускорить с вашей стороны?
ср, 12 окт. 2022 г. в 15:02, Daniil Knyazev ***@***.***>:

**Comment by xenos18** [comment]
Даниил, добрый день!

Не очень поняла вопрос. Если нужна частота обновления вакансий и превью,
то, например, перед публикацией одной вакансии мы можем 5-10 раз подряд
обновлять описание и смотреть, как обновления влияют на превью. В идеале
это могло бы занимать 1-5 минут, но сейчас уходит до 1 часа в связи с
задержками обновления превью.

вт, 22 нояб. 2022 г. в 11:15, Daniil Knyazev ***@***.***>:
