### ISSUE TITLE
Параметр professional_role дублируется в доке вакансий

### ISSUE THREAD

**Issue by KirStepankov** [hhru/api#645]
Параметр professional_role дублируется в доке https://github.com/hhru/api/blob/master/docs/vacancies.md#%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%BF%D0%BE-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8F%D0%BC

**Comment by tpasichnik** [comment]
Добрый день.

Спасибо за информацию, ошибку поправили.
