### ISSUE TITLE
Дублирующиеся субъекты

### ISSUE THREAD

**Issue by Mikort** [hhru/api#659]
По запросу https://api.hh.ru/areas в ответе присутствуют несколько повторяющихся субъектов:

Название: Пушкинские Горы
area ids: 4032, 3728

Название: Шабровский
area ids: 4783, 5772

Название: Красные Баррикады
area ids: 5173, 4594

Название: Александровка
area ids: 4246, 4565

Из-за этого некоторые API могут не работать, т.к. по названию требуется конкретный area (например тут: https://github.com/Aleks-Ya/hh-java-api)

**Comment by tpasichnik** [comment]
Добрый день. 

Дубли из регионов "Пушкинские Горы", "Шабровский", "Красные Баррикады" удалены.
Несколько регионов - "Александровка" в справочнике регионов - это разные регионы, они относятся к разным областям (родительским регионам).
