### ISSUE TITLE
Добавить initial_created_at в методе /employers/{employer_id}/vacancies/active

### ISSUE THREAD

**Issue by Ynome-Meva** [hhru/api#665]
Просьба добавить поле initial_created_at, которое присутствует в методе GET /vacancies/{vacancy_id} в сопутствующий метод GET /employers/{employer_id}/vacancies/active
https://github.com/hhru/api/blob/master/docs/employer_vacancies.md#active

Спасибо.

**Comment by Ynome-Meva** [comment]
В противном случае на 150 вакансий придется дернуть лишний раз 150 однотипных запросов, ради одного поля...

**Comment by tpasichnik** [comment]
Добрый день.

Спасибо за обратную связь. Ваше пожелание передал в отдел разработки.
