### ISSUE TITLE
professional_role доступно к просмотру только для по запросу на конкретную вакансию

### ISSUE THREAD

**Issue by Konstantin9658** [hhru/api#672]
Добрый день, могли бы добавить поле `professional_role` не только по запросу на конкретную вакансию, но и в полный список доступных вакансий?
https://github.com/hhru/api/blob/master/docs/vacancies.md#%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%BF%D0%BE-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8F%D0%BC в документации почему то оно присутствует, но по факту не приходят

**Comment by Konstantin9658** [comment]
![image](https://user-images.githubusercontent.com/76180339/203751247-3a0ead33-2dfa-4f5f-bdbc-11b7c7299f94.png)

**Comment by Konstantin9658** [comment]
![image](https://user-images.githubusercontent.com/76180339/203751846-1e15d5b6-44df-416b-8792-bb359451fb3d.png)

**Comment by tpasichnik** [comment]
Добрый день.

Атрибут professional_roles указан в документации в качестве возможного query-параметра, который можно использовать в [запросе](https://github.com/hhru/api/blob/master/docs/vacancies.md#%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81) вакансий, а также в примере ответа в [запросе](https://github.com/hhru/api/blob/master/docs/vacancies.md#%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B8) на просмотр определенной вакансии.

Ваше пожелание по отображению атрибута `professional_roles` в методе `GET /vacancies` будет учтено.

**Comment by Konstantin9658** [comment]
Спасибо!
