### ISSUE TITLE
Проблема с авторизацией

### ISSUE THREAD

**Issue by nostalgie** [hhru/api#70]
В случае, если аккаунт на jobs.tut.by - авторизация через m.hh.ru не проходит (указывает, что неверный логин/пароль, тоже самое выдает на самом hh.ru).
Но если пользователь авторизировался на jobs.tut.by - то всё отрабатывает как надо.
С этим возможно что-то сделать?

**Comment by dirael** [comment]
логин давно выслала, дублирую здесь: makira@tut.by

**Comment by mikesub** [comment]
К сожалению, на данный момент мы не поддерживаем авторизацию jobs.tut.by в api, только hh.ru. У нас есть в планах добавить такую возможность, но по срокам пока соориентировать не можем.
