### ISSUE TITLE
В краткой форме резюме для поля actions отсутствует поле get_with_contact

### ISSUE THREAD

**Issue by BAKAWAKALAKA** [hhru/api#706]
x-request-id = 167836252281467962566ed8be540a4d

Запрос отправляется через токен приложения менеджера. Запрос на поиск резюме с параметрам.  В ответе приходит список но в каждом резюме отсутствует поле get_with_contact в поле actions. 7 марта поле присутствовало в краткой форме.

**Comment by DanilKnyazev** [comment]
Здравствуйте. 
Прошу прощения за долгий ответ.
У менеджера, от которого запрашивался поисковый запрос резюме, не было квот на просмотр контактов. С 9 марта квота поплнена менеджером с правами администратора. Если у вас остались вопросы - рекомендуем обратиться на почту api@hh.ru, т.к. некоторые сведения о менеджерах и соискателях могут носить конфиденциальный характер. Репозиторий в github является публичным. Спасибо за обращение!
