### ISSUE TITLE
Пропала возможность фильтрации по специализации при поиске вакансий

### ISSUE THREAD

**Issue by a98e36** [hhru/api#707]
Добрый день! Куда пропала возможность фильтрации по специализации (specialization) при поиске вакансий? Пару недель назад такая возможность была. Информацию об урезании фильтра по специализациям я не нашел.

Запрос [https://api.hh.ru/vacancies?area=1&specialization=1](https://api.hh.ru/vacancies?area=1&specialization=1) вернет информацию о том, что найдено ~182122 вакансий, точно такой же результат вернет и [https://api.hh.ru/vacancies?area=1](https://api.hh.ru/vacancies?area=1).

**Comment by DanilKnyazev** [comment]
Здравствуйте. 
Спасибо за обращение!
Согласно https://github.com/hhru/api/blob/master/docs/role_catalog_article.md мы убрали поддержку старого каталога специализаций. О своем решении мы неоднократно предупреждали владельцев приложений по почте. Если в вашем личном кабинете есть хотя бы одно зарегистрированное приложение, то должно быть письмо с оповещением. На данный момент рекомендуем использовать значения из нового каталога профессиональных ролей - https://api.hh.ru/professional_roles
