### ISSUE TITLE
Нельзя однозначно соотнести категорию профессиональной роли у вакансии

### ISSUE THREAD

**Issue by MuR** [hhru/api#716]
https://api.hh.ru/professional_roles

Профессиональная роль у вакансии может относится к нескольким категориям, например:

`"id": "107", "name": "Руководитель проектов"`

Расположена в категориях:

```
"id": "11", "name": "Информационные технологии"
"id": "18", "name": "Строительство, недвижимость"
"id": "4", "name": "Стратегия, инвестиции, консалтинг"
```
с одинаковым `id: 107`

Аналогично для роли:

`"id": "10", "name": "Аналитик"`

```
"id": "11", "name": "Информационные технологии"
"id": "1", "name": "Продажи, обслуживание клиентов"
"id": "4", "name": "Стратегия, инвестиции, консалтинг"
```

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Проф. области используются для **группировки** профролей в справочнике /professional_roles для удобства выбора. В запросах API проф. области не используются.
