### ISSUE TITLE
Ошибка при запросе с кириллицей

### ISSUE THREAD

**Issue by evgeniiegorov** [hhru/api#72]
curl --header "Authorization: Bearer <токен>" https://api.hh.ru/resumes?text=programm       -- успешно,
curl --header "Authorization: Bearer <токен>" https://api.hh.ru/resumes?text=911                  -- успешно

curl --header "Authorization: Bearer <токен>" https://api.hh.ru/resumes?text=программист   -- провал:            

400 Bad request
Your browser sent an invalid request.

**Comment by mikesub** [comment]
Добрый день,
проблема в том, что вы передаёте некорректные символы в URL:

> URLs can only be sent over the Internet using the ASCII character-set. Since URLs often contain characters outside the ASCII set, the URL has to be converted into a valid ASCII format. URL encoding replaces unsafe ASCII characters with a "%" followed by two hexadecimal digits...

**Comment by evgeniiegorov** [comment]
Да, спасибо, я разобрался
