### ISSUE TITLE
https://github.com/konstantinkuchuk/test_job.git

### ISSUE THREAD

**Issue by konstantinkuchuk** [hhru/api#727]
не совсем разобрался с древовидным меню, вернее у меня не устанавливался пакет mptt
https://github.com/konstantinkuchuk/test_job.git

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Объясните, пожалуйста, как это связано с документацией API HH?

**Comment by mediaexplorer74** [comment]
> Здравствуйте. Объясните, пожалуйста, как это связано с документацией API HH?

А где именно указано, что "https://github.com/hhru/api" - репозитарий про ДОКУМУНТАЦИЮ? Как переводится слово "api"? В АПИ инженеры вкладывают другой смысл. У вас же Readme черти как оформлен, про библиотеки на Pythin / C# / RUST / JS ни хрена ничего нет! [DanilKnyazev](https://github.com/DanilKnyazev), нелепый человек соврешенно. Еще пару таких фраз, и будет жалоба на GitHub, чтобы забанили к черту за уродство такое!!!

**Comment by mediaexplorer74** [comment]
> не совсем разобрался с древовидным меню, вернее у меня не устанавливался пакет mptt https://github.com/konstantinkuchuk/test_job.git

Привет. Это Вы разрабом в HH надумали тродоустроиться, что ли? Ну удачи...
