### ISSUE TITLE
Отказы на отклики и сообщения в откликах

### ISSUE THREAD

**Issue by caxopog** [hhru/api#73]
Добрый день

Я правильно понимаю, что на данный момент нельзя отказывать соискателям или писать сообщения в откликах через API?

Если нельзя, то когда ориентировочно планируете внедрить эту возможность?

Спасибо.

**Comment by mikesub** [comment]
Добрый день,

верно, сервис откликов/приглашений на данный момент реализован только со стороны соискателя. Часть для работодателей сейчас в работе, планируем выпустить через пару месяцев.

**Comment by CGSfera** [comment]
Добрый день,

подскажите, пожалуйста, в какой стадии находится функционал отказов\приглашений на отклики для работодателей? Очень ждем!

**Comment by maizy** [comment]
Добрый день.

Выпустили пока только получение откликов/приглашений, в данный момент готовится документация, но есть предварительная версия тут - #88 

Сроков появления действий по откликами приглашения пока точно назвать не могу.

**Comment by maizy** [comment]
Создал два отдельный issue на разные части данной фукнциональности, подпишитесь, если хотите получать уведомления о статусе разработки:
- #95 - Действия по откликам и приглашениям для работодателя
- #96 - Отправка приглашения на вакансию работодателем

Скорее всего возможности будут появляться в указанном порядке.
Возможно, в вашем случае хватит первой.
