### ISSUE TITLE
Есть ли ограничения на число запросов к API hh.ru?

### ISSUE THREAD

**Issue by xBBCoder** [hhru/api#74]
Собственно, сабж. Например, к superjob.ru можно делать 120 запросов в минуту. По hh.ru такую информацию не нашел.

**Comment by mikesub** [comment]
Да, ограничение по кол-ву запросов у нас есть. Мы считаем кол-во запросов с одного IP в секунду. При превышении выдаётся ответ с HTTP-кодом 429 (too many requests). В данный момент лимиты настроены таким образом, что при использовании API в известных нам случаях лимит достигнут довольно сложно. Это число может изменяться и завязываться на конкретные цифры некорректно. Сейчас это около 10 req/sec/ip. В любом случае, если вы столкнулись с лимитом (либо вы делаете лишние запросы и те же данные можно получить более оптимальным путём (меньшим кол-вом запросов), либо у вас действительно высока нагрузка) — пишите нам на api@hh.ru, рассмотрим конкретную ситуацию и найдем решение.

**Comment by xBBCoder** [comment]
Спасибо за ответ

**Comment by CGSfera** [comment]
Добрый день! У нас есть приложение, получающее отклики на вакансию работодателя и загружающее полное резюме по ключу из каждого отклика. Дело в том, что вакансий у компании 900 штук, при проходе по всем вакансиям часть запросов возвращает резюме корректно,а после этого некоторого количества успешных запросов появляется 429 ошибка. Вот пример 

GET https://api.hh.ru/resumes/7a8cc01900018221b50003b32a7a654b6c4b68 

ответ
 
XMLHttpRequest cannot load https://api.hh.ru/resumes/7a8cc01900018221b50003b32a7a654b6c4b68. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://kl:1126' is therefore not allowed access. The response had HTTP status code 429.

Кажется, будто проблема действительно в количестве запросов. Подскажите, что делать.

**Comment by maizy** [comment]
У нас есть есть несколько ограничений:

1. Техническое ограничение - ~30 запросов к api в секунду, если вы превысили этот лимит необходимо снизить скорость работы с api (добавить задержки).

2. Лимит на 500 просмотров резюме на каждого пользователя в сутки. Если вы превысили этот лимит, вероятно вы пытаетесь загрузить все отклики от лица одного менеджера. Считается, что человек не в состоянии обработать за сутки более 500 резюме. 

Если вы превысили этот лимит, вам необходимо сделать, чтобы отклики загружались от лица разных менеджеров. Наиболее простой вариант брать ответственного за вакансию менеджера. В вашей системе уже может присутствовать связка менеджера и вакансии, но если нет, это можно узнать и из API. См. поле manager в полях вакансии - https://github.com/hhru/api/blob/master/docs/vacancies.md#Дополнительные-поля-вакансии.

Также могут пригодится эти ресурсы api:
* справочник менеджеров работодателя - https://github.com/hhru/api/blob/master/docs/employer_managers.md
* список активных вакансий менеджера - https://github.com/hhru/api/blob/master/docs/employer_vacancies.md#active

3. Лимит на количество просмотров резюме в сутки на всю компанию. Значение отличается для разных компаний, обычно несколько тысяч. При нормальном использовании данный лимит редко достигается.

**Comment by artembeloglazov** [comment]
Здравствуйте, насколько актуальна информация, которая здесь представлена?

**Comment by iriss22** [comment]
добрый день, актуальна

**Comment by emil-ufa** [comment]
Добрый день! Хочу уточнить:
1) Есть аккаунт менеджера и 1 резюме. За день смотрим это резюме под этим аккаунтом 2 раза. Это считается как один просмотр резюме из доступных 500 на аккаунт, или как два?
2) Как (1), только есть 2 аккаунта менеджеров одной компании. И смотрим одно и тоже резюме с каждого аккаунта по 1 разу. Это считается как один просмотр резюме из доступных 8000 на компанию, или как два?

**Comment by shurik2533** [comment]
1. Если смотреть резюме за день под одним аккаунтом более одного раза, то это считается за один просмотр
2. Если смотреть резюме разными аккаунтами одного работодателя, то счетчик доступных для компании просмотров увеличивается
3. Правила обратотки счетчиков просмотра резюме для сайта и API одинаковы

**Comment by Razvie-arr** [comment]
Добрый день, актуально ли до сих пор информация, приведенная выше?

**Comment by adanilkina** [comment]
Добрый день, информация актуальна.

**Comment by etovityusha** [comment]
Здравствуйте. А сейчас актуально?

**Comment by adanilkina** [comment]
Добрый день, на сегодняшнй день rps с одного ip не должен привышать 7, в остальном по лимитам изменений не было

**Comment by mikeasta** [comment]
Здравствуйте!
На данный момент какие ограничения наложены на:
1) Количество выгружаемых подробных резюме в день на 1 менеджера?
2) Максимальный rpm (или rps) по загрузке подробных резюме?
Спасибо!

**Comment by HotDog1112** [comment]
Добрый день! Данный лимит для работодателя актуален, если есть платный доступ к резюме и другим модулям API ?

**Comment by mobiden** [comment]
Добрый день! Можете обновить информацию по лимитам на скачивание анонимных резюме?
