### ISSUE TITLE
"type":"bad_request" при GET запросе

### ISSUE THREAD

**Issue by StickKing** [hhru/api#751]
Добрый день!

С помощью python произвожу выгрузку вакансий (через **GET** запрос на адрес _https://api.hh.ru/vacancies_).
При использовании синхронного подхода с библиотекой **requests** проблем не возникает, но при использовании
асинхронного подхода с библиотекой **aiohttp**  из условных 20 запросов успешными будут не больше 5-ти.
В обоих случаях используются одинаковые параметры запросов.

В качестве параметров передаю например такое (выгрузка первых 20 страниц devops-ов):
`{'text': 'devops', 'area': '1', 'per_page': '100', 'page': 6}`

В ответ же получаю 400 ошибку с ответом:
`{"description":"bad argument","errors":[{"type":"bad_request"}],"request_id":"169064378029920c287c3c3d04f9bf7b"}`

**Comment by DanilKnyazev** [comment]
Добрый день!
Выясняем причины. Спасибо за сведения!

**Comment by DanilKnyazev** [comment]
Здравствуйте! Подскажите, пожалуйста, проблема сохраняется?

**Comment by StickKing** [comment]
Здравствуйте, стало лучше, но от 2 до 5 запросов (из 20) всё равно выдают туже самую ошибку

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Попробуйте не превышать допустимые лимиты на частоту запросов к API. Сейчас лимит на кол-во запросов в секунду = 9
