### ISSUE TITLE
Добавить возможность, как на сайте, указать несколько значений для поля образование education_level

### ISSUE THREAD

**Issue by LioneNET** [hhru/api#758]
Не удается указать несколько значений для поля education_level при поиске сотрудников, через **https://api.hh.ru/resumes?education_level=special_secondary&education_level=unfinished_higher**
![image](https://github.com/hhru/api/assets/79297443/45f11adb-5ea8-4979-afe2-070e9e0e2c45)

На сайте поиска сотрудников такая возможность есть.
![image](https://github.com/hhru/api/assets/79297443/204f9afb-d66c-4fa9-8826-4bf261a34e79)

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Спасибо за хорошее замечание! Оно обязательно будет принято во внимание. 
Следите за обновлениями в документации.
