### ISSUE TITLE
Страница теста навыка остается активной после завершения теста 

### ISSUE THREAD

**Issue by vladimirdesyat** [hhru/api#764]
После завершения теста на навык для соискателя, на странице теста в поле кнопки появляется следующая дата проведения теста. Между тем, если в истории браузера открыть вкладку с тестом, то его можно пройти повторно с другим результатом и таймер внутри теста сбрасывается. Работает в браузере Chrome Version 116.0.5845.141 (Official Build) (64-bit), если это важно.

**Comment by DanilKnyazev** [comment]
Здравствуйте! 
Это нормальный сценарий для прохождения теста. Этот тест можно также пройти без авторизации. На результат это не влияет. 
Если у Вас возникают вопросы по работе сайта, рекомендуем задавать их в [сообщество поддержки](https://feedback.hh.ru/ticket/add). 
Спасибо за обращение и хорошего дня!
