### ISSUE TITLE
Цикл редиректов при вводе второго фактора в окне выдачи доступа стороннему приложению

### ISSUE THREAD

**Issue by btravel** [hhru/api#765]
Не работает выдача прав приложению для пользователя с подключенной двухфакторной авторизацией работодателя через email.

**Исходные данные:**

Есть пользователь с уч. записью работодателя и подключенной двухфакторной авторизацией по email.

**Сценарий 1 (успешный):**

1. Открыть страницу входа на hh.ru.
2. Ввести логин и пароль уч. записи работодателя. 
3. Откроется окно для ввода кода второго фактора.
4. Ввести код подтверждения, отправленный на email.
5. Пользователь успешно авторизовался на hh.ru.
6. Запустить в стороннем приложении процесс "Пользовательской авторизации на hh.ru" для выдачи прав доступа к приложению.
7. Откроется модальное окно для подтверждения выдачи прав приложению к уч. записи пользователя.
8. Подтвердить выдачу прав доступа.

**Результат:** Пользователь успешно авторизован на hh.ru, стороннему приложению выдан доступ к уч. записи пользователя.

**Сценарий 2 (ошибка):**

1. Сделать logout пользователя на hh.ru 
2. Запустить в стороннем приложении процесс "Пользовательской авторизации на hh.ru" для выдачи прав доступа к приложению.
3. Откроется модальное окно для ввода логина и пароля.
4. Ввести логин и пароль  уч. записи работодателя из сценария 1.
5. Отобразится форма для ввода кода второго фактора.
6. Ввести код подтверждения, отправленный на email (приходит точно такой же код, как и в сценарии 1).

**Результат:**
В модальное окне происходит серия редиректов внутри ресурсов hh.ru, которая заканчивается ошибкой "Сайт hh.ru выполнил переадресацию слишком много раз".

<img width="701" alt="Снимок экрана 2023-09-06 в 09 46 37" src="https://github.com/hhru/api/assets/21336941/64f9422d-528a-4bc4-ba6e-d4b1142dd1d2">

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Не могли бы Вы, пожалуйста, предоставить URL, по которому настроен процесс получения авторизации?

**Comment by btravel** [comment]
Параметры открытия окна:

```
window.open(
      'https://hh.ru/oauth/authorize?response_type=code&client_id=наш_идентификатор_клиента&redirect_uri=https://наш_сайт&state=a072e384-c791-4e8a-b698-5baa920bb6f1',
      'hh',
      'width=600,height=600,left=100,top=100'
    );
```

Значение параметра state указано в качестве примера - оно содержит уникальный uuid для каждого открытия.

**Comment by btravel** [comment]
Как я описал выше в сценариях, если открывать окно c таким же URL и параметрами window.open, но предварительно авторизовавшись на сайте hh.ru, то проблема не возникает, интеграция подключается. Ошибка возникает только при логине и вводе второго фактора в окне.

**Comment by btravel** [comment]
> Добрый день. Сообщите, пожалуйста, redirect_uri, который вы использовали в приложении. Нам необходимо воспроизвести ошибку, чтобы затем ее всесторонне исследовать. Или это ваш внутренний адрес и из внешки он не доступен?

Значение параметра redirect_uri имело вид https://subdomain.example.com/oauth

Проблема оказалась в отсутствующей кодировке значения параметра redirect_uri. После кодирования строки через encodeURIComponent(redirect_uri) ошибка больше не воспроизводится.
