### ISSUE TITLE
Разные результаты при получении ответа на запрос

### ISSUE THREAD

**Issue by fatherlandboy** [hhru/api#767]
Отправляю запрос к api с поиском слова "Территориальный" (менеджер) в вакансиях и получаю не только территориальных менеджеров а также региональных, супервайзеров и прочих. Несмотря на то, что даже установить фильтр "Искать только в названии вакансии" api выдает также "Региональный менеджер", "Супервайзер" и т.д. Ни в названии ни в описании подобных вакансий не фигурирует слово "Территориальный"

https://hh.ru/search/vacancy?no_magic=true&L_save_area=true&text=%D0%A2%D0%B5%D1%80%D1%80%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9&search_field=name&excluded_text=&area=63&salary=&currency_code=RUR&experience=doesNotMatter&order_by=relevance&search_period=0&items_on_page=100

Просьба помочь в решении вопроса

**Comment by DanilKnyazev** [comment]
Здравствуйте. 
Так происходит из-за синонимо в названиях вакансий. Чтобы выдача соответствовала поисковой фразе рекомендуем добавить перед запросом восклицательный знак:
https://hh.ru/search/vacancy?no_magic=true&L_save_area=true&text=%21%D0%A2%D0%B5%D1%80%D1%80%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9&search_field=name&excluded_text=&area=63&salary=&currency_code=RUR&experience=doesNotMatter&order_by=relevance&search_period=0&items_on_page=100

**Comment by fatherlandboy** [comment]
Сработало, спасибо за помощь!
