### ISSUE TITLE
Как я могу откликнуться на вакансию?

### ISSUE THREAD

**Issue by loganbaby** [hhru/api#774]
в API есть метод:

```
https://api.hh.ru/vacancies/{vacancy_id}/similar_vacancies
```

в ответе можно найти следующие данные:

```
"apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=8331228"
```

переход по этой ссылке позволяет откликнуться на вакансию. но как я могу откликнуться на вакансию через API?

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Вы можете зная resume_id и vacancy_id откликнуться на вакансию используя [метод](https://github.com/hhru/api/blob/master/docs/negotiations.md#post_negotiation). В теле метода нужно передать resume_id и vacancy_id
