### ISSUE TITLE
Список архивных вакансий - неверное значение в документации

### ISSUE THREAD

**Issue by Solo-it** [hhru/api#780]
В документации написано что 10 000 можно на странице получать
По факту только 1000

integer
Количество элементов на странице выдачи. Поддерживаются [стандартные параметры пагинации](https://github.com/hhru/api/blob/master/docs/general.md#pagination). Значение по умолчанию и максимальное значение per_page составляет 10000

**Comment by Solo-it** [comment]
https://api.hh.ru/openapi/redoc#tag/Upravlenie-vakansiyami/operation/get-archived-vacancies

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Спасибо за справедливое замечание! 
В ближайшее время исправим
