### ISSUE TITLE
Неизвестная ошибка

### ISSUE THREAD

**Issue by loganbaby** [hhru/api#782]
```{'description': '"enable_applicant_visibility_in_country" param required'}```

Данная ошибка возвращает код 400 и возникает после отправки запроса, который позволяет откликнуться на вакансию:
https://github.com/hhru/api/blob/master/docs/negotiations.md#post_negotiation

причем, работает в 99% случаев, но у некоторых юзеров моего приложения не срабатывает, вызывается эта ошибка. в документации описания не нашел. в чем причина?

**Comment by DanilKnyazev** [comment]
Здравствуйте. 
Так происходит, потому что соискатель не дал согласие на передачу персональных данных в личном кабинете. Вероятнее всего это соискатели из Беларуси. 
Страница, на которой соискатель может дать согласие - https://rabota.by/applicant/settings/resume_countries_visibility

**Comment by loganbaby** [comment]
Спасибо! Учту это, при дальнейшей разработке.

Также хотелось бы отметить, что в документации этой ошибки нет. Есть ли еще какие-то "секретные" типы ошибок? Где я могу их увидеть? Можете ли вы обновить документацию?
