### ISSUE TITLE
typo: Опечатка в определении параметра OpenAPI

### ISSUE THREAD

**Issue by oshliaer** [hhru/api#794]
## Как есть

По адресу https://api.hh.ru/openapi/redoc#tag/Otklikipriglasheniya-rabotodatelya/operation/put-negotiations-collection-to-next-state в части **Действия по откликам/приглашениям** в разделе **REQUEST BODY SCHEMA** параметр `topic_id` описан как _Идентификаторы **топиков**_.

<details>
  <summary>Картинка с обозначением места</summary>
<img src="https://github.com/hhru/api/assets/5027939/d12ff443-da01-4692-9de2-9d1c390b8c02">
</details>

## Как должно быть

Параметр `topic_id` Идентификаторы **откликов**

**Comment by DanilKnyazev** [comment]
Здравствуйте. 
Опечатка исправлена. Спасибо
