### ISSUE TITLE
Просьба добавить Education в короткую модель при поиске вакансий

### ISSUE THREAD

**Issue by JustickDM** [hhru/api#797]
Очень, настоятельно хочется видеть данные по образованию в короткой модели при поиске вакансий. В противном случае, приходится делать кучу лишних запросов на сервер, чтобы получить полную информацию о вакансии. Лишнее время, лишняя нагрузка на сервера, хотя поле очень важное в определении вакансии, даже в кратком.

**Comment by JustickDM** [comment]
@tpasichnik Есть кто живой?

**Comment by tpasichnik** [comment]
Добрый день.

Новые поля в GET /vacancies добавляться не будут, в связи со внутренними техническими ограничениями.

**Comment by JustickDM** [comment]
Можно просто ответить "Впадлу". "Технические ограничения" это настолько смешно, что не смеяться не хочется. Ощущение, будто у вас сидят бездари. Смысл такого саппорта вообще?
