### ISSUE TITLE
Неверные координаты у метро "Терехово" в Москве

### ISSUE THREAD

**Issue by opeeen** [hhru/api#805]
Текущие координаты в API указывают на город Электросталь

Текущие координаты в API - "lat":55.749167,"lng":38.460556
Правильные координаты метро по Яндекс Картам - "lat":55.748108,"lng":37.459738

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Приносим свои извинения за такую неточность. Уже исправили! Спасибо за обращение!
