### ISSUE TITLE
403 ошибка с переадресацией на captcha при получении вакансии

### ISSUE THREAD

**Issue by NiceOneFox** [hhru/api#809]
Здравствуйте, мне необходимо выгрузить все вакансии по идентификатору api.hh.ru/vacancies/{vacancy_id} однако при получении некоторых из них в ответе приходит 403 и ссылка на прохождение captcha. Данный метод вызываю без предварительной авторизации. 
Если я авторизуюсь через приложение зарегистрированное через личный кабинет, смогу ли я получать вакансии без необходимости ввода captcha. Т.к я не использую интерфейс для выгрузки вакансий, то ввод captcha для меня становится проблемным местом.

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Да, авторизация приложения избавит от необходимости вводить CAPTCHA.
