### ISSUE TITLE
Неверный формат даты/времени

### ISSUE THREAD

**Issue by somepad** [hhru/api#81]
Коллеги, [вот тут](https://github.com/hhru/api/blob/master/docs/general.md) сказано:
> Даты форматируются в соответствии с ISO 8601: YYYY-MM-HHThh:mm:ss±hh:mm

Однако в ответе метода `GET /resumes/mine` все поля дат имеют формат
`YYYY-MM-HHThh:mm:ss±hhmm`
Приходится городить нечто подобное: `s/(.+)(\d{2})/$1:$2/`
Поправьте, плз.

**Comment by maizy** [comment]
В данном случае имеет место ошибка в документации. Везде в нашем api мы выдаём даты в формате `YYYY-MM-HHThh:mm:ss±hhmm`. В том числе и в `GET /resumes/mine`.

Документацию поправим, спасибо.

**Comment by maizy** [comment]
исправили 429405d9b9dc30da4c4aa859ffd57ed1e7e87fab
