### ISSUE TITLE
История звонков недоступна работодателю? 

### ISSUE THREAD

**Issue by batiyaa** [hhru/api#816]
Метод не отдаёт отклик с историей звонков от лица работодателя/менеджера https://api.hh.ru/negotiations/{negotiations_id} 

Историю звонков невозможно получить от лица? Если нет, то когда-нибудь появится такая возможность?

**Comment by DanilKnyazev** [comment]
Здравствуйте. 
Уточните, пожалуйста, что имеется ввиду.
Список звонков, которые сделал менеджер?
Или список звонков по вакансии?

**Comment by DanilKnyazev** [comment]
На текущий момент можно вызвать список коллекций по вакансии с флагом `with_generated_collections`, если по учетной записи работодателя не отключался call tracking (подмена номера), то в ответе придет collections[].phone_calls :

```
{
            "id": "phone_calls",
            "name": "Звонки",
            "description": "В эту коллекцию попадают отклики, по которым есть пропущенные и входящие звонки.",
            "url": "https://api.hh.ru/negotiations/phone_calls?vacancy_id={id}",
            "order_types": [
                {
                    "id": "last_change_time_except_employer_inbox",
                    "name": "По дате создания и активности соискателя",
                    "url": "https://api.hh.ru/negotiations/phone_calls?vacancy_id={id}&order_by=last_change_time_except_employer_inbox"
                },
                {
                    "id": "created_at",
                    "name": "По дате отклика",
                    "url": "https://api.hh.ru/negotiations/phone_calls?vacancy_id={id}&order_by=created_at"
                }

```
исходя из полученной информации можно сделать запросы на url и получить отклики, по которым есть пропущенные и входящие звонки.
