### ISSUE TITLE
Ограничение отправки откликов через API

### ISSUE THREAD

**Issue by Gidwin** [hhru/api#817]
Добрый день, существует метод API для отправки откликов. Знаю, что ограничение составляет 200 в день, но в какое время оно обнуляется, когда достигнут лимит? А если лимит не достигнут, внутреннее ограничение когда спадает? Буду признателен за разъяснение.

**Comment by DanilKnyazev** [comment]
Здравствуйте.
На текущий момент лимит в 200 откликов в сутки рассчитывается динамически. Соискатель совершает отклик и в промежутке 24 часа **до** этого отклика считается количество откликов соискателя, если в этом промежутке было 200 откликов, то соискатель получает ошибку 429.
