### ISSUE TITLE
403 при попытке откликнуться на вакансию

### ISSUE THREAD

**Issue by CodeWhiz101** [hhru/api#819]
Здравствуйте! Пытаюсь откликнуться на вакансии  с помощью **POST /negotiations** метода.

Используя токен приложения получаю в ответ `{"description":"Forbidden","errors":[{"type":"forbidden"}],"request_id":"1711371171318898510c68179018e31e"}`

При использовании токена юзера получаю в ответ `{"description":"Forbidden","errors":[{"value":"bad_authorization","type":"oauth"}],"request_id":"171137152671106baaeaa61bb1e94b7d"}`

Реализация:
```
def respond_to_job(resume_id, vacancy_id, message=None):
    url = "https://api.hh.ru/negotiations"
    headers = {
        "Authorization": f"Bearer {ТОКЕН}",
        "HH-User-Agent": "Имя приложения/1.1 (Почта)"
    }
    data = {"resume_id": resume_id, "vacancy_id": vacancy_id, "message": message}
    response = requests.post(url, headers=headers, json=data)
    if response.status_code == 201:
        print("Successfully responded to job")
        print("Negotiation created at:", response.headers.get("Location"))
    else:
        print("Failed to respond to job")
        print("Status code:", response.status_code)
        print("Response:", response.text)
```

Повторная генерация токенов не помогает, смена HH-User-Agent на User-Agent тоже.
Прошу помочь с данной проблемой, заранее спасибо!

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Этот запрос доступен только с [авторизаций пользователя](https://github.com/hhru/api/blob/master/docs/authorization_for_user.md)

**Comment by CodeWhiz101** [comment]
> Здравствуйте. Этот запрос доступен только с [авторизаций пользователя](https://github.com/hhru/api/blob/master/docs/authorization_for_user.md)



При использовании токена юзера (То есть, при использовании авторизации пользователя, как в документации) получаю в ответ {"description":"Forbidden","errors":[{"value":"bad_authorization","type":"oauth"}],"request_id":"171137152671106baaeaa61bb1e94b7d"}

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Судя по логам, авторизация пользователя не передается.
Попробуйте проверить свой запрос через cURL, подставив свое значение вместо `{bearer}`:
`curl 'https://api.hh.ru/me' -X GET -H 'Authorization: Bearer {bearer}'`

**Comment by CodeWhiz101** [comment]
Здравствуйте,

В ответ получаю: 

`{"auth_type":"application","is_applicant":false,"is_employer":false,"is_admin":false,"is_application":true,"is_employer_integration":false}`

При попытке реализовать с запрос с курла напрямую: 

`curl -X POST "https://api.hh.ru/negotiations" -H "Authorization: Bearer {bearer}" -H "HH-User-Agent: ResumeSender/1.1 (l5dkap@outlook.com)"  -H "Content-Type: application/json" -d '{"resume_id": " {resume_id_value}", "vacancy_id": " {vacancy_id_value}", "message": " {message_text}"}'`
     
Получаю так же: `{"description":"Forbidden","errors":[{"type":"forbidden"}],"request_id":"171611438412112982de72878265fda2"}`

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Для работы с откликами нужно использовать токен пользователя. Вы используете токен приложения. Об этом говорят значения полей, указанных выше: "auth_type":"application", "is_application":true
