### ISSUE TITLE
Стабы ошибок авторизации

### ISSUE THREAD

**Issue by maizy** [hhru/api#82]
:white_check_mark:Описать ошибки:
- :white_check_mark: старый токен
- :white_check_mark: не валидный токен
- :white_check_mark: приложение отозвано
- :white_check_mark: авторизация отозвана пользователем
- https://github.com/hhru/api/blob/master/docs/errors.md#oauth

Выложить конфигурацию и стабы [какого-нибудь сервера для создания http стабов](https://www.google.ru/webhp?q=http+stubs+server#newwindow=1&q=http+stubs+server) или файлы с ресурсами для unit тестов.

**Comment by somepad** [comment]
Сейчас есть насущный вопрос по этому тикету:
1. Как ответ прилетит от api.hh.ru при попытке что-то сделать с истекшим токеном?
2. Какой будет код ответа сервера?

**Comment by maizy** [comment]
> Сейчас есть насущный вопрос по этому тикету:

Новую документацию уже готовим.

> 1. Как ответ прилетит от api.hh.ru при попытке что-то сделать с истекшим токеном?
> 2. Какой будет код ответа сервера?

```
HTTP/1.1 403 Forbidden
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ETag, Date, Expires, Cache-Control, Content-Type, X-Request-ID
Connection: keep-alive
Content-Length: 134
Content-Type: application/json; charset=UTF-8
Date: Thu, 23 Apr 2015 12:08:28 GMT

{
    "errors": [
        {
            "type": "oauth", 
            "value": "token_expired"
        }
    ]
}
```

Данных на самом деле будет чуть больше, но ориентироваться нужно именно на указынные выше, часть ключей в ответе в устаревшем формате и оставлена для совместимости с существующими клиентами.

**Comment by somepad** [comment]
Что сервер будет отвечать на запрос refresh_token? Тоже, что и на запрос его получения или..?

**Comment by maizy** [comment]
Полностью аналогичный том, что приходит после получения токена в первый раз.

**Comment by maizy** [comment]
Немного обновили документацию по авторизации.
Измнения - f039af297381c009381252c359dae8af2e8184f2.
Готовый результат - https://github.com/hhru/api/blob/auth/docs/authorization.md

Учли вопрос про refresh токена.

Стабы ответов и описание ошибок можно ожидать в ближайшее время.

**Comment by maizy** [comment]
Добавили описание ошибок авторизации - https://github.com/hhru/api/blob/master/docs/errors.md#oauth

**Comment by maizy** [comment]
+2 от различных клиентов

**Comment by tnovikov** [comment]
Подскажите, плз, если у меня не было refresh_token (access_token получил через https://dev.hh.ru/admin ) как мне его рефрешить? Т.е. приложение должно работать без участия пользователя и, соответственно без авторизации. Спасибо

**Comment by maizy** [comment]
про refresh ответил тут - https://github.com/hhru/api/issues/50#issuecomment-201179602

про авторизацию сервер-сервер. вот кусочек FAQ который мы сейчас собираем по api.

---

Мы поддерживаем только 3-х шаговый процесс авторизации пользователей, так как он самый безопасный и не требует пользователю передавать свой пароль от учётной записи приложению, которому необходим доступ от имени этого пользователя.

Более того, хранение логинов и паролей пользователя, явно запрещено в условиях использования API - https://dev.hh.ru/admin/developer_agreement (п. 3.6).

Рекомендуем поступать так:

* На первый запрос, где требуется авторизация в HH API, или просто заранее проводить пользователя по процессу авторизации, как он описан в [нашей документации](https://github.com/hhru/api/blob/master/docs/authorization.md). При необходимости, это можно делать в новом popup/iframe окне браузера, встроенном web-компоненте (web view, IE Embedded и подобных), открывать в системном браузере и использовать другие способы. Пользователю нужно будет авторизоваться своей учётной записью на hh.ru.
* После получения access token и refresh token сохранить их и привязать к пользователю вашей системы.
* Access token будет работать примерно в течении 2-х недель. Затем, по истечения жизни Access token, с помощью Refresh token можно получить новую пару Access & refresh token.

Главное, что кроме первого шага в дальнейшем все операции происходят сервер-сервер или сервер-приложение, не вовлекая пользователя.

Для использования в desktop приложениях мы позволяем использовать custom schemes в redirect_uri приложений, вроде `myapp://backurl`. В большинстве операционных систем (Windows, iOs, Android, OS X) такие схемы можно зарегистрировать на приложение. При использовании такого способа можно использовать обычный системный браузер, который после проведения авторизации, вернёт управление вашему приложению.

**Comment by tnovikov** [comment]
Спасибо за ответ, этот вариант подходит, хотя и, согласитесь, не особо friendly)

**Comment by maizy** [comment]
+1 от клиента
