### ISSUE TITLE
Не работает параметр  host

### ISSUE THREAD

**Issue by ZhenkaP** [hhru/api#823]
Здравствуйте!
```
params = {"text": "python", "host":"hh.kz"}
response = requests.get(url="https://api.hh.ru/vacancies",headers=headers, params=params)
resp = response.json()
```
В данном запросе получаю вакансии для России, а не для Казахстана. Указаны Москва, Санкт-Петербург и другие города.
При этом запрос по данному url показывает вакансии из Казахстана:
```
https://hh.kz/search/vacancy?text=python&area=159&hhtmFrom=main&hhtmFromLabel=vacancy_search_line
```
Подскажите, пожалуйста, как получить через API вакансии для Казахстана.

**Comment by DanilKnyazev** [comment]
Здравствуйте.
Достаточно использовать [в поисковом запросе API](https://api.hh.ru/openapi/redoc#tag/Poisk-vakansij/operation/get-vacancies) `area=159`
