### ISSUE TITLE
Расхождения в поисковой выдаче

### ISSUE THREAD

**Issue by Kavushafull** [hhru/api#826]
При сравнении одинакового поискового запроса через API и браузер получаем разное количество подходящих резюме (через API на 5-10% меньше). Пример передаваемых параметров:
```
{
    "area": ["160", "2653", "3048"], 
    "relocation": "living", 
    "citizenship": "40", 
    "period": 1, 
    "employment": "full", 
    "schedule": "fullDay", 
    "language": "rus", 
    "language.level": "b2", 
    "job_search_status": ["active_search", "looking_for_offers"], 
    "age_from": "18", 
    "age_to": "50", 
    "salary_from": 0, 
    "salary_to": 300000, 
    "currency": "KZT"
}
```

**Comment by DanilKnyazev** [comment]
Здравствуйте!
Не могли бы вы, пожалуйста, предоставить примеры поисковых запросов из браузера и через API?
А также время и логин пользователя, от которого осуществляется поиск
