### ISSUE TITLE
Выгрузка вакансий

### ISSUE THREAD

**Issue by NiceOneFox** [hhru/api#827]
Здравствуйте, процесс выгрузки вакансий по одной вакансии занимает существенное время с учётом более 90 миллионов записей. Даже с учётом опроса 4500 вакансий в минуту.
Есть ли возможность предоставить выгруженные данные по вакансиям из бд за все время или какие то другие способы выгрузки вакансий?

**Comment by DanilKnyazev** [comment]
Здравствуйте!
Поиск вакансий предназначен для поиска позиций по определенным критериям в целях трудоустройства соискателей. Подразумевается, что соискатель ведет поиск по 1 или нескольким смежным специальностям, также уменьшая круг поиска различными параметрами. 
Доступ ко всей базе вакансий за все время мы не предоставляем.
Подскажите, пожалуйста, какие цели преследуете? 
возможно, я смогу порекомендовать более оптимальный способ использования поиска вакансий.
