### ISSUE TITLE
403 Forbidden при поиске резюме

### ISSUE THREAD

**Issue by Andrey-VLV** [hhru/api#829]
Подскажите, пожалуйста, в чём проблема. Пытаюсь выполнить поиск резюме по ключевым словам python developer, получаю в ответе 403 forbidden (request_id 1715871071937a6d23d0a5bdff5a8094).
![Screenshot](https://github.com/hhru/api/assets/77433979/8dfeb2ad-75eb-4953-96cf-9d22617b47c8)

Токен валиден, подписка на платные вызовы куплена
![1_censored](https://github.com/hhru/api/assets/77433979/1663db53-f3fa-464b-a90d-4e7b97707bb9)

В запросе указан токен пользователя, пользователь employer
![2_censored](https://github.com/hhru/api/assets/77433979/f6c09697-60b3-4921-946a-0dc6c3a10d57)

**Comment by DanilKnyazev** [comment]
Для поиска по базе резюме нужно использовать http-метод GET. У вас был POST
