### ISSUE TITLE
HH API resumes/{id}/publish POST 403 Forbidden type forbidden

### ISSUE THREAD

**Issue by igorkravitz** [hhru/api#831]
Здравствуйте, проблема с методом publish
Вызываю команду
POST https://api.hh.ru/resumes/{resume_id}/publish
В ответ приходит
Код состояния: 403
`{
  "description": "Forbidden",
  "errors": [
    {
      "type": "forbidden"
    }
  ],
  "request_id": "1716059545550477d04166e592878534"
}`
Другая команда с теми же заголовками, параметрами
GET https://api.hh.ru/resumes/{resume_id}/status
Возвращает
Код состояния: 200
`{
  "status": {
    "id": "published",
    "name": "опубликовано"
  },
  "blocked": false,
  "finished": true,
  "moderation_note": [],
  "can_publish_or_update": true,
  "publish_url": "https://api.hh.ru/resumes/*****************/publish?locale=RU&host=hh.ru",
  "progress": {
    "percentage": 93,
    "mandatory": [],
    "recommended": [
     {
        "id": "district",
        "name": "Район проживания"
      },
      {
        "id": "birth_date",
        "name": "Дата рождения"
      },
      {
        "id": "hidden_fields",
        "name": "Список скрытых полей"
      },
      {
        "id": "education",
        "name": "Образование"
      }
    ]
  }
}`
Авторизацию пользователя успешно выполнил. Получил access_token, refresh_token.
Прошу помочь разобраться с ошибкой.

**Comment by DanilKnyazev** [comment]
Здравствуйте.
В запросе с идентификатором 1716059545550477d04166e592878534 не передается токен авторизации пользователя в заголовке Authorization: Bearer {token}. Данный запрос был анонимным
Рекомендуем в случае возникновения проблем проверять работоспособность запроса REST-клиентом таким как cURL, Postman или Insomnia
