### ISSUE TITLE
Реалтайм получение сообщений кандидатов

### ISSUE THREAD

**Issue by Viktor-Pan** [hhru/api#837]
Добрый день, хочу предложить улучшение: получение новых сообщений от соискателей по Webhook. Было бы оптимальнее получать новые сообщения по событию, чем постоянно дудосить ваш апи на предмет новых сообщений

**Comment by DanilKnyazev** [comment]
Здравствуйте!
Спасибо за предложение!
На текущий момент у нас в планах поддержать функциональность в чатах с соискателем в API, как на сайте. После этого мы обязательно сделаем Webhook по этому событию.
