### ISSUE TITLE
Lifetime refresh токена

### ISSUE THREAD

**Issue by Dimkashow** [hhru/api#838]
Подскажите какой lifetime у refresh токена. https://api.hh.ru/openapi/redoc#section/Avtorizaciya/Obnovlenie-pary-access-i-refresh-tokenov

**Comment by DanilKnyazev** [comment]
Здравствуйте!
Если пара токенов не обновлялась и пользователь не менял пароль, то refresh_token можно использовать спустя неограниченное время.
