### ISSUE TITLE
Определение отклика/приглашения в вебхуке

### ISSUE THREAD

**Issue by yamplum** [hhru/api#842]
Привет. Насколько я пойму из [документации](https://api.hh.ru/openapi/redoc#tag/Webhook-API/operation/post-webhook-subscription), в подписку на события типа `NEW_RESPONSE_OR_INVITATION_VACANCY` попадают как отклики, так и приглашения, без разделения. Можно ли как-то определить тип получаемых объектов? Я немного покопал вариант получения всех откликов, но по ощущениям там требуется куча дополнительных запросов.

**Comment by DanilKnyazev** [comment]
Здравствуйте!
Чтобы понять был отклик или приглашение по подписки на событие. Необходимо сделать [запрос](https://api.hh.ru/openapi/redoc#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiation-item) и по полю employer_state посмотреть в случае отклика будет response, приглашение - другое наименование коллекции
