### ISSUE TITLE
Пустой блок contacts

### ISSUE THREAD

**Issue by vmakhlay** [hhru/api#843]
Добрый день!

Вызываю метод получения информации о вакансии с токеном приложения
GET https://api.hh.ru/vacancies/*

С заголовками 

{'HH-User-Agent': '*** (Application ***) (*****@yandex.ru)', 'Authorization': 'Bearer ***'}

Получаю ответ со всеми данными по вакансии, кроме блока contacts - он есть, но значения в нем пустые, хоть и в самой вакансии на сайте контакты есть
```
{
'contacts': {'name': None, 'email': None, 'phones': []}
}
```

Подскажите, плз, что делаю не так

**Comment by DanilKnyazev** [comment]
Здравствуйте!
Контакты вакансии доступны только с авторизацией пользователя.
