### ISSUE TITLE
Ошибка авторизации пользователя

### ISSUE THREAD

**Issue by LiRiK000** [hhru/api#846]
Добрый день, при авторизации пользователя начала вылезать 403 ошибка, хотя раньше ее не было, могу я как-то ее избежать? Что для этого необходимо сделать?
`
    const response = await axios.post('https://hh.ru/oauth/token', null, {
      params: {
        grant_type: 'authorization_code',
        client_id: process.env.NEXT_PUBLIC_CLIENT_ID,
        client_secret: process.env.NEXT_PUBLIC_CLIENT_SECRET,
        code,
      },
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
    });
`
Код со стороны пользователя приходит, все передается адекватно и т.д.
Пока не нашел решения

**Comment by DanilKnyazev** [comment]
Здравствуйте!
К сожалению, вы не предоставили request_id, который приходит в JSON-теле ответа. Предполагаю, что не отправлялся User-Agent. Рекомендуем передавать данный заголовок для всех запросов
