### ISSUE TITLE
API для проверки данных вакансии перед публикацией

### ISSUE THREAD

**Issue by andrey158** [hhru/api#89]
Добрый день, сделайте, пожалуйста, API для проверки данных, указанных в запросе на публикацию, без фактической публикации.

В нашем случае ввод информации и собственно публикация происходит с разницей во времени, поэтому, если пользователь что-то не так указал, об ошибке он узнает не сразу.

Спасибо.

**Comment by maizy** [comment]
задача понятна, учтём
