### ISSUE TITLE
Получение резюме по идентификатору

### ISSUE THREAD

**Issue by kibasteg** [hhru/api#91]
Насколько я понял, у каждого резюме может быть несколько идентификаторов в зависимости от зарегистрированного пользователя?

Дело в том, что получение резюме /resumes/{resume_id} иногда отдает 404 ошибку.
На самом деле это резюме существует, но открыто оно было пользователем, отличным от того, который авторизован в API.

На сайте резюме с такой ссылкой просматривается корректно. AP, к сожалению, возвращает 404 ошибку.

Баг ли это?

**Comment by maizy** [comment]
Это намеренное поведение. 
При правильном использовании api такого происходить не должно.
Каким образом вы получаете эти id резюме?

**Comment by kibasteg** [comment]
Опишу суть.
Для компании была разработана своя система учета контроля просмотров резюме.
Сотрудник вставляет ссылку, система берет из нее id, получает данные резюме, отправляет данные сотруднику. Сам сотрудник возможно получил такую ссылку по email от компании-партера.

**Comment by maizy** [comment]
> Сам сотрудник возможно получил такую ссылку по email от компании-партера.

Такое использование API не подразумевается, так как может означать перепродажу доступа к контактной информации о резюме.

**Comment by kibasteg** [comment]
Ответ понятен, спасибо.
Тогда возможен ли вариант открытия доступа к API поиска резюме для написания внутренней поисковой системы и использования ее в рамках кадрового холдинга?

**Comment by maizy** [comment]
Напишите запрос по правилам описанным здесь - https://github.com/hhru/api/blob/master/docs/resumes.md#search мы его рассмотрим.
