### ISSUE TITLE
Более подробно описать ограничения на глубину выдачи в поиске вакансий/резюме

### ISSUE THREAD

**Issue by maizy** [hhru/api#94]
Не все это понимают.

Суть в том, что ограничение на *глубину* выдачи в N штук.
Например, вакансии ограничены 2000, страницы считаются с 0, значит
`per_page=10&page=199` - ок (выдача с 1991 по 2000), но `per_page=10&page=200` уже ошибка (выдача с 2001 до 2010).

**Comment by a-pertsev** [comment]
По-моему, две одинаковые квери в описании?

**Comment by maizy** [comment]
fixed
![doh](https://cloud.githubusercontent.com/assets/789623/7831619/0b2f2afe-0461-11e5-9620-6d52cb25fca4.jpg)

**Comment by maizy** [comment]
Добавили более подробное описание - https://github.com/hhru/api/commit/3e5a0858ab8b4f1bda46af4faf6fe882ff5e09a2

резюме - https://github.com/hhru/api/blob/master/docs/resumes.md#search
вакансии - https://github.com/hhru/api/blob/master/docs/vacancies.md#search
